// React/src/components/shared/Skeleton.tsx
import React from 'react';

export interface SkeletonProps {
  width?: number | string;
  height?: number | string;
  radius?: number | string;
  style?: React.CSSProperties;
}


export const Skeleton: React.FC<SkeletonProps> = ({ width = '100%', height = 16, radius = 4, style }) => (
  <div
    className="skeleton-shimmer"
    aria-hidden="true"
    style={{ width, height, borderRadius: radius, ...style }}
  />
);

// Angular/src/app/shared/skeleton/skeleton.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'app-skeleton',
  standalone: true,
  imports: [],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<div class="skeleton-shimmer" [style.width]="width" [style.height]="height" [style.border-radius]="radius" aria-hidden="true"></div>`,
})
export class SkeletonComponent {
  @Input() width: string | number = '100%';
  @Input() height: string | number = '16px';
  @Input() radius: string | number = '4px';
}
