// Angular/src/app/pages/dashboard/dashboard-page.component.ts
import { Component, inject, OnInit, ChangeDetectionStrategy, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { map } from 'rxjs';
import {
  ChartModule,
  CategoryService,
  StackingColumnSeriesService,
  ColumnSeriesService,
  LegendService,
  TooltipService,
  DataLabelService,
  HighlightService,
  SelectionService,
} from '@syncfusion/ej2-angular-charts';
import { ListViewModule } from '@syncfusion/ej2-angular-lists';
import { HealthcareService } from '../../core/api/healthcare.service';
import {
  APPOINTMENT_TYPE_SERIES,
  BAR_RAMP,
  buildValueAxis,
  chartFillHeight,
  CHART_LEGEND_SETTINGS,
  HIDDEN_LEGEND_SETTINGS,
  COLUMN_WIDTH,
  COLUMN_CORNER_RADIUS,
  CHART_SELECTION_MODE,
  CHART_HIGHLIGHT_MODE,
  chartThemeName,
} from '../../core/utils/chart-theme';
import { ThemeService } from '../../core/theme/theme.service';
import { okOrThrow } from '../../core/api/api.service';
import { createAsyncResult } from '../../core/async/async-result';
import { KpiCardComponent } from '../../shared/kpi-card/kpi-card.component';
import { LoadingStateComponent } from '../../shared/loading-state/loading-state.component';
import { ErrorBannerComponent } from '../../shared/error-banner/error-banner.component';
import { EmptyStateComponent } from '../../shared/empty-state/empty-state.component';
import {
  LucideCalendarDays,
  LucideUserCheck,
  LucideClock,
  LucideTrendingUp,
  LucideListChecks,
} from '@lucide/angular';
import type {
  AppointmentSummaryDto,
  DashboardKpiDto,
  VolumeDataPointDto,
  UtilizationDataPointDto,
} from '../../core/models/dtos';

interface StatusStyle {
  fg: string;
  bg: string;
  label: string;
}

const STATUS_STYLES: Record<string, StatusStyle> = {
  Scheduled: { fg: 'var(--color-sf-cyan-700)', bg: 'var(--color-sf-cyan-50)', label: 'Scheduled' },
  Confirmed: { fg: 'var(--color-sf-success-700)', bg: 'var(--color-sf-success-50)', label: 'Confirmed' },
  CheckedIn: { fg: 'var(--color-sf-brand-700)', bg: 'var(--color-sf-brand-50)', label: 'Checked In' },
  InProgress: { fg: 'var(--color-sf-warning-700)', bg: 'var(--color-sf-warning-50)', label: 'In Progress' },
  Completed: { fg: 'var(--color-sf-fg-secondary)', bg: 'var(--color-sf-bg-tertiary)', label: 'Completed' },
};

const NEUTRAL_STATUS: StatusStyle = {
  fg: 'var(--color-sf-fg-tertiary)',
  bg: 'var(--color-sf-bg-tertiary)',
  label: 'Scheduled',
};

interface VolumeRow {
  department: string;
  [type: string]: number | string;
}

interface UtilizationRow {
  name: string;
  rate: number;
  color: string;
}

interface UpcomingItem {
  appointmentId: string;
  patientName: string;
  appointmentType: string;
  providerName: string;
  initials: string;
  statusLabel: string;
  statusFg: string;
  statusBg: string;
  time: string;
  day: string;
}

function toYmd(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

function initialsOf(name: string): string {
  const parts = name.trim().split(/\s+/);
  const first = parts[0]?.[0] ?? '';
  const last = parts.length > 1 ? parts[parts.length - 1][0] : '';
  return (first + last).toUpperCase();
}

function relativeDay(dt: Date): string {
  const today = new Date();
  const startOf = (d: Date) => new Date(d.getFullYear(), d.getMonth(), d.getDate()).getTime();
  const diffDays = Math.round((startOf(dt) - startOf(today)) / 86400000);
  if (diffDays === 0) return 'Today';
  if (diffDays === 1) return 'Tomorrow';
  return dt.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
}

function volumeTotal(row: VolumeRow): number {
  return APPOINTMENT_TYPE_SERIES.reduce((sum, s) => sum + ((row[s.type] as number) ?? 0), 0);
}

@Component({
  selector: 'app-dashboard-page',
  standalone: true,
  imports: [
    CommonModule,
    ChartModule,
    ListViewModule,
    KpiCardComponent,
    LoadingStateComponent,
    ErrorBannerComponent,
    EmptyStateComponent,
    LucideCalendarDays,
    LucideUserCheck,
    LucideClock,
    LucideTrendingUp,
    LucideListChecks,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './dashboard-page.component.html',
  styleUrl: './dashboard-page.component.scss',
  providers: [
    CategoryService,
    StackingColumnSeriesService,
    ColumnSeriesService,
    LegendService,
    TooltipService,
    DataLabelService,
    HighlightService,
    SelectionService,
  ],
})
export class DashboardPageComponent implements OnInit {
  private healthcare = inject(HealthcareService);
  private theme = inject(ThemeService);

  readonly chartTheme = computed(() => chartThemeName(this.theme.resolved()));
  readonly chartFillHeight = chartFillHeight;

  private readonly rangeStartDate: string;
  private readonly rangeEndDate: string;
  private readonly todayFrom: string;
  private readonly todayTo: string;

  private readonly kpiState = createAsyncResult<DashboardKpiDto>(
    () => this.healthcare.getDashboardKpis().pipe(map((res) => okOrThrow(res))),
    { immediate: false }
  );

  private readonly upcomingState = createAsyncResult<AppointmentSummaryDto[]>(
    () =>
      this.healthcare
        .listAppointments({ dateFrom: this.todayFrom, dateTo: this.todayTo, limit: '200' })
        .pipe(map((res) => okOrThrow(res).items)),
    { immediate: false }
  );

  private readonly UPCOMING_STATUSES = ['Scheduled', 'Confirmed', 'CheckedIn', 'InProgress', 'Completed'];

  private readonly volumeState = createAsyncResult<VolumeDataPointDto[]>(
    () =>
      this.healthcare
        .getAppointmentVolume(this.rangeStartDate, this.rangeEndDate)
        .pipe(map((res) => okOrThrow(res))),
    { immediate: false }
  );

  private readonly utilizationState = createAsyncResult<UtilizationDataPointDto[]>(
    () =>
      this.healthcare
        .getProviderUtilization(this.rangeStartDate, this.rangeEndDate)
        .pipe(map((res) => okOrThrow(res))),
    { immediate: false }
  );

  readonly volumeData = computed<VolumeRow[]>(() => {
    const rows = this.volumeState.data ?? [];
    const byDept = new Map<string, VolumeRow>();
    rows.forEach((d) => {
      let entry = byDept.get(d.departmentName);
      if (!entry) {
        entry = { department: d.departmentName };
        APPOINTMENT_TYPE_SERIES.forEach((s) => (entry![s.type] = 0));
        byDept.set(d.departmentName, entry);
      }
      if (d.appointmentType in entry) {
        entry[d.appointmentType] = (entry[d.appointmentType] as number) + d.count;
      }
    });
    return Array.from(byDept.values()).sort((a, b) => volumeTotal(b) - volumeTotal(a));
  });

  readonly utilizationData = computed<UtilizationRow[]>(() => {
    const rows = this.utilizationState.data ?? [];
    const byProvider = new Map<string, { name: string; appts: number; slots: number }>();
    rows.forEach((d) => {
      const entry = byProvider.get(d.providerName) ?? { name: d.providerName, appts: 0, slots: 0 };
      entry.appts += d.appointmentCount;
      entry.slots += d.totalSlots;
      byProvider.set(d.providerName, entry);
    });
    return Array.from(byProvider.values())
      .map((p) => ({
        name: p.name,
        rate: p.slots > 0 ? Math.round((100 * p.appts) / p.slots) : 0,
        color: '',
      }))
      .sort((a, b) => b.rate - a.rate)
      .slice(0, 8)
      .map((d, i) => ({ ...d, color: BAR_RAMP[i % BAR_RAMP.length] }));
  });

  readonly upcomingItems = computed<UpcomingItem[]>(() => {
    const items = this.upcomingState.data ?? [];
    return items
      .filter((a) => this.UPCOMING_STATUSES.includes(a.status))
      .sort(
        (a, b) => new Date(a.scheduledDateTime).getTime() - new Date(b.scheduledDateTime).getTime()
      )
      .slice(0, 12)
      .map((a) => {
        const dt = new Date(a.scheduledDateTime);
        const s = STATUS_STYLES[a.status] ?? NEUTRAL_STATUS;
        return {
          appointmentId: a.appointmentId,
          patientName: a.patientName,
          appointmentType: a.appointmentType,
          providerName: a.providerName,
          initials: initialsOf(a.patientName),
          statusLabel: s.label,
          statusFg: s.fg,
          statusBg: s.bg,
          time: dt.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
          day: relativeDay(dt),
        };
      });
  });

  readonly kpis = computed(() => this.kpiState.data);
  readonly kpisError = computed(() => this.kpiState.error);
  readonly volumeLoading = computed(() => this.volumeState.loading);
  readonly utilizationLoading = computed(() => this.utilizationState.loading);
  readonly upcomingLoading = computed(() => this.upcomingState.loading);

  readonly volumeError = computed(() => this.volumeState.error);
  readonly utilizationError = computed(() => this.utilizationState.error);
  readonly upcomingError = computed(() => this.upcomingState.error);
  readonly bannerError = computed(() => this.kpiState.error ?? this.upcomingState.error);

  readonly volumePrimaryXAxis = {
    valueType: 'Category',
    title: 'Department',
  };
  readonly volumePrimaryYAxis = {
    title: 'Share',
    labelFormat: '{value}%',
    minimum: 0,
    maximum: 100,
    interval: 20,
  };
  readonly utilizationPrimaryXAxis = {
    valueType: 'Category',
    title: 'Provider',
  };
  readonly utilizationPrimaryYAxis = computed(() =>
    buildValueAxis(this.utilizationData().map((d) => d.rate), {
      title: 'Utilization %',
      labelFormat: '{value}%',
    })
  );
  readonly tooltip = { enable: true };

  readonly legendSettings = CHART_LEGEND_SETTINGS;
  readonly hiddenLegend = HIDDEN_LEGEND_SETTINGS;
  readonly columnWidth = COLUMN_WIDTH;
  readonly cornerRadius = COLUMN_CORNER_RADIUS;
  readonly selectionMode = CHART_SELECTION_MODE;
  readonly highlightMode = CHART_HIGHLIGHT_MODE;

  readonly appointmentTypeSeries = APPOINTMENT_TYPE_SERIES;

  constructor() {
    const end = new Date();
    const start = new Date();
    start.setDate(start.getDate() - 30);
    this.rangeStartDate = toYmd(start);
    this.rangeEndDate = toYmd(end);

    const dayStart = new Date();
    dayStart.setHours(0, 0, 0, 0);
    const dayEnd = new Date();
    dayEnd.setHours(23, 59, 59, 999);
    this.todayFrom = dayStart.toISOString();
    this.todayTo = dayEnd.toISOString();
  }

  ngOnInit(): void {
    this.refresh();
  }

  refresh(): void {
    this.kpiState.refresh();
    this.upcomingState.refresh();
    this.volumeState.refresh();
    this.utilizationState.refresh();
  }

  retryBanner(): void {
    this.kpiState.refresh();
    this.upcomingState.refresh();
  }

  retryVolume(): void {
    this.volumeState.refresh();
  }

  retryUtilization(): void {
    this.utilizationState.refresh();
  }

  retryUpcoming(): void {
    this.upcomingState.refresh();
  }
}

<div>
  @if (bannerError(); as err) {
    <div class="dashboard-banner">
      <app-error-banner
        title="Unable to load dashboard"
        [message]="err"
        (retry)="retryBanner()">
      </app-error-banner>
    </div>
  }

  <div class="dashboard-grid">
    <div id="kpis" class="kpi-row">
      <app-kpi-card
        title="Today's Appts"
        [value]="(kpis()?.totalAppointments ?? '—')"
        [loading]="!kpis() && !kpisError()">
        <ng-template #icon>
          <svg lucideCalendarDays [size]="16"></svg>
        </ng-template>
      </app-kpi-card>

      <app-kpi-card
        title="Completed"
        [value]="(kpis()?.completedAppointments ?? '—')"
        [loading]="!kpis() && !kpisError()">
        <ng-template #icon>
          <svg lucideUserCheck [size]="16"></svg>
        </ng-template>
      </app-kpi-card>

      <app-kpi-card
        title="Avg Wait"
        [value]="kpis() ? (kpis()!.averageWaitTimeMinutes + 'm') : '—'"
        [loading]="!kpis() && !kpisError()">
        <ng-template #icon>
          <svg lucideClock [size]="16"></svg>
        </ng-template>
      </app-kpi-card>

      <app-kpi-card
        title="No-Show Rate"
        [value]="kpis() ? ((kpis()!.noShowRate * 100).toFixed(1) + '%') : '—'"
        [loading]="!kpis() && !kpisError()">
        <ng-template #icon>
          <svg lucideTrendingUp [size]="16"></svg>
        </ng-template>
      </app-kpi-card>

      <app-kpi-card
        title="Open Waitlist"
        [value]="(kpis()?.openWaitlistCount ?? '—')"
        [loading]="!kpis() && !kpisError()">
        <ng-template #icon>
          <svg lucideListChecks [size]="16"></svg>
        </ng-template>
      </app-kpi-card>
    </div>

    <div id="volume" class="dashboard-card chart-card">
      <div class="card-title">Appointment Type Mix by Department</div>
      @if (volumeLoading()) {
        <app-loading-state inline label="Loading appointment volume…"></app-loading-state>
      } @else if (volumeError(); as err) {
        <app-error-banner title="Unable to load appointment volume" [message]="err" (retry)="retryVolume()"></app-error-banner>
      } @else if (volumeData().length === 0) {
        <app-empty-state
          title="No appointment volume"
          description="No appointments in the last 30 days.">
        </app-empty-state>
      } @else {
        <div [style.height]="chartFillHeight({ rows: 1, reserve: 560, cap: 620 })">
          <ejs-chart
            [theme]="chartTheme()"
            [primaryXAxis]="volumePrimaryXAxis"
            [primaryYAxis]="volumePrimaryYAxis"
            [legendSettings]="legendSettings"
            [tooltip]="tooltip"
            [selectionMode]="selectionMode"
            [highlightMode]="highlightMode"
            height="100%">
            <e-series-collection>
              @for (s of appointmentTypeSeries; track s.type; let last = $last) {
                <e-series
                  type="StackingColumn100"
                  [dataSource]="volumeData()"
                  xName="department"
                  [yName]="s.type"
                  [name]="s.type"
                  [fill]="s.color"
                  [columnWidth]="columnWidth"
                  [cornerRadius]="last ? cornerRadius : undefined">
                </e-series>
              }
            </e-series-collection>
          </ejs-chart>
        </div>
      }
    </div>

    <div id="utilization" class="dashboard-card chart-card">
      <div class="card-title">Provider Utilization</div>
      @if (utilizationLoading()) {
        <app-loading-state inline label="Loading provider utilization…"></app-loading-state>
      } @else if (utilizationError(); as err) {
        <app-error-banner title="Unable to load provider utilization" [message]="err" (retry)="retryUtilization()"></app-error-banner>
      } @else if (utilizationData().length === 0) {
        <app-empty-state
          title="No utilization data"
          description="No appointments in the last 30 days.">
        </app-empty-state>
      } @else {
        <div [style.height]="chartFillHeight({ rows: 1, reserve: 560, cap: 620 })">
          <ejs-chart
            [theme]="chartTheme()"
            [primaryXAxis]="utilizationPrimaryXAxis"
            [primaryYAxis]="utilizationPrimaryYAxis()"
            [legendSettings]="hiddenLegend"
            [tooltip]="tooltip"
            [selectionMode]="selectionMode"
            [highlightMode]="highlightMode"
            height="100%">
            <e-series-collection>
              <e-series
                type="Column"
                [dataSource]="utilizationData()"
                xName="name"
                yName="rate"
                name="Utilization %"
                [pointColorMapping]="'color'"
                [columnWidth]="columnWidth"
                [cornerRadius]="cornerRadius">
              </e-series>
            </e-series-collection>
          </ejs-chart>
        </div>
      }
    </div>

    <div id="upcoming" class="dashboard-card upcoming-card">
      <div class="card-title upcoming-title" [class.upcoming-title--bordered]="upcomingItems().length > 0">
        Today's Appointments
      </div>
      @if (upcomingLoading()) {
        <div class="upcoming-body">
          <app-loading-state inline label="Loading upcoming appointments…"></app-loading-state>
        </div>
      } @else if (upcomingError(); as err) {
        <div class="upcoming-body">
          <app-error-banner title="Unable to load upcoming appointments" [message]="err" (retry)="retryUpcoming()"></app-error-banner>
        </div>
      } @else if (upcomingItems().length === 0) {
        <div class="upcoming-body">
          <app-empty-state
            title="No appointments today"
            description="Today's appointments will appear here.">
          </app-empty-state>
        </div>
      } @else {
        <div class="upcoming-body" [style.maxHeight]="'clamp(340px, calc(100vh - 640px), 640px)'">
          <ejs-listview
            cssClass="dashboard-upcoming-list"
            [dataSource]="upcomingItems()"
            [fields]="{ id: 'appointmentId', text: 'patientName' }">
            <ng-template #template let-data="">
              <div class="upcoming-row">
                <span class="upcoming-rail" [style.background]="data.statusFg"></span>

                <div class="upcoming-avatar" [style.background]="data.statusBg" [style.color]="data.statusFg">
                  {{ data.initials }}
                </div>

                <div class="upcoming-identity">
                  <div class="upcoming-identity-top">
                    <span class="upcoming-patient">{{ data.patientName }}</span>
                    <span class="upcoming-type">{{ data.appointmentType }}</span>
                  </div>
                  <div class="upcoming-provider">{{ data.providerName }}</div>
                </div>

                <div class="upcoming-when">
                  <div class="upcoming-time-row">
                    <span class="upcoming-time">{{ data.time }}</span>
                    <span class="upcoming-day">{{ data.day }}</span>
                  </div>
                  <span
                    class="upcoming-status"
                    [style.background]="data.statusBg"
                    [style.color]="data.statusFg">
                    {{ data.statusLabel }}
                  </span>
                </div>
              </div>
            </ng-template>
          </ejs-listview>
        </div>
      }
    </div>
  </div>
</div>

// React/src/pages/DashboardPage.tsx
import React, { useMemo } from 'react';
import { useAsyncResult } from '@hooks/useAsyncResult';
import { getDashboardKpis, listAppointments, getAppointmentVolume, getProviderUtilization } from '@services/healthcare.service';
import { KpiCard } from '@components/shared/KpiCard';
import { ErrorBanner } from '@components/shared/ErrorBanner';
import { EmptyState } from '@components/shared/EmptyState';
import { LoadingState } from '@components/shared/LoadingState';
import {
  ChartComponent,
  SeriesCollectionDirective,
  SeriesDirective,
  Inject,
  Category,
  Legend,
  Tooltip,
  DataLabel,
  ColumnSeries,
  StackingColumnSeries,
} from '@syncfusion/ej2-react-charts';
import { ListViewComponent } from '@syncfusion/ej2-react-lists';
import { CalendarDays, UserCheck, Clock, TrendingUp, ListChecks } from 'lucide-react';
import type { AppointmentSummaryDto, VolumeDataPointDto, UtilizationDataPointDto } from '@models/dtos';
import {
  APPOINTMENT_TYPE_SERIES,
  BAR_RAMP,
  buildValueAxis,
  chartFillHeight,
  chartLegendSettings,
  chartInteraction,
  chartThemeName,
  COLUMN_STYLE,
  Highlight,
  Selection,
} from '../utils/chartTheme';
import { useTheme } from '../theme/ThemeProvider';

const UPCOMING_STATUSES = ['Scheduled', 'Confirmed', 'CheckedIn', 'InProgress', 'Completed'];

const STATUS_STYLES: Record<string, { fg: string; bg: string; label: string }> = {
  Scheduled: { fg: 'var(--color-sf-cyan-700)', bg: 'var(--color-sf-cyan-50)', label: 'Scheduled' },
  Confirmed: { fg: 'var(--color-sf-success-700)', bg: 'var(--color-sf-success-50)', label: 'Confirmed' },
  CheckedIn: { fg: 'var(--color-sf-brand-700)', bg: 'var(--color-sf-brand-50)', label: 'Checked In' },
  InProgress: { fg: 'var(--color-sf-warning-700)', bg: 'var(--color-sf-warning-50)', label: 'In Progress' },
  Completed: { fg: 'var(--color-sf-fg-secondary)', bg: 'var(--color-sf-bg-tertiary)', label: 'Completed' },
};
const NEUTRAL_STATUS = { fg: 'var(--color-sf-fg-tertiary)', bg: 'var(--color-sf-bg-tertiary)', label: 'Scheduled' };

function toYmd(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

function initialsOf(name: string): string {
  const parts = name.trim().split(/\s+/);
  const first = parts[0]?.[0] ?? '';
  const last = parts.length > 1 ? parts[parts.length - 1][0] : '';
  return (first + last).toUpperCase();
}

interface UpcomingItem {
  appointmentId: string;
  patientName: string;
  appointmentType: string;
  providerName: string;
  initials: string;
  statusLabel: string;
  statusFg: string;
  statusBg: string;
  time: string;
  day: string;
}

function relativeDay(dt: Date): string {
  const today = new Date();
  const startOf = (d: Date) => new Date(d.getFullYear(), d.getMonth(), d.getDate()).getTime();
  const diffDays = Math.round((startOf(dt) - startOf(today)) / 86400000);
  if (diffDays === 0) return 'Today';
  if (diffDays === 1) return 'Tomorrow';
  return dt.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
}

export const DashboardPage: React.FC = () => {
  const { resolved } = useTheme();
  const chartTheme = chartThemeName(resolved);
  const kpis = useAsyncResult(() => getDashboardKpis(), []);
  const todayRange = useMemo(() => {
    const start = new Date();
    start.setHours(0, 0, 0, 0);
    const end = new Date();
    end.setHours(23, 59, 59, 999);
    return { from: start.toISOString(), to: end.toISOString() };
  }, []);
  const upcoming = useAsyncResult(
    () => listAppointments({ dateFrom: todayRange.from, dateTo: todayRange.to, limit: '200' }),
    [todayRange],
  );

  
  const range = useMemo(() => {
    const end = new Date();
    const start = new Date();
    start.setDate(start.getDate() - 30);
    return { startDate: toYmd(start), endDate: toYmd(end) };
  }, []);
  const volume = useAsyncResult(() => getAppointmentVolume(range.startDate, range.endDate), [range]);
  const utilization = useAsyncResult(() => getProviderUtilization(range.startDate, range.endDate), [range]);

  const volumeData = useMemo(() => {
    const rows = volume.data?.data ?? [];
    type VolumeRow = { department: string } & Record<string, number | string>;
    const byDept = new Map<string, VolumeRow>();
    rows.forEach((d: VolumeDataPointDto) => {
      let entry = byDept.get(d.departmentName);
      if (!entry) {
        entry = { department: d.departmentName };
        APPOINTMENT_TYPE_SERIES.forEach((s) => (entry![s.type] = 0));
        byDept.set(d.departmentName, entry);
      }
      if (d.appointmentType in entry) entry[d.appointmentType] = (entry[d.appointmentType] as number) + d.count;
    });
    const total = (e: VolumeRow) => APPOINTMENT_TYPE_SERIES.reduce((sum, s) => sum + (e[s.type] as number), 0);
    return Array.from(byDept.values()).sort((a, b) => total(b) - total(a));
  }, [volume.data]);

  const utilizationData = useMemo(() => {
    const rows = utilization.data?.data ?? [];
    const byProvider = new Map<string, { name: string; appts: number; slots: number }>();
    rows.forEach((d: UtilizationDataPointDto) => {
      const entry = byProvider.get(d.providerName) ?? { name: d.providerName, appts: 0, slots: 0 };
      entry.appts += d.appointmentCount;
      entry.slots += d.totalSlots;
      byProvider.set(d.providerName, entry);
    });
    return Array.from(byProvider.values())
      .map((p) => ({ name: p.name, rate: p.slots > 0 ? Math.round((100 * p.appts) / p.slots) : 0 }))
      .sort((a, b) => b.rate - a.rate)
      .slice(0, 8)
      .map((d, i) => ({ ...d, color: BAR_RAMP[i % BAR_RAMP.length] }));
  }, [utilization.data]);

  const upcomingItems: UpcomingItem[] = useMemo(() => {
    const items = upcoming.data?.data?.items ?? [];
    return items
      .filter((a: AppointmentSummaryDto) => UPCOMING_STATUSES.includes(a.status))
      .sort((a, b) => new Date(a.scheduledDateTime).getTime() - new Date(b.scheduledDateTime).getTime())
      .slice(0, 12)
      .map((a: AppointmentSummaryDto) => {
        const dt = new Date(a.scheduledDateTime);
        const s = STATUS_STYLES[a.status] ?? NEUTRAL_STATUS;
        return {
          appointmentId: a.appointmentId,
          patientName: a.patientName,
          appointmentType: a.appointmentType,
          providerName: a.providerName,
          initials: initialsOf(a.patientName),
          statusLabel: s.label,
          statusFg: s.fg,
          statusBg: s.bg,
          time: dt.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
          day: relativeDay(dt),
        };
      });
  }, [upcoming.data]);

  const upcomingTemplate = (item: UpcomingItem) => (
    <div style={{ display: 'flex', alignItems: 'center', width: '100%', gap: 14 }}>
      <span style={{ width: 4, alignSelf: 'stretch', minHeight: 40, borderRadius: 'var(--radius-full)', background: item.statusFg, flexShrink: 0 }} />
      <div
        style={{
          width: 40,
          height: 40,
          borderRadius: '50%',
          background: item.statusBg,
          color: item.statusFg,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          fontSize: 13,
          fontWeight: 700,
          flexShrink: 0,
          border: '1px solid var(--color-sf-border-secondary)',
        }}
      >
        {item.initials}
      </div>

      <div style={{ minWidth: 0, flex: 1 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, minWidth: 0, flexWrap: 'wrap' }}>
          <span style={{ fontWeight: 600, fontSize: 14, color: 'var(--color-sf-fg-primary)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', lineHeight: 1.3, minWidth: 0, flex: '1 1 auto' }}>{item.patientName}</span>
          <span style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-sf-fg-secondary)', background: 'var(--color-sf-bg-tertiary)', padding: '1px 8px', borderRadius: 'var(--radius-full)', whiteSpace: 'nowrap', flexShrink: 0 }}>{item.appointmentType}</span>
        </div>
        <div style={{ fontSize: 12, color: 'var(--color-sf-fg-tertiary)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', lineHeight: 1.4, marginTop: 2 }}>{item.providerName}</div>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 5, flexShrink: 0 }}>
        <div style={{ display: 'flex', alignItems: 'baseline', gap: 6 }}>
          <span style={{ fontSize: 14, fontWeight: 700, color: 'var(--color-sf-fg-primary)' }}>{item.time}</span>
          <span style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-sf-fg-quinary)' }}>{item.day}</span>
        </div>
        <span
          style={{
            fontSize: 11,
            fontWeight: 600,
            color: item.statusFg,
            background: item.statusBg,
            padding: '2px 10px',
            borderRadius: 'var(--radius-full)',
            lineHeight: 1.5,
          }}
        >
          {item.statusLabel}
        </span>
      </div>
    </div>
  );

  const cardSurface: React.CSSProperties = {
    background: 'var(--color-sf-bg-primary)',
    borderRadius: 'var(--radius-12)',
    border: '1px solid var(--color-sf-border-secondary)',
    boxShadow: 'var(--shadow-sm)',
    padding: 20,
  };
  const sectionTitle: React.CSSProperties = {
    fontWeight: 600,
    fontSize: 14,
    color: 'var(--color-sf-fg-primary)',
    marginBottom: 16,
  };

  const kpiData = kpis.data?.data;

  return (
    <div>
      {(kpis.error || upcoming.error) && (
        <ErrorBanner message={(kpis.error ?? upcoming.error) || 'Failed to load dashboard data'} onRetry={() => { kpis.refresh(); upcoming.refresh(); }} />
      )}

      <div className="responsive-page-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 16 }}>
        <div id="kpis" style={{ gridColumn: 'span 4', display: 'flex', gap: 16, flexWrap: 'wrap' }}>
          <KpiCard title="Today's Appts" value={kpiData?.totalAppointments ?? '—'} loading={kpis.loading} icon={<CalendarDays size={16} />} />
          <KpiCard title="Completed" value={kpiData?.completedAppointments ?? '—'} loading={kpis.loading} icon={<UserCheck size={16} />} />
          <KpiCard title="Avg Wait" value={kpiData ? `${kpiData.averageWaitTimeMinutes}m` : '—'} loading={kpis.loading} icon={<Clock size={16} />} />
          <KpiCard title="No-Show Rate" value={kpiData ? `${(kpiData.noShowRate * 100).toFixed(1)}%` : '—'} loading={kpis.loading} icon={<TrendingUp size={16} />} />
          <KpiCard title="Open Waitlist" value={kpiData?.openWaitlistCount ?? '—'} loading={kpis.loading} icon={<ListChecks size={16} />} />
        </div>

        <div id="volume" style={{ gridColumn: 'span 2', minWidth: 0, ...cardSurface }}>
          <div style={sectionTitle}>Appointment Type Mix by Department</div>
          {volume.loading ? (
            <LoadingState inline label="Loading appointment volume…" />
          ) : volume.error ? (
            <ErrorBanner message={volume.error} onRetry={volume.refresh} />
          ) : volumeData.length === 0 ? (
            <EmptyState title="No appointment volume" description="No appointments in the last 30 days." />
          ) : (
            <div style={{ height: chartFillHeight({ rows: 1, reserve: 560, cap: 620 }) }}>
            <ChartComponent
              theme={chartTheme}
              primaryXAxis={{ valueType: 'Category', title: 'Department' }}
              primaryYAxis={{ title: 'Share', labelFormat: '{value}%', minimum: 0, maximum: 100, interval: 20 }}
              legendSettings={chartLegendSettings}
              height="100%"
              tooltip={{ enable: true }}
              {...chartInteraction}
            >
              <Inject services={[StackingColumnSeries, Legend, Tooltip, DataLabel, Category, Highlight, Selection]} />
              <SeriesCollectionDirective>
                {APPOINTMENT_TYPE_SERIES.map((s, i) => (
                  <SeriesDirective
                    key={s.type}
                    dataSource={volumeData}
                    xName="department"
                    yName={s.type}
                    name={s.type}
                    type="StackingColumn100"
                    fill={s.color}
                    columnWidth={COLUMN_STYLE.columnWidth}
                    cornerRadius={i === APPOINTMENT_TYPE_SERIES.length - 1 ? COLUMN_STYLE.cornerRadius : undefined}
                  />
                ))}
              </SeriesCollectionDirective>
            </ChartComponent>
            </div>
          )}
        </div>

        <div id="utilization" style={{ gridColumn: 'span 2', minWidth: 0, ...cardSurface }}>
          <div style={sectionTitle}>Provider Utilization</div>
          {utilization.loading ? (
            <LoadingState inline label="Loading provider utilization…" />
          ) : utilization.error ? (
            <ErrorBanner message={utilization.error} onRetry={utilization.refresh} />
          ) : utilizationData.length === 0 ? (
            <EmptyState title="No utilization data" description="No appointments in the last 30 days." />
          ) : (
            <div style={{ height: chartFillHeight({ rows: 1, reserve: 560, cap: 620 }) }}>
            <ChartComponent
              theme={chartTheme}
              primaryXAxis={{ valueType: 'Category', title: 'Provider' }}
              primaryYAxis={buildValueAxis(utilizationData.map((d) => d.rate), { title: 'Utilization %', labelFormat: '{value}%' })}
              legendSettings={{ visible: false }}
              height="100%"
              tooltip={{ enable: true }}
              {...chartInteraction}
            >
              <Inject services={[ColumnSeries, Legend, Tooltip, DataLabel, Category, Highlight, Selection]} />
              <SeriesCollectionDirective>
                <SeriesDirective dataSource={utilizationData} xName="name" yName="rate" name="Utilization %" type="Column" pointColorMapping="color" {...COLUMN_STYLE} />
              </SeriesCollectionDirective>
            </ChartComponent>
            </div>
          )}
        </div>

        <div id="upcoming" style={{ gridColumn: 'span 4', minWidth: 0, ...cardSurface, padding: 0, overflow: 'hidden' }}>
          <div style={{ ...sectionTitle, marginBottom: 0, padding: '16px 20px', borderBottom: upcomingItems.length ? '1px solid var(--color-sf-border-secondary)' : 'none' }}>Today's Appointments</div>
          {upcoming.loading ? (
            <LoadingState inline label="Loading upcoming appointments…" />
          ) : upcoming.error ? (
            <div style={{ padding: 20 }}>
              <ErrorBanner message={upcoming.error} onRetry={upcoming.refresh} />
            </div>
          ) : !upcomingItems.length ? (
            <div style={{ padding: 20 }}>
              <EmptyState title="No appointments today" description="Today's appointments will appear here." />
            </div>
          ) : (
            <div style={{ maxHeight: 'clamp(340px, calc(100vh - 640px), 640px)', overflow: 'auto' }}>
              <ListViewComponent
                dataSource={upcomingItems as unknown as { [key: string]: Object }[]}
                fields={{ id: 'appointmentId', text: 'patientName' }}
                template={upcomingTemplate as unknown as string}
                cssClass="dashboard-upcoming-list"
              />
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
