// Angular/src/app/pages/providers/provider-list-page.component.ts
import {
  Component,
  inject,
  computed,
  ChangeDetectionStrategy,
  ViewChild,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { map } from 'rxjs';
import {
  GridModule,
  PageService,
  SortService,
  FilterService,
  ToolbarService,
  DetailRowService,
  GridComponent,
} from '@syncfusion/ej2-angular-grids';
import { ButtonModule } from '@syncfusion/ej2-angular-buttons';
import { HealthcareService } from '../../core/api/healthcare.service';
import { okOrThrow } from '../../core/api/api.service';
import { createAsyncResult } from '../../core/async/async-result';
import { ErrorBannerComponent } from '../../shared/error-banner/error-banner.component';
import { EmptyStateComponent } from '../../shared/empty-state/empty-state.component';
import { LoadingStateComponent } from '../../shared/loading-state/loading-state.component';
import { StatusBadgeComponent } from '../../shared/status-badge/status-badge.component';
import { ProviderScheduleDetailComponent } from './provider-schedule-detail.component';
import type { ProviderSummaryDto } from '../../core/models/dtos';

const CHIP_COLORS: Record<string, { bg: string; fg: string }> = {
  cardiology: { bg: 'var(--color-sf-chip-cardiology-bg)', fg: 'var(--color-sf-chip-cardiology-fg)' },
  neurology: { bg: 'var(--color-sf-chip-neurology-bg)', fg: 'var(--color-sf-chip-neurology-fg)' },
  orthopedics: { bg: 'var(--color-sf-chip-orthopedics-bg)', fg: 'var(--color-sf-chip-orthopedics-fg)' },
  pediatrics: { bg: 'var(--color-sf-chip-pediatrics-bg)', fg: 'var(--color-sf-chip-pediatrics-fg)' },
  dermatology: { bg: 'var(--color-sf-chip-dermatology-bg)', fg: 'var(--color-sf-chip-dermatology-fg)' },
  ophthalmology: { bg: 'var(--color-sf-chip-ophthalmology-bg)', fg: 'var(--color-sf-chip-ophthalmology-fg)' },
  'internal medicine': { bg: 'var(--color-sf-chip-internal-medicine-bg)', fg: 'var(--color-sf-chip-internal-medicine-fg)' },
  'family medicine': { bg: 'var(--color-sf-chip-family-medicine-bg)', fg: 'var(--color-sf-chip-family-medicine-fg)' },
  'obstetrics & gynecology': { bg: 'var(--color-sf-chip-obstetrics-gynecology-bg)', fg: 'var(--color-sf-chip-obstetrics-gynecology-fg)' },
  obstetrics: { bg: 'var(--color-sf-chip-obstetrics-bg)', fg: 'var(--color-sf-chip-obstetrics-fg)' },
  gynecology: { bg: 'var(--color-sf-chip-gynecology-bg)', fg: 'var(--color-sf-chip-gynecology-fg)' },
  endocrinology: { bg: 'var(--color-sf-chip-endocrinology-bg)', fg: 'var(--color-sf-chip-endocrinology-fg)' },
  oncology: { bg: 'var(--color-sf-chip-oncology-bg)', fg: 'var(--color-sf-chip-oncology-fg)' },
  psychiatry: { bg: 'var(--color-sf-chip-psychiatry-bg)', fg: 'var(--color-sf-chip-psychiatry-fg)' },
  gastroenterology: { bg: 'var(--color-sf-chip-gastroenterology-bg)', fg: 'var(--color-sf-chip-gastroenterology-fg)' },
  urology: { bg: 'var(--color-sf-chip-urology-bg)', fg: 'var(--color-sf-chip-urology-fg)' },
  radiology: { bg: 'var(--color-sf-chip-radiology-bg)', fg: 'var(--color-sf-chip-radiology-fg)' },
  pulmonology: { bg: 'var(--color-sf-chip-pulmonology-bg)', fg: 'var(--color-sf-chip-pulmonology-fg)' },
  nephrology: { bg: 'var(--color-sf-chip-nephrology-bg)', fg: 'var(--color-sf-chip-nephrology-fg)' },
  rheumatology: { bg: 'var(--color-sf-chip-rheumatology-bg)', fg: 'var(--color-sf-chip-rheumatology-fg)' },
};

const NEUTRAL_CHIP = { bg: 'var(--color-sf-chip-neutral-bg)', fg: 'var(--color-sf-chip-neutral-fg)' };

function chipColor(value: string): { bg: string; fg: string } {
  const key = value.trim().toLowerCase();
  const match = Object.keys(CHIP_COLORS).find((k) => key.includes(k));
  return match ? CHIP_COLORS[match] : NEUTRAL_CHIP;
}

function initialsOf(first: string, last: string): string {
  return ((first?.[0] ?? '') + (last?.[0] ?? '')).toUpperCase();
}

@Component({
  selector: 'app-provider-list-page',
  standalone: true,
  imports: [
    CommonModule,
    GridModule,
    ButtonModule,
    ErrorBannerComponent,
    EmptyStateComponent,
    LoadingStateComponent,
    StatusBadgeComponent,
    ProviderScheduleDetailComponent,
  ],
  providers: [PageService, SortService, FilterService, ToolbarService, DetailRowService],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './provider-list-page.component.html',
  styleUrl: './provider-list-page.component.scss',
})
export class ProviderListPageComponent {
  private healthcare = inject(HealthcareService);
  private router = inject(Router);

  @ViewChild('grid') grid?: GridComponent;

  private readonly providersState = createAsyncResult<{ items: ProviderSummaryDto[] }>(() =>
    this.healthcare.listProviders().pipe(map((res) => okOrThrow(res)))
  );

  readonly items = computed(() => this.providersState.data?.items ?? []);
  readonly loading = computed(() => this.providersState.loading);
  readonly error = computed(() => this.providersState.error);

  readonly pageSettings = { pageSize: 50 };
  readonly toolbar = ['Search'];
  readonly filterSettings = { type: 'Excel' as const };

  retry(): void {
    this.providersState.refresh();
  }

  viewProvider(providerId: string): void {
    this.router.navigate(['/providers', providerId]);
  }

  chipStyle(value: string): { background: string; color: string } {
    const { bg, fg } = chipColor(value);
    return { background: bg, color: fg };
  }

  providerName(props: ProviderSummaryDto): string {
    return `Dr. ${props.firstName} ${props.lastName}${props.title ? `, ${props.title}` : ''}`;
  }

  initials(props: ProviderSummaryDto): string {
    return initialsOf(props.firstName, props.lastName);
  }

  avgDuration(props: ProviderSummaryDto): number {
    return Number(props?.averageAppointmentDuration ?? 0);
  }
}

<div class="provider-list">
  @if (error(); as err) {
    <app-error-banner title="Unable to load providers" [message]="err" (retry)="retry()"></app-error-banner>
  }

  @if (loading() && items().length === 0) {
    <app-loading-state label="Loading providers…"></app-loading-state>
  } @else if (items().length === 0) {
    <app-empty-state
      title="No providers found"
      description="Provider data will appear once the backend is seeded.">
    </app-empty-state>
  } @else {
    <ejs-grid
      #grid
      [dataSource]="items()"
      [allowPaging]="true"
      [allowSorting]="true"
      [allowFiltering]="true"
      [filterSettings]="filterSettings"
      [pageSettings]="pageSettings"
      [toolbar]="toolbar">
      <e-columns>
        <e-column headerText="Provider" width="260" field="lastName">
          <ng-template #template let-data>
            <div class="provider-cell">
              <span class="provider-avatar">{{ initials(data) }}</span>
              <span class="provider-name">{{ providerName(data) }}</span>
            </div>
          </ng-template>
        </e-column>
        <e-column field="specialty" headerText="Specialty" width="160">
          <ng-template #template let-data>
            <span class="specialty-chip" [ngStyle]="chipStyle(data.specialty)">{{ data.specialty }}</span>
          </ng-template>
        </e-column>
        <e-column field="averageAppointmentDuration" headerText="Avg Duration" width="130">
          <ng-template #template let-data>
            @if (avgDuration(data) === 0) {
              <span class="cell-muted">—</span>
            } @else {
              <span class="avg-duration">{{ avgDuration(data) }} min</span>
            }
          </ng-template>
        </e-column>
        <e-column field="locationName" headerText="Location" width="160" hideAtMedia="(max-width: 1023px)"></e-column>
        <e-column field="npiNumber" headerText="NPI" width="120" hideAtMedia="(max-width: 1023px)"></e-column>
        <e-column field="phoneNumber" headerText="Phone" width="140"></e-column>
        <e-column field="isActive" headerText="Status" width="100" hideAtMedia="(max-width: 640px)">
          <ng-template #template let-data>
            <app-status-badge [status]="data.isActive ? 'Active' : 'Inactive'"></app-status-badge>
          </ng-template>
        </e-column>
        <e-column headerText="Actions" width="110" [allowFiltering]="false" [allowSorting]="false">
          <ng-template #template let-data>
            <button
              ejs-button
              cssClass="e-flat e-primary e-small"
              class="view-btn"
              (click)="viewProvider(data.providerId)">
              View
            </button>
          </ng-template>
        </e-column>
      </e-columns>
      <ng-template #detailTemplate let-data>
        <app-provider-schedule-detail [data]="data"></app-provider-schedule-detail>
      </ng-template>
    </ejs-grid>
  }
</div>

// React/src/pages/ProviderListPage.tsx
import React from 'react';
import {
  GridComponent,
  ColumnsDirective,
  ColumnDirective,
  Inject,
  Page,
  Sort,
  Filter,
  Toolbar,
  DetailRow,
} from '@syncfusion/ej2-react-grids';
import { ButtonComponent } from '@syncfusion/ej2-react-buttons';
import { useAsyncResult } from '@hooks/useAsyncResult';
import { listProviders } from '@services/healthcare.service';
import { ErrorBanner } from '@components/shared/ErrorBanner';
import { EmptyState } from '@components/shared/EmptyState';
import { StatusBadge } from '@components/shared/StatusBadge';
import { InitialsAvatar } from '@components/shared/InitialsAvatar';
import { LoadingState } from '@components/shared/LoadingState';
import { ProviderScheduleDetail } from '@components/providers/ProviderScheduleDetail';
import { useNavigate } from 'react-router-dom';

const CHIP_COLORS: Record<string, { bg: string; fg: string }> = {
  cardiology: { bg: 'var(--color-sf-chip-cardiology-bg)', fg: 'var(--color-sf-chip-cardiology-fg)' },
  neurology: { bg: 'var(--color-sf-chip-neurology-bg)', fg: 'var(--color-sf-chip-neurology-fg)' },
  orthopedics: { bg: 'var(--color-sf-chip-orthopedics-bg)', fg: 'var(--color-sf-chip-orthopedics-fg)' },
  pediatrics: { bg: 'var(--color-sf-chip-pediatrics-bg)', fg: 'var(--color-sf-chip-pediatrics-fg)' },
  dermatology: { bg: 'var(--color-sf-chip-dermatology-bg)', fg: 'var(--color-sf-chip-dermatology-fg)' },
  ophthalmology: { bg: 'var(--color-sf-chip-ophthalmology-bg)', fg: 'var(--color-sf-chip-ophthalmology-fg)' },
  'internal medicine': { bg: 'var(--color-sf-chip-internal-medicine-bg)', fg: 'var(--color-sf-chip-internal-medicine-fg)' },
  'family medicine': { bg: 'var(--color-sf-chip-family-medicine-bg)', fg: 'var(--color-sf-chip-family-medicine-fg)' },
  'obstetrics & gynecology': { bg: 'var(--color-sf-chip-obstetrics-gynecology-bg)', fg: 'var(--color-sf-chip-obstetrics-gynecology-fg)' },
  'obstetrics': { bg: 'var(--color-sf-chip-obstetrics-bg)', fg: 'var(--color-sf-chip-obstetrics-fg)' },
  gynecology: { bg: 'var(--color-sf-chip-gynecology-bg)', fg: 'var(--color-sf-chip-gynecology-fg)' },
  endocrinology: { bg: 'var(--color-sf-chip-endocrinology-bg)', fg: 'var(--color-sf-chip-endocrinology-fg)' },
  oncology: { bg: 'var(--color-sf-chip-oncology-bg)', fg: 'var(--color-sf-chip-oncology-fg)' },
  psychiatry: { bg: 'var(--color-sf-chip-psychiatry-bg)', fg: 'var(--color-sf-chip-psychiatry-fg)' },
  gastroenterology: { bg: 'var(--color-sf-chip-gastroenterology-bg)', fg: 'var(--color-sf-chip-gastroenterology-fg)' },
  urology: { bg: 'var(--color-sf-chip-urology-bg)', fg: 'var(--color-sf-chip-urology-fg)' },
  radiology: { bg: 'var(--color-sf-chip-radiology-bg)', fg: 'var(--color-sf-chip-radiology-fg)' },
  pulmonology: { bg: 'var(--color-sf-chip-pulmonology-bg)', fg: 'var(--color-sf-chip-pulmonology-fg)' },
  nephrology: { bg: 'var(--color-sf-chip-nephrology-bg)', fg: 'var(--color-sf-chip-nephrology-fg)' },
  rheumatology: { bg: 'var(--color-sf-chip-rheumatology-bg)', fg: 'var(--color-sf-chip-rheumatology-fg)' },
};

const NEUTRAL_CHIP = { bg: 'var(--color-sf-chip-neutral-bg)', fg: 'var(--color-sf-chip-neutral-fg)' };

function chipColor(value: string): { bg: string; fg: string } {
  const key = value.trim().toLowerCase();
  const match = Object.keys(CHIP_COLORS).find((k) => key.includes(k));
  return match ? CHIP_COLORS[match] : NEUTRAL_CHIP;
}

const Chip: React.FC<{ value?: string }> = ({ value }) => {
  if (!value) return <span style={{ color: 'var(--color-sf-fg-quinary)' }}>—</span>;
  const { bg, fg } = chipColor(value);
  return (
    <span
      style={{
        display: 'inline-block',
        padding: '2px 10px',
        borderRadius: 999,
        fontSize: 12,
        fontWeight: 600,
        background: bg,
        color: fg,
      }}
    >
      {value}
    </span>
  );
};

export const ProviderListPage: React.FC = () => {
  const navigate = useNavigate();
  const query = useAsyncResult(() => listProviders(), []);
  const items = query.data?.data?.items ?? [];

  return (
    <div>
      {query.error && <ErrorBanner message={query.error} onRetry={query.refresh} />}
      {query.loading && !query.data ? (
        <LoadingState label="Loading providers…" />
      ) : items.length === 0 ? (
        <EmptyState title="No providers found" description="Provider data will appear once the backend is seeded." />
      ) : (
        <GridComponent
          dataSource={items}
          allowPaging
          allowSorting
          allowFiltering
          filterSettings={{ type: 'Excel' }}
          pageSettings={{ pageSize: 50 }}
          toolbar={['Search']}
          detailTemplate={(props: any) => <ProviderScheduleDetail providerId={props.providerId} />}
        >
          <ColumnsDirective>
            <ColumnDirective
              headerText="Provider"
              width="260"
              field="lastName"
              template={(props: any) => (
                <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                  <InitialsAvatar first={props.firstName} last={props.lastName} size={40} />
                  <div style={{ minWidth: 0 }}>
                    <div style={{ fontWeight: 600, fontSize: 13, color: 'var(--color-sf-fg-primary)' }}>
                      Dr. {props.firstName} {props.lastName}{props.title ? `, ${props.title}` : ''}
                    </div>
                  </div>
                </div>
              )}
            />
            <ColumnDirective field="specialty" headerText="Specialty" width="160" template={(props: any) => <Chip value={props.specialty} />} />
            <ColumnDirective
              field="averageAppointmentDuration"
              headerText="Avg Duration"
              width="130"
              template={(props: any) => {
                const v = Number(props?.averageAppointmentDuration ?? 0);
                if (!v) return <span style={{ color: 'var(--color-sf-fg-quinary)' }}>—</span>;
                return <span style={{ fontSize: 13 }}>{v} min</span>;
              }}
            />
            <ColumnDirective
              field="locationName"
              headerText="Location"
              width="160"
              hideAtMedia="(max-width: 1023px)"
            />
            <ColumnDirective
              field="npiNumber"
              headerText="NPI"
              width="120"
              hideAtMedia="(max-width: 1023px)"
            />
            <ColumnDirective
              field="phoneNumber"
              headerText="Phone"
              width="140"
            />
            <ColumnDirective
              field="isActive"
              headerText="Status"
              width="100"
              hideAtMedia="(max-width: 640px)"
              template={(props: any) => <StatusBadge status={props.isActive ? 'Active' : 'Inactive'} />}
            />
            <ColumnDirective
              headerText="Actions"
              width="110"
              allowFiltering={false}
              allowSorting={false}
              template={(props: any) => (
                <ButtonComponent cssClass="e-flat e-primary e-small" onClick={() => navigate(`/providers/${props.providerId}`)}>
                  View
                </ButtonComponent>
              )}
            />
          </ColumnsDirective>
          <Inject services={[Page, Sort, Filter, Toolbar, DetailRow]} />
        </GridComponent>
      )}
    </div>
  );
};
