// Angular/src/app/pages/providers/provider-detail-page.component.ts
import {
  Component,
  inject,
  computed,
  signal,
  effect,
  ChangeDetectionStrategy,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import { map, of } from 'rxjs';
import { TabModule } from '@syncfusion/ej2-angular-navigations';
import { HealthcareService } from '../../core/api/healthcare.service';
import { okOrThrow } from '../../core/api/api.service';
import { createAsyncResult } from '../../core/async/async-result';
import { ErrorBannerComponent } from '../../shared/error-banner/error-banner.component';
import { EmptyStateComponent } from '../../shared/empty-state/empty-state.component';
import { LoadingStateComponent } from '../../shared/loading-state/loading-state.component';
import { KpiCardComponent } from '../../shared/kpi-card/kpi-card.component';
import { ProviderScheduleTabComponent } from './provider-schedule-tab.component';
import { ProviderAnalyticsTabComponent } from './provider-analytics-tab.component';
import {
  LucideCalendarDays,
  LucideUsers,
  LucideActivity,
  LucideXCircle,
  LucideUserX,
} from '@lucide/angular';
import type {
  ProviderDetailDto,
  UtilizationDataPointDto,
  NoShowTrendDto,
  AppointmentSummaryDto,
} from '../../core/models/dtos';

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

function monthLabel(period: string): string {
  const m = Number(period.split('-')[1]);
  return MONTHS[m - 1] ?? period;
}

function toYmd(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

function startOfWeek(d: Date): Date {
  const date = new Date(d);
  date.setHours(0, 0, 0, 0);
  date.setDate(date.getDate() - date.getDay());
  return date;
}



interface TrendPoint {
  month: string;
  rate: number;
}

type TabKey = 'schedule' | 'analytics';
const TAB_KEYS: TabKey[] = ['schedule', 'analytics'];

@Component({
  selector: 'app-provider-detail-page',
  standalone: true,
  imports: [
    CommonModule,
    TabModule,
    ErrorBannerComponent,
    EmptyStateComponent,
    LoadingStateComponent,
    KpiCardComponent,
    ProviderScheduleTabComponent,
    ProviderAnalyticsTabComponent,
    LucideCalendarDays,
    LucideUsers,
    LucideActivity,
    LucideXCircle,
    LucideUserX,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './provider-detail-page.component.html',
  styleUrl: './provider-detail-page.component.scss',
})
export class ProviderDetailPageComponent {
  private route = inject(ActivatedRoute);
  private healthcare = inject(HealthcareService);

  readonly id = computed(() => this.route.snapshot.paramMap.get('id') ?? '');
  readonly activeTab = signal<TabKey>('schedule');

  readonly today = new Date();

  readonly range = computed<{ start: string; end: string }>(() => {
    const end = new Date();
    const start = new Date();
    start.setMonth(start.getMonth() - 6);
    return { start: toYmd(start), end: toYmd(end) };
  });

  readonly apptWindow = computed<{ from: string; to: string }>(() => {
    const from = new Date();
    from.setDate(from.getDate() - 30);
    const to = new Date();
    to.setDate(to.getDate() + 14);
    return { from: toYmd(from), to: toYmd(to) };
  });

  private readonly providerState = createAsyncResult<ProviderDetailDto>(() =>
    this.healthcare.getProvider(this.id()).pipe(map((res) => okOrThrow(res)))
  );

  readonly apptsState = createAsyncResult<{ items: AppointmentSummaryDto[] }>(() =>
    this.healthcare
      .listAppointments({
        providerId: this.id(),
        dateFrom: this.apptWindow().from,
        dateTo: this.apptWindow().to,
        limit: '500',
      })
      .pipe(map((res) => okOrThrow(res)))
  );

  readonly utilizationState = createAsyncResult<UtilizationDataPointDto[]>(() =>
    this.healthcare
      .getProviderUtilization(this.range().start, this.range().end, this.id())
      .pipe(map((res) => okOrThrow(res)))
  );

  readonly noShowState = createAsyncResult<NoShowTrendDto[]>(() => {
    const provider = this.providerState.data;
    if (!provider) {
      return of([]);
    }
    return this.healthcare
      .getNoShowTrends(this.range().start, this.range().end, provider.departmentId)
      .pipe(map((res) => okOrThrow(res)));
  });

  readonly provider = computed(() => this.providerState.data);
  readonly appointments = computed<AppointmentSummaryDto[]>(() => this.apptsState.data?.items ?? []);

  readonly utilizationData = computed<TrendPoint[]>(() => {
    const rows = this.utilizationState.data ?? [];
    const byMonth = new Map<string, { key: string; appts: number; slots: number }>();
    rows.forEach((r) => {
      const key = r.date.slice(0, 7);
      const e = byMonth.get(key) ?? { key, appts: 0, slots: 0 };
      e.appts += r.appointmentCount;
      e.slots += r.totalSlots;
      byMonth.set(key, e);
    });
    return Array.from(byMonth.values())
      .sort((a, b) => a.key.localeCompare(b.key))
      .map((e) => ({ month: monthLabel(e.key), rate: e.slots > 0 ? Math.round((100 * e.appts) / e.slots) : 0 }));
  });

  readonly overallUtilization = computed<number | null>(() => {
    const rows = this.utilizationState.data ?? [];
    const appts = rows.reduce((s, r) => s + r.appointmentCount, 0);
    const slots = rows.reduce((s, r) => s + r.totalSlots, 0);
    return slots > 0 ? Math.round((100 * appts) / slots) : null;
  });

  readonly noShowData = computed<TrendPoint[]>(() => {
    const rows = this.noShowState.data ?? [];
    return [...rows]
      .sort((a, b) => a.period.localeCompare(b.period))
      .map((r) => ({ month: monthLabel(r.period), rate: Math.round(r.noShowRate * 1000) / 10 }));
  });

  readonly kpis = computed(() => {
    const startWeek = startOfWeek(this.today).getTime();
    const endWeek = startWeek + 7 * 86400000;
    const todayYmd = toYmd(this.today);
    let apptsToday = 0;
    let cancelled = 0;
    let noShow = 0;
    const weekPatients = new Set<string>();
    this.appointments().forEach((a) => {
      const t = new Date(a.scheduledDateTime).getTime();
      if (toYmd(new Date(a.scheduledDateTime)) === todayYmd) apptsToday += 1;
      if (t >= startWeek && t < endWeek) weekPatients.add(a.patientId);
      if (a.status === 'Cancelled') cancelled += 1;
      if (a.status === 'NoShow') noShow += 1;
    });
    const total = this.appointments().length;
    return {
      apptsToday,
      patientsThisWeek: weekPatients.size,
      cancellationRate: total > 0 ? (100 * cancelled) / total : null,
      noShowRate: total > 0 ? (100 * noShow) / total : null,
    };
  });

  readonly overallUtilizationLabel = computed(() =>
    this.overallUtilization() === null ? '—' : `${this.overallUtilization()}%`
  );
  readonly cancellationRateLabel = computed(() => this.pct(this.kpis().cancellationRate));
  readonly noShowRateLabel = computed(() => this.pct(this.kpis().noShowRate));

  readonly loadingProvider = computed(() => this.providerState.loading);
  readonly providerError = computed(() => this.providerState.error);

  constructor() {
    effect(() => {
      if (this.providerState.data) this.noShowState.refresh();
    });
  }

  readonly selectedTabIndex = computed(() => TAB_KEYS.indexOf(this.activeTab()));
  readonly tabHeaders = [
    { text: 'Schedule' },
    { text: 'Analytics' },
  ];

  private pct(v: number | null): string {
    return v === null ? '—' : `${v.toFixed(1)}%`;
  }

  onTabSelecting(args: { selectingIndex: number }): void {
    const key = TAB_KEYS[args.selectingIndex];
    if (key) this.activeTab.set(key);
  }

  retryProvider(): void {
    this.providerState.refresh();
  }

  retryAppointments = (): void => {
    this.apptsState.refresh();
  };

  retryUtilization = (): void => {
    this.utilizationState.refresh();
  };

  retryNoShow = (): void => {
    this.noShowState.refresh();
  };
}

@if (providerError(); as err) {
  <app-error-banner title="Unable to load provider" [message]="err" (retry)="retryProvider()"></app-error-banner>
}

@if (loadingProvider() && !provider()) {
  <app-loading-state label="Loading provider…"></app-loading-state>
} @else if (!provider()) {
  <app-empty-state
    title="Provider not found"
    description="The requested provider does not exist.">
  </app-empty-state>
} @else {
  <div class="provider-detail">
    <div class="profile-header">
      <span class="profile-avatar">
        {{ (provider()?.firstName?.[0] ?? '') + (provider()?.lastName?.[0] ?? '') }}
      </span>
      <div class="profile-meta">
        <div class="profile-name">
          Dr. {{ provider()?.firstName }} {{ provider()?.lastName }}, {{ provider()?.title }}
        </div>
        <div class="profile-subtitle">
          {{ provider()?.specialty }} • {{ provider()?.locationName }}
        </div>
        <div class="profile-extra">
          NPI: {{ provider()?.npiNumber }} • {{ provider()?.phoneNumber }}
        </div>
      </div>
    </div>

    <div class="kpi-row">
      <app-kpi-card title="Appointments Today" [value]="kpis().apptsToday" [loading]="apptsState.loading">
        <ng-template #icon><svg lucideCalendarDays [size]="16" [strokeWidth]="2"></svg></ng-template>
      </app-kpi-card>
      <app-kpi-card title="Patients This Week" [value]="kpis().patientsThisWeek" [loading]="apptsState.loading">
        <ng-template #icon><svg lucideUsers [size]="16" [strokeWidth]="2"></svg></ng-template>
      </app-kpi-card>
      <app-kpi-card title="Utilization" [value]="overallUtilizationLabel()" [loading]="utilizationState.loading">
        <ng-template #icon><svg lucideActivity [size]="16" [strokeWidth]="2"></svg></ng-template>
      </app-kpi-card>
      <app-kpi-card title="Cancellation Rate" [value]="cancellationRateLabel()" [loading]="apptsState.loading">
        <ng-template #icon><svg lucideXCircle [size]="16" [strokeWidth]="2"></svg></ng-template>
      </app-kpi-card>
      <app-kpi-card title="No-Show Rate" [value]="noShowRateLabel()" [loading]="apptsState.loading">
        <ng-template #icon><svg lucideUserX [size]="16" [strokeWidth]="2"></svg></ng-template>
      </app-kpi-card>
    </div>

    <ejs-tab heightAdjustMode="Auto" [selectedItem]="selectedTabIndex()" (selecting)="onTabSelecting($event)">
      <e-tabitems>
        @for (header of tabHeaders; track header.text) {
          <e-tabitem [header]="header"></e-tabitem>
        }
      </e-tabitems>
    </ejs-tab>

    <div class="tab-content">
      @switch (activeTab()) {
        @case ('schedule') {
          <app-provider-schedule-tab
            [appointments]="appointments()"
            [loading]="apptsState.loading && !apptsState.data"
            [error]="apptsState.error"
            [onRetry]="retryAppointments"
            [selectedDate]="today">
          </app-provider-schedule-tab>
        }
        @case ('analytics') {
          <app-provider-analytics-tab
            [utilizationData]="utilizationData()"
            [utilizationLoading]="utilizationState.loading && !utilizationState.data"
            [utilizationError]="utilizationState.error"
            [onUtilizationRetry]="retryUtilization"
            [noShowData]="noShowData()"
            [noShowLoading]="noShowState.loading && !noShowState.data"
            [noShowError]="noShowState.error"
            [onNoShowRetry]="retryNoShow"
            [departmentName]="provider()?.departmentName ?? ''">
          </app-provider-analytics-tab>
        }
      }
    </div>
  </div>
}

// React/src/pages/ProviderDetailPage.tsx
import React, { useMemo, useState } from 'react';
import { useParams } from 'react-router-dom';
import { TabComponent, TabItemDirective, TabItemsDirective } from '@syncfusion/ej2-react-navigations';
import { CalendarDays, Users, Activity, XCircle, UserX } from 'lucide-react';
import { useAsyncResult } from '@hooks/useAsyncResult';
import { getProvider, getProviderUtilization, getNoShowTrends, listAppointments } from '@services/healthcare.service';
import { ErrorBanner } from '@components/shared/ErrorBanner';
import { EmptyState } from '@components/shared/EmptyState';
import { LoadingState } from '@components/shared/LoadingState';
import { InitialsAvatar } from '@components/shared/InitialsAvatar';
import { KpiCard } from '@components/shared/KpiCard';
import { ProviderScheduleTab } from '@components/providers/ProviderScheduleTab';
import { ProviderAnalyticsTab } from '@components/providers/ProviderAnalyticsTab';

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

function monthLabel(period: string): string {
  const m = Number(period.split('-')[1]);
  return MONTHS[m - 1] ?? period;
}

function toYmd(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

function startOfWeek(d: Date): Date {
  const date = new Date(d);
  date.setHours(0, 0, 0, 0);
  date.setDate(date.getDate() - date.getDay());
  return date;
}

const TAB_KEYS = ['schedule', 'analytics'] as const;
type TabKey = (typeof TAB_KEYS)[number];

export const ProviderDetailPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const [activeTab, setActiveTab] = useState<TabKey>('schedule');

  const providerQuery = useAsyncResult(() => getProvider(id!), [id]);

  const provider = providerQuery.data?.data;

  const today = useMemo(() => new Date(), []);

  const range = useMemo(() => {
    const end = new Date();
    const start = new Date();
    start.setMonth(start.getMonth() - 6);
    return { start: toYmd(start), end: toYmd(end) };
  }, []);

  const apptWindow = useMemo(() => {
    const from = new Date();
    from.setDate(from.getDate() - 30);
    const to = new Date();
    to.setDate(to.getDate() + 14);
    return { from: toYmd(from), to: toYmd(to) };
  }, []);
  const apptsQuery = useAsyncResult(
    () => listAppointments({ providerId: id!, dateFrom: apptWindow.from, dateTo: apptWindow.to, limit: '500' }),
    [id, apptWindow]
  );
  const appointments = useMemo(() => apptsQuery.data?.data?.items ?? [], [apptsQuery.data]);

  const utilizationQuery = useAsyncResult(() => getProviderUtilization(range.start, range.end, id), [id, range]);
  const utilizationData = useMemo(() => {
    const rows = utilizationQuery.data?.data ?? [];
    const byMonth = new Map<string, { key: string; appts: number; slots: number }>();
    rows.forEach((r) => {
      const key = r.date.slice(0, 7); 
      const e = byMonth.get(key) ?? { key, appts: 0, slots: 0 };
      e.appts += r.appointmentCount;
      e.slots += r.totalSlots;
      byMonth.set(key, e);
    });
    return Array.from(byMonth.values())
      .sort((a, b) => a.key.localeCompare(b.key))
      .map((e) => ({ month: monthLabel(e.key), rate: e.slots > 0 ? Math.round((100 * e.appts) / e.slots) : 0 }));
  }, [utilizationQuery.data]);
  const overallUtilization = useMemo(() => {
    const rows = utilizationQuery.data?.data ?? [];
    const appts = rows.reduce((s, r) => s + r.appointmentCount, 0);
    const slots = rows.reduce((s, r) => s + r.totalSlots, 0);
    return slots > 0 ? Math.round((100 * appts) / slots) : null;
  }, [utilizationQuery.data]);

  const noShowQuery = useAsyncResult(
    () => (provider ? getNoShowTrends(range.start, range.end, provider.departmentId) : Promise.resolve({ status: 'ok' as const, data: [] })),
    [provider?.departmentId, range]
  );
  const noShowData = useMemo(() => {
    const rows = noShowQuery.data?.data ?? [];
    return [...rows]
      .sort((a, b) => a.period.localeCompare(b.period))
      .map((r) => ({ month: monthLabel(r.period), rate: Math.round(r.noShowRate * 1000) / 10 }));
  }, [noShowQuery.data]);

  const kpis = useMemo(() => {
    const startWeek = startOfWeek(today).getTime();
    const endWeek = startWeek + 7 * 86400000;
    const todayYmd = toYmd(today);
    let apptsToday = 0;
    let cancelled = 0;
    let noShow = 0;
    const weekPatients = new Set<string>();
    appointments.forEach((a) => {
      const t = new Date(a.scheduledDateTime).getTime();
      if (toYmd(new Date(a.scheduledDateTime)) === todayYmd) apptsToday += 1;
      if (t >= startWeek && t < endWeek) weekPatients.add(a.patientId);
      if (a.status === 'Cancelled') cancelled += 1;
      if (a.status === 'NoShow') noShow += 1;
    });
    const total = appointments.length;
    return {
      apptsToday,
      patientsThisWeek: weekPatients.size,
      cancellationRate: total > 0 ? (100 * cancelled) / total : null,
      noShowRate: total > 0 ? (100 * noShow) / total : null,
    };
  }, [appointments, today]);

  if (providerQuery.error) {
    return <ErrorBanner message={providerQuery.error} onRetry={providerQuery.refresh} />;
  }

  if (!provider && providerQuery.loading) {
    return <LoadingState label="Loading provider…" />;
  }

  if (!provider) {
    return <EmptyState title="Provider not found" description="The requested provider does not exist." />;
  }

  const pct = (v: number | null) => (v === null ? '—' : `${v.toFixed(1)}%`);

  const onTabSelecting = (e: { selectingIndex: number }) => {
    if (e.selectingIndex >= 0 && e.selectingIndex < TAB_KEYS.length) setActiveTab(TAB_KEYS[e.selectingIndex]);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      
      <div style={{ display: 'flex', alignItems: 'center', gap: 16, background: 'var(--color-sf-bg-primary)', padding: 20, borderRadius: 8, boxShadow: 'var(--shadow-default)' }}>
        <InitialsAvatar first={provider.firstName} last={provider.lastName} size={64} />
        <div style={{ flex: 1 }}>
          <div style={{ fontSize: 20, fontWeight: 700 }}>Dr. {provider.firstName} {provider.lastName}, {provider.title}</div>
          <div style={{ fontSize: 14, color: 'var(--color-sf-fg-tertiary)' }}>{provider.specialty} • {provider.locationName}</div>
          <div style={{ fontSize: 12, color: 'var(--color-sf-fg-quinary)', marginTop: 4 }}>NPI: {provider.npiNumber} • {provider.phoneNumber}</div>
        </div>
      </div>

      
      <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
        <KpiCard title="Appointments Today" value={kpis.apptsToday} loading={apptsQuery.loading} icon={<CalendarDays size={16} />} />
        <KpiCard title="Patients This Week" value={kpis.patientsThisWeek} loading={apptsQuery.loading} icon={<Users size={16} />} />
        <KpiCard title="Utilization" value={overallUtilization === null ? '—' : `${overallUtilization}%`} loading={utilizationQuery.loading} icon={<Activity size={16} />} />
        <KpiCard title="Cancellation Rate" value={pct(kpis.cancellationRate)} loading={apptsQuery.loading} icon={<XCircle size={16} />} />
        <KpiCard title="No-Show Rate" value={pct(kpis.noShowRate)} loading={apptsQuery.loading} icon={<UserX size={16} />} />
      </div>

      
      <TabComponent heightAdjustMode="Auto" selectedItem={TAB_KEYS.indexOf(activeTab)} selecting={onTabSelecting}>
        <TabItemsDirective>
          <TabItemDirective header={{ text: 'Schedule' }} />
          <TabItemDirective header={{ text: 'Analytics' }} />
        </TabItemsDirective>
      </TabComponent>

      <div>
        {activeTab === 'schedule' && (
          <ProviderScheduleTab
            appointments={appointments}
            loading={apptsQuery.loading && !apptsQuery.data}
            error={apptsQuery.error}
            onRetry={apptsQuery.refresh}
            selectedDate={today}
          />
        )}
        {activeTab === 'analytics' && (
          <ProviderAnalyticsTab
            utilizationData={utilizationData}
            utilizationLoading={utilizationQuery.loading && !utilizationQuery.data}
            utilizationError={utilizationQuery.error}
            onUtilizationRetry={utilizationQuery.refresh}
            noShowData={noShowData}
            noShowLoading={noShowQuery.loading && !noShowQuery.data}
            noShowError={noShowQuery.error}
            onNoShowRetry={noShowQuery.refresh}
            departmentName={provider.departmentName}
          />
        )}
      </div>
    </div>
  );
};
