// Angular/src/app/pages/schedule/schedule-page.component.ts
import { Component, inject, computed, signal, effect, ChangeDetectionStrategy, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { map } from 'rxjs';
import {
  ScheduleModule,
  EventSettingsModel,
  ActionEventArgs,
  CellClickEventArgs,
  EventClickArgs,
  NavigatingEventArgs,
  EventRenderedArgs,
  GroupModel,
} from '@syncfusion/ej2-angular-schedule';
import { DropDownListModule, ChangeEventArgs as DropDownChangeArgs } from '@syncfusion/ej2-angular-dropdowns';
import { ButtonModule } from '@syncfusion/ej2-angular-buttons';
import { HealthcareService } from '../../core/api/healthcare.service';
import { okOrThrow } from '../../core/api/api.service';
import { createAsyncResult } from '../../core/async/async-result';
import { ErrorBannerComponent } from '../../shared/error-banner/error-banner.component';
import { EmptyStateComponent } from '../../shared/empty-state/empty-state.component';
import { LoadingStateComponent } from '../../shared/loading-state/loading-state.component';
import { NewAppointmentDialogComponent } from './new-appointment-dialog.component';
import { AppointmentDetailPanelComponent } from './appointment-detail-panel.component';
import { getAppointmentColor, chooseTextColor } from '../../core/utils/appointment-colors';
import type {
  AppointmentSummaryDto,
  ProviderSummaryDto,
  DepartmentDto,
  CreateAppointmentRequest,
} from '../../core/models/dtos';

interface ScheduleEvent {
  Id: string;
  Subject: string;
  StartTime: Date;
  EndTime: Date;
  ProviderId: string;
  ResourceId: string;
  ProviderName: string;
  PatientName: string;
  Status: string;
  IsReadonly: boolean;
  AppointmentType: string;
  CategoryColor: string;
}

import {
  DayService,
  WeekService,
  WorkWeekService,
  MonthService,
  TimelineViewsService,
  ResizeService,
  DragAndDropService,
} from '@syncfusion/ej2-angular-schedule';

function computeVisibleRange(anchor: Date, view: string): [Date, Date] {
  if (view === 'Month') {
    const firstOfMonth = new Date(anchor.getFullYear(), anchor.getMonth(), 1);
    const start = new Date(firstOfMonth);
    start.setDate(start.getDate() - 7);
    const end = new Date(anchor.getFullYear(), anchor.getMonth() + 1, 1);
    end.setDate(end.getDate() + 7);
    return [start, end];
  }
  return [startOfWeek(anchor), endOfWeek(anchor)];
}

function startOfWeek(d: Date): Date {
  const date = new Date(d);
  const day = date.getDay();
  const diff = date.getDate() - day;
  return new Date(date.setDate(diff));
}

function endOfWeek(d: Date): Date {
  const start = startOfWeek(d);
  return new Date(start.getTime() + 6 * 86400000);
}

function formatDateOnly(d: Date): string {
  return d.toISOString().split('T')[0];
}

function formatEndOfDay(d: Date): string {
  const end = new Date(d);
  end.setUTCHours(23, 59, 59, 999);
  return end.toISOString();
}

@Component({
  selector: 'app-schedule-page',
  standalone: true,
  imports: [
    CommonModule,
    ScheduleModule,
    DropDownListModule,
    ButtonModule,
    ErrorBannerComponent,
    EmptyStateComponent,
    LoadingStateComponent,
    NewAppointmentDialogComponent,
    AppointmentDetailPanelComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './schedule-page.component.html',
  styleUrl: './schedule-page.component.scss',
  providers: [
    DayService,
    WeekService,
    WorkWeekService,
    MonthService,
    TimelineViewsService,
    ResizeService,
    DragAndDropService,
  ],
})
export class SchedulePageComponent {
  private healthcare = inject(HealthcareService);

  @ViewChild(NewAppointmentDialogComponent) dialog?: NewAppointmentDialogComponent;

  readonly selectedDate = signal(new Date());
  readonly currentView = signal<string>('WorkWeek');
  readonly departmentFilter = signal('');
  readonly providerFilter = signal('');
  readonly refreshTick = signal(0);
  readonly dialogVisible = signal(false);
  readonly dialogDateTime = signal<Date | undefined>(undefined);
  readonly dialogProviderId = signal<string | undefined>(undefined);
  readonly detailOpen = signal(false);
  readonly detailAppointmentId = signal<string>('');
  readonly isMobile = window.innerWidth <= 768;

  readonly departmentsState = createAsyncResult<DepartmentDto[]>(() =>
    this.healthcare.listDepartments().pipe(map((res) => okOrThrow(res)))
  );

  constructor() {
    effect(() => {
      const depts = this.departmentsState.data ?? [];
      if (!this.departmentFilter() && depts.length > 0) {
        this.departmentFilter.set(depts[0].departmentId);
        this.providersState.refresh();
        this.apptsState.refresh();
      }
    });
  }

  readonly providersState = createAsyncResult<{ items: ProviderSummaryDto[] }>(() =>
    this.healthcare
      .listProviders(this.departmentFilter() || undefined)
      .pipe(map((res) => okOrThrow(res)))
  );

  readonly apptsState = createAsyncResult<{ items: AppointmentSummaryDto[] }>(() => {
    const [rangeStart, rangeEnd] = computeVisibleRange(this.selectedDate(), this.currentView());
    const params: Record<string, string> = {
      dateFrom: formatDateOnly(rangeStart),
      dateTo: formatEndOfDay(rangeEnd),
      limit: '500',
    };
    if (this.departmentFilter()) params['departmentId'] = this.departmentFilter();
    if (this.providerFilter()) params['providerId'] = this.providerFilter();
    return this.healthcare.listAppointments(params).pipe(map((res) => okOrThrow(res)));
  });

  readonly events = computed<ScheduleEvent[]>(() => {
    const items = this.apptsState.data?.items ?? [];
    return items.map((a) => {
      const color = getAppointmentColor(a.appointmentType);
      return {
        Id: a.appointmentId,
        Subject: `${a.patientName} — ${a.appointmentType}`,
        StartTime: new Date(a.scheduledDateTime),
        EndTime: new Date(new Date(a.scheduledDateTime).getTime() + a.durationMinutes * 60000),
        ProviderId: a.providerId ?? this.providerFilter(),
        ResourceId: a.providerId ?? this.providerFilter(),
        ProviderName: a.providerName,
        PatientName: a.patientName,
        Status: a.status,
        IsReadonly: ['Completed', 'Cancelled', 'NoShow'].includes(a.status),
        AppointmentType: a.appointmentType,
        CategoryColor: color,
      };
    });
  });

  readonly eventSettings = computed<EventSettingsModel>(() => ({
    dataSource: this.events(),
    fields: {
      id: 'Id',
      subject: { name: 'Subject' },
      startTime: { name: 'StartTime' },
      endTime: { name: 'EndTime' },
    },
  } as EventSettingsModel));

  readonly filteredProviders = computed<ProviderSummaryDto[]>(() => {
    const all = this.providersState.data?.items ?? [];
    const dept = this.departmentFilter();
    return dept ? all.filter((p) => p.departmentId === dept) : all;
  });

  readonly resourceDataSource = computed(() =>
    this.filteredProviders().map((p) => ({
      text: `Dr. ${p.firstName} ${p.lastName}`,
      id: p.providerId,
    }))
  );

  readonly group = computed<GroupModel | undefined>(() => {
    if (this.providerFilter() || !this.departmentFilter() || this.resourceDataSource().length === 0) {
      return undefined;
    }
    return { byDate: true, resources: ['Providers'] };
  });

  readonly scheduleInstanceKey = computed(
    () => `${this.group() ? 'grouped' : 'flat'}|${this.resourceDataSource().map((r) => r.id).join(',')}`
  );

  readonly departmentOptions = computed(() => this.departmentsState.data ?? []);
  readonly departmentFields = { text: 'departmentName', value: 'departmentId', groupBy: 'locationName' };
  readonly providerFields = { text: 'lastName', value: 'providerId' };

  readonly dataError = computed(
    () => this.apptsState.error ?? this.providersState.error ?? this.departmentsState.error ?? null
  );

  readonly allDataReady = computed(
    () =>
      (!!this.apptsState.data || !!this.apptsState.error) &&
      (!!this.providersState.data || !!this.providersState.error) &&
      (!!this.departmentsState.data || !!this.departmentsState.error)
  );

  readonly scheduleLoading = computed(() => !this.allDataReady());

  onCellDoubleClick(args: CellClickEventArgs): void {
    args.cancel = true;
    const groupIndex = (args as unknown as { groupIndex?: number }).groupIndex;
    const resourceId =
      groupIndex !== undefined ? this.resourceDataSource()[groupIndex]?.id : undefined;
    this.openNewAppointment(args.startTime as Date, resourceId ?? (this.providerFilter() || undefined));
  }

  onEventClick(args: EventClickArgs): void {
    args.cancel = true;
    const id = (args.event as unknown as ScheduleEvent | undefined)?.Id;
    if (id) this.openDetailPanel(id);
  }

  onEventDoubleClick(args: EventClickArgs): void {
    args.cancel = true;
    const id = (args.event as unknown as ScheduleEvent | undefined)?.Id;
    if (id) this.openDetailPanel(id);
  }

  onNavigating(args: NavigatingEventArgs): void {
    if (args.action === 'date' && args.currentDate) {
      const next = new Date(args.currentDate as Date);
      if (next.getTime() === this.selectedDate().getTime()) return;
      this.selectedDate.set(next);
      this.apptsState.refresh();
    } else if (args.action === 'view' && args.currentView) {
      const nextView = args.currentView as string;
      if (nextView === this.currentView()) return;
      this.currentView.set(nextView);
      this.apptsState.refresh();
    }
  }

  onEventRendered(args: EventRenderedArgs): void {
    const data = args.data as unknown as ScheduleEvent;
    const bg = data?.CategoryColor;
    if (!bg || !args.element) return;
    const text = chooseTextColor(bg);
    args.element.style.backgroundColor = bg;
    args.element.style.color = text;
    args.element.style.borderColor = bg;
    args.element.querySelectorAll<HTMLElement>('.e-subject, .e-time, .e-date-time').forEach((node) => {
      node.style.color = 'inherit';
    });
  }

  onActionComplete(args: ActionEventArgs): void {
    if (args.requestType === 'eventCreated' && args.data && !Array.isArray(args.data)) {
      const ev = args.data as unknown as ScheduleEvent;
      this.openNewAppointment(ev.StartTime, ev.ProviderId);
    }
    if (args.requestType === 'eventChanged' || args.requestType === 'eventRemoved') {
      this.refreshTick.update((t) => t + 1);
      this.apptsState.refresh();
    }
  }

  onDepartmentChange(args: DropDownChangeArgs): void {
    this.departmentFilter.set((args.value as string) ?? '');
    this.providerFilter.set('');
    this.providersState.refresh();
    this.apptsState.refresh();
  }

  onProviderChange(args: DropDownChangeArgs): void {
    this.providerFilter.set((args.value as string) ?? '');
    this.apptsState.refresh();
  }

  openNewAppointment(initialDateTime?: Date, initialProviderId?: string): void {
    this.dialogDateTime.set(initialDateTime);
    this.dialogProviderId.set(initialProviderId ?? (this.providerFilter() || undefined));
    this.dialogVisible.set(true);
  }

  handleDialogSubmit(req: CreateAppointmentRequest): void {
    this.healthcare
      .createAppointment(req)
      .pipe(map((res) => okOrThrow(res)))
      .subscribe({
        next: () => {
          this.dialogVisible.set(false);
          this.apptsState.refresh();
        },
        error: (e: unknown) =>
          alert(e instanceof Error ? e.message : 'Failed to book appointment'),
      });
  }

  openDetailPanel(appointmentId: string): void {
    this.detailAppointmentId.set(appointmentId);
    this.detailOpen.set(true);
  }

  closeDetailPanel(): void {
    this.detailOpen.set(false);
  }

  onDetailChanged(): void {
    this.apptsState.refresh();
  }

  refreshAll(): void {
    this.apptsState.refresh();
    this.providersState.refresh();
    this.departmentsState.refresh();
  }
}


<div class="schedule-root">
  <div class="toolbar">
    <div class="filters">
      <div class="filter">
        <ejs-dropdownlist
          [dataSource]="departmentOptions()"
          [fields]="departmentFields"
          placeholder="All Departments"
          [allowFiltering]="true"
          [sortOrder]="'Ascending'"
          [showClearButton]="true"
          [value]="departmentFilter()"
          width="200px"
          cssClass="dept-group-ddl"
          (change)="onDepartmentChange($event)">
        </ejs-dropdownlist>
      </div>
      <div class="filter">
        <ejs-dropdownlist
          [dataSource]="filteredProviders()"
          [fields]="providerFields"
          placeholder="All Providers"
          [allowFiltering]="true"
          [sortOrder]="'Ascending'"
          [showClearButton]="true"
          [value]="providerFilter()"
          width="200px"
          (change)="onProviderChange($event)">
        </ejs-dropdownlist>
      </div>
      <button ejs-button cssClass="e-primary" iconCss="e-icons e-plus" (click)="openNewAppointment()">
        New Appointment
      </button>
    </div>
  </div>

  @if (dataError(); as err) {
    <app-error-banner
      title="Schedule data could not be loaded"
      message="Schedule data could not be loaded — showing an empty planner. Click Retry to attempt loading again."
      (retry)="refreshAll()">
    </app-error-banner>
  }

  @if (scheduleLoading()) {
    <app-loading-state label="Loading schedule…"></app-loading-state>
  } @else if (dataError()) {
    <div class="empty-shell">
      <app-empty-state title="Empty schedule" description="No events to display."></app-empty-state>
    </div>
  } @else {
    <div class="schedule-wrap">
      @for (instanceKey of [scheduleInstanceKey()]; track instanceKey) {
      <ejs-schedule
        height="100%"
        [selectedDate]="selectedDate()"
        currentView="WorkWeek"
        [startHour]="'08:00'"
        [endHour]="'18:00'"
        [workHours]="{ highlight: true, start: '08:00', end: '17:00' }"
        [showQuickInfo]="false"
        [eventSettings]="eventSettings()"
        [group]="group()"
        (actionComplete)="onActionComplete($event)"
        (cellDoubleClick)="onCellDoubleClick($event)"
        (eventClick)="onEventClick($event)"
        (eventDoubleClick)="onEventDoubleClick($event)"
        (navigating)="onNavigating($event)"
        (eventRendered)="onEventRendered($event)"
        [enableAdaptiveUI]="isMobile"
        [timezone]="'UTC'" >
        <e-views>
          <e-view option="Day"></e-view>
          <e-view option="WorkWeek"></e-view>
          <e-view option="Month"></e-view>
          <e-view option="Agenda"></e-view>
          <e-view option="TimelineWeek"></e-view>
        </e-views>
        <e-resources>
          <e-resource
            field="ProviderId"
            title="Provider"
            name="Providers"
            [dataSource]="resourceDataSource()"
            textField="text"
            idField="id"
            [allowMultiple]="false">
          </e-resource>
        </e-resources>
      </ejs-schedule>
      }
    </div>
  }

  @if (dialogVisible()) {
    <app-new-appointment-dialog
      [visible]="dialogVisible()"
      [initialDateTime]="dialogDateTime()"
      [initialProviderId]="dialogProviderId()"
      [providers]="filteredProviders()"
      [departments]="departmentsState.data ?? []"
      (onClose)="dialogVisible.set(false)"
      (onSubmit)="handleDialogSubmit($event)">
    </app-new-appointment-dialog>
  }

  <app-appointment-detail-panel
    [isOpen]="detailOpen()"
    [appointmentId]="detailAppointmentId()"
    (close)="closeDetailPanel()"
    (changed)="onDetailChanged()">
  </app-appointment-detail-panel>
</div>

// React/src/pages/SchedulePage.tsx
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  ScheduleComponent,
  ViewsDirective,
  ViewDirective,
  ResourcesDirective,
  ResourceDirective,
  Day,
  Week,
  WorkWeek,
  Month,
  Inject,
  Resize,
  DragAndDrop,
  ActionEventArgs,
  EventSettingsModel,
  CellClickEventArgs,
  EventClickArgs,
  NavigatingEventArgs,
  EventRenderedArgs,
  Agenda,
  TimelineViews,
} from '@syncfusion/ej2-react-schedule';
import { DropDownListComponent, ChangeEventArgs as DropDownChangeArgs } from '@syncfusion/ej2-react-dropdowns';
import { ButtonComponent } from '@syncfusion/ej2-react-buttons';
import { useAsyncResult } from '@hooks/useAsyncResult';
import {
  listAppointments,
  createAppointment,
  listProviders,
  listDepartments,
} from '@services/healthcare.service';
import { withDepartmentLabel } from '../utils/department';
import { NewAppointmentDialog } from '@components/appointments/NewAppointmentDialog';
import { AppointmentDetailPanel } from '@components/appointments/AppointmentDetailPanel';
import { ErrorBanner } from '@components/shared/ErrorBanner';
import { EmptyState } from '@components/shared/EmptyState';
import { LoadingState } from '@components/shared/LoadingState';
import { ScheduleErrorBoundary } from '@components/shared/ScheduleErrorBoundary';
import { APPOINTMENT_TYPE_COLORS, getAppointmentColor, chooseTextColor } from '../utils/appointmentColors';
import type { AppointmentSummaryDto, CreateAppointmentRequest } from '@models/dtos';

interface ScheduleEvent {
  Id: string;
  Subject: string;
  StartTime: Date;
  EndTime: Date;
  ProviderId: string;
  ResourceId: string;
  ProviderName: string;
  PatientName: string;
  Status: string;
  IsReadonly: boolean;
  AppointmentType: string;
  CategoryColor: string;
}

export const SchedulePage: React.FC = () => {
  const scheduleRef = useRef<ScheduleComponent>(null);
  const deptDdlRef = useRef<DropDownListComponent>(null);
  const [selectedDate, setSelectedDate] = useState<Date>(new Date());
  const [currentView, setCurrentView] = useState<string>('Day');
  const [departmentFilter, setDepartmentFilter] = useState<string>('');
  const [providerFilter, setProviderFilter] = useState<string>('');
  const [dialogVisible, setDialogVisible] = useState(false);
  const [dialogDateTime, setDialogDateTime] = useState<Date | undefined>(undefined);
  const [dialogProviderId, setDialogProviderId] = useState<string | undefined>(undefined);
  const [refreshTick, setRefreshTick] = useState(0);
  const [detailPanel, setDetailPanel] = useState<{ open: boolean; appointmentId?: string }>({ open: false });

  const apptsQuery = useAsyncResult(() => {
    const [rangeStart, rangeEnd] = computeVisibleRange(selectedDate, currentView);
    const params: Record<string, string> = { dateFrom: formatDate(rangeStart), dateTo: formatEndOfDay(rangeEnd), limit: '500' };
    if (departmentFilter) params.departmentId = departmentFilter;
    if (providerFilter) params.providerId = providerFilter;
    return listAppointments(params);
  }, [selectedDate, currentView, departmentFilter, providerFilter, refreshTick]);
  const providersQuery = useAsyncResult(() => listProviders(departmentFilter || undefined), [departmentFilter]);
  const departmentsQuery = useAsyncResult(() => listDepartments(), []);

  
  
  useEffect(() => {
    const depts = departmentsQuery.data?.data ?? [];
    if (!departmentFilter && depts.length > 0) {
      setDepartmentFilter(depts[0].departmentId);
    }
  }, [departmentsQuery.data, departmentFilter]);

  const events: ScheduleEvent[] = useMemo(() => {
    const items = apptsQuery.data?.data?.items;
    if (!items) {
      if (apptsQuery.data) {
        
        console.warn('[SchedulePage] listAppointments returned no items', apptsQuery.data);
      }
      return [];
    }
    return items.map((a: AppointmentSummaryDto) => {
      const color = getAppointmentColor(a.appointmentType);
      if (!APPOINTMENT_TYPE_COLORS[a.appointmentType]) {
        
        console.warn(`[SchedulePage] Unmapped appointment type "${a.appointmentType}" — falling back to neutral color.`);
      }
      return {
        Id: a.appointmentId,
        Subject: `${a.patientName} — ${a.appointmentType}`,
        StartTime: new Date(a.scheduledDateTime),
        EndTime: new Date(new Date(a.scheduledDateTime).getTime() + a.durationMinutes * 60000),
        ProviderId: a.providerId ?? providerFilter,
        ResourceId: a.providerId ?? providerFilter,
        ProviderName: a.providerName,
        PatientName: a.patientName,
        Status: a.status,
        IsReadonly: ['Completed', 'Cancelled', 'NoShow'].includes(a.status),
        AppointmentType: a.appointmentType,
        CategoryColor: color,
      };
    });
  }, [apptsQuery.data, providerFilter]);

  
  useEffect(() => {
    if (scheduleRef.current && events.length > 0) {
      scheduleRef.current.refreshEvents();
    }
  }, [events]);

  const eventSettings: EventSettingsModel = useMemo(() => ({
    dataSource: events,
    fields: {
      id: 'Id',
      subject: { name: 'Subject' },
      startTime: { name: 'StartTime' },
      endTime: { name: 'EndTime' },
    },
  }), [events]);

  
  
  
  
  
  const departmentOptions = useMemo(
    () => withDepartmentLabel(departmentsQuery.data?.data ?? []),
    [departmentsQuery.data]
  );

  
  
  
  
  
  
  
  useEffect(() => {
    const ddl = deptDdlRef.current;
    if (!ddl || departmentOptions.length === 0) return;
    const next = departmentFilter || null;
    if (ddl.value !== next) {
      ddl.value = next;
    }
  }, [departmentFilter, departmentOptions]);

  const filteredProviders = useMemo(() => {
    const all = providersQuery.data?.data?.items ?? [];
    if (departmentFilter) return all.filter((p) => p.departmentId === departmentFilter);
    return all;
  }, [providersQuery.data, departmentFilter]);

  const resourceDataSource = useMemo(() => {
    return filteredProviders.map((p) => ({
      text: `Dr. ${p.firstName} ${p.lastName}`,
      id: p.providerId,
    }));
  }, [filteredProviders]);

  
  
  
  
  
  
  
  const group = useMemo(() => {
    if (providerFilter || !departmentFilter || resourceDataSource.length === 0) return undefined;
    return {
      byDate: true,
      resources: ['Providers'],
    };
  }, [providerFilter, departmentFilter, resourceDataSource]);





  const scheduleKey = useMemo(
    () => `${group ? 'grouped' : 'flat'}|${resourceDataSource.map((r) => r.id).join(',')}`,
    [group, resourceDataSource]
  );

  const handleOpenNewAppointment = useCallback(
    (initialDateTime?: Date, initialProviderId?: string) => {
      setDialogDateTime(initialDateTime);
      setDialogProviderId(initialProviderId ?? (providerFilter || undefined));
      setDialogVisible(true);
    },
    [providerFilter]
  );

  const openDetailPanel = useCallback((appointmentId: string) => {
    setDetailPanel({ open: true, appointmentId });
  }, []);

  const closeDetailPanel = useCallback(() => {
    setDetailPanel({ open: false });
  }, []);

  const onCellDoubleClick = useCallback(
    (args: CellClickEventArgs) => {
      args.cancel = true;
      const resourceId = (args as any).groupIndex !== undefined
        ? resourceDataSource[(args as any).groupIndex]?.id
        : undefined;
      handleOpenNewAppointment(args.startTime as Date, resourceId ?? undefined);
    },
    [handleOpenNewAppointment, resourceDataSource]
  );

  const onEventClick = useCallback(
    (args: EventClickArgs) => {
      
      
      args.cancel = true;
      const id = (args.event as any)?.Id as string | undefined;
      if (id) openDetailPanel(id);
    },
    [openDetailPanel]
  );

  const onEventDoubleClick = useCallback(
    (args: EventClickArgs) => {
      args.cancel = true;
      const id = (args.event as any)?.Id as string | undefined;
      if (id) openDetailPanel(id);
    },
    [openDetailPanel]
  );

  const onNavigating = useCallback((args: NavigatingEventArgs) => {
    if (args.action === 'date' && args.currentDate) {
      setSelectedDate(new Date(args.currentDate as Date));
    } else if (args.action === 'view' && args.currentView) {
      setCurrentView(args.currentView as string);
    }
  }, []);

  const onEventRendered = useCallback((args: EventRenderedArgs) => {
    const data = args.data as ScheduleEvent;
    const bg = data?.CategoryColor;
    if (!bg || !args.element) return;

    const text = chooseTextColor(bg);
    args.element.style.backgroundColor = bg;
    args.element.style.color = text;
    args.element.style.borderColor = bg;

    
    
    const textNodes = args.element.querySelectorAll<HTMLElement>('.e-subject, .e-time, .e-date-time');
    textNodes.forEach((node) => {
      node.style.color = 'inherit';
    });
  }, []);

  const onActionComplete = useCallback((args: ActionEventArgs) => {
    if (args.requestType === 'eventCreated' && args.data && !Array.isArray(args.data)) {
      const ev = args.data as ScheduleEvent;
      setDialogDateTime(ev.StartTime);
      setDialogProviderId(ev.ProviderId);
      setDialogVisible(true);
    }
    if (args.requestType === 'eventChanged' || args.requestType === 'eventRemoved') {
      setRefreshTick((t) => t + 1);
    }
  }, []);

  const handleDialogSubmit = async (req: CreateAppointmentRequest) => {
    const res = await createAppointment(req);
    if (res.status === 'ok') {
      setDialogVisible(false);
      setRefreshTick((t) => t + 1);
    } else {
      alert(res.error?.detail ?? 'Failed to book appointment');
    }
  };

  
  
  
  const dataError = apptsQuery.error || providersQuery.error || departmentsQuery.error || null;

  
  
  
  
  
  
  const allDataReady =
    (!!apptsQuery.data || !!apptsQuery.error) &&
    (!!providersQuery.data || !!providersQuery.error) &&
    (!!departmentsQuery.data || !!departmentsQuery.error);

  const scheduleLoading = !allDataReady;

  const refreshAll = useCallback(() => {
    apptsQuery.refresh();
    providersQuery.refresh();
    departmentsQuery.refresh();
  }, [apptsQuery, providersQuery, departmentsQuery]);

  const isMobile = window.innerWidth <= 768;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
      <div style={{ display: 'flex', justifyContent: 'flex-end', alignItems: 'center', marginBottom: 12, flexWrap: 'wrap', gap: 12 }}>
        <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap' }}>
          <DropDownListComponent
            ref={deptDdlRef}
            cssClass="dept-group-ddl"
            dataSource={departmentOptions as any}
            fields={{ text: 'departmentName', value: 'departmentId', groupBy: 'locationName' }}
            sortOrder="Ascending"
            showClearButton
            placeholder="All Departments"
            change={(e: DropDownChangeArgs) => {
              setDepartmentFilter((e.value as string) ?? '');
              setProviderFilter('');
            }}
            value={departmentFilter}
            allowFiltering
            width="200px"
          />
          <DropDownListComponent
            dataSource={filteredProviders as any}
            fields={{ text: 'lastName', value: 'providerId' }}
            sortOrder="Ascending"
            showClearButton
            placeholder="All Providers"
            change={(e: DropDownChangeArgs) => setProviderFilter((e.value as string) ?? '')}
            value={providerFilter}
            allowFiltering
            width="200px"
          />
          <ButtonComponent
            cssClass="e-primary"
            iconCss="e-icons e-plus"
            onClick={() => handleOpenNewAppointment()}
          >
            New Appointment
          </ButtonComponent>
        </div>
      </div>

      {dataError && (
        <ErrorBanner
          title="Schedule data could not be loaded"
          message="Schedule data could not be loaded — showing an empty planner. Click Retry to attempt loading again."
          onRetry={refreshAll}
        />
      )}

      {scheduleLoading ? (
        <LoadingState label="Loading schedule…" />
      ) : dataError ? (
        
        
        <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'var(--color-sf-bg-secondary)', borderTop: '1px solid var(--color-sf-border-secondary)' }}>
          <EmptyState title="Empty schedule" description="No events to display." />
        </div>
      ) : (
        
        
        <ScheduleErrorBoundary onRetry={refreshAll}>
          <ScheduleComponent
            key={scheduleKey}
            ref={scheduleRef}
            height="100%"
            selectedDate={selectedDate}
            currentView="WorkWeek"
            showQuickInfo={false}
            enableAdaptiveUI={isMobile}
            startHour="08:00"
            endHour="18:00"
            workHours={{ highlight: true, start: '08:00', end: '17:00' }}
            eventSettings={dataError ? { dataSource: [] } : eventSettings}
            actionComplete={onActionComplete}
            cellDoubleClick={onCellDoubleClick}
            eventClick={onEventClick}
            eventDoubleClick={onEventDoubleClick}
            navigating={onNavigating}
            eventRendered={onEventRendered}
            group={group}
            timezone="UTC"
          >
            <ViewsDirective>
              <ViewDirective option="Day" />
              <ViewDirective option="WorkWeek" />
              <ViewDirective option="Month" />
              <ViewDirective option="Agenda" />
              <ViewDirective option="TimelineWeek" />
            </ViewsDirective>
             <ResourcesDirective>
              <ResourceDirective
                field="ProviderId"
                title="Provider"
                name="Providers"
                dataSource={resourceDataSource as any}
                textField="text"
                idField="id"
                allowMultiple={false}
              />
            </ResourcesDirective>
            <Inject services={[Day, Week, WorkWeek, Month, Agenda, TimelineViews, Resize, DragAndDrop]} />
          </ScheduleComponent>
        </ScheduleErrorBoundary>
      )}

      
      {dialogVisible && (
        <NewAppointmentDialog
          visible={dialogVisible}
          initialDateTime={dialogDateTime}
          initialProviderId={dialogProviderId}
          providers={filteredProviders}
          departments={departmentsQuery.data?.data ?? []}
          onClose={() => setDialogVisible(false)}
          onSubmit={handleDialogSubmit}
          loading={false}
        />
      )}

      {detailPanel.open && (
        <AppointmentDetailPanel
          isOpen={detailPanel.open}
          appointmentId={detailPanel.appointmentId}
          onClose={closeDetailPanel}
          onChanged={() => setRefreshTick((t) => t + 1)}
        />
      )}
    </div>
  );
};

function formatDate(d: Date) {
  return d.toISOString().split('T')[0];
}

function formatEndOfDay(d: Date) {
  
  
  const end = new Date(d);
  end.setUTCHours(23, 59, 59, 999);
  return end.toISOString();
}

function computeVisibleRange(anchor: Date, view: string): [Date, Date] {
  if (view === 'Month') {
    const firstOfMonth = new Date(anchor.getFullYear(), anchor.getMonth(), 1);
    const start = new Date(firstOfMonth);
    start.setDate(start.getDate() - 7);
    const end = new Date(anchor.getFullYear(), anchor.getMonth() + 1, 1);
    end.setDate(end.getDate() + 7);
    return [start, end];
  }
  return [startOfWeek(anchor), endOfWeek(anchor)];
}

function startOfWeek(d: Date) {
  const date = new Date(d);
  const day = date.getDay();
  const diff = date.getDate() - day;
  return new Date(date.setDate(diff));
}

function endOfWeek(d: Date) {
  const start = startOfWeek(d);
  return new Date(start.getTime() + 6 * 86400000);
}
