// Angular/src/app/pages/settings/settings-page.component.ts
import { Component, inject, computed, ChangeDetectionStrategy, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { map } from 'rxjs';
import {
  GridModule,
  PageService,
  SortService,
  ToolbarService,
  EditService,
} from '@syncfusion/ej2-angular-grids';
import { HealthcareService } from '../../core/api/healthcare.service';
import { okOrThrow } from '../../core/api/api.service';
import { createAsyncResult } from '../../core/async/async-result';
import { ThemeService, ThemeMode } from '../../core/theme/theme.service';
import { ErrorBannerComponent } from '../../shared/error-banner/error-banner.component';
import { LoadingStateComponent } from '../../shared/loading-state/loading-state.component';
import type { DepartmentDto, LocationDto } from '../../core/models/dtos';

type SettingsTab = 'departments' | 'locations' | 'theme';

const THEME_OPTIONS: { mode: ThemeMode; label: string }[] = [
  { mode: 'light', label: 'Light' },
  { mode: 'dark', label: 'Dark' },
  { mode: 'system', label: 'System' },
];

@Component({
  selector: 'app-settings-page',
  standalone: true,
  imports: [CommonModule, GridModule, ErrorBannerComponent, LoadingStateComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './settings-page.component.html',
  styleUrl: './settings-page.component.scss',
  providers: [PageService, SortService, ToolbarService, EditService],
})
export class SettingsPageComponent {
  private healthcare = inject(HealthcareService);
  protected themeService = inject(ThemeService);

  readonly activeTab = signal<SettingsTab>('departments');
  readonly themeOptions = THEME_OPTIONS;
  readonly tabs: { id: SettingsTab; label: string }[] = [
    { id: 'departments', label: 'Departments' },
    { id: 'locations', label: 'Locations' },
    { id: 'theme', label: 'Appearance' },
  ];

  readonly pageSettings = { pageSize: 20 };

  private readonly departmentsState = createAsyncResult<DepartmentDto[]>(() =>
    this.healthcare.listDepartments().pipe(map((res) => okOrThrow(res)))
  );
  private readonly locationsState = createAsyncResult<LocationDto[]>(() =>
    this.healthcare.listLocations().pipe(map((res) => okOrThrow(res)))
  );

  readonly departments = computed(() => this.departmentsState.data ?? []);
  readonly locations = computed(() => this.locationsState.data ?? []);
  readonly departmentsLoading = computed(() => this.departmentsState.loading);
  readonly locationsLoading = computed(() => this.locationsState.loading);
  readonly departmentsError = computed(() => this.departmentsState.error);
  readonly locationsError = computed(() => this.locationsState.error);

  setTab(tab: SettingsTab): void {
    this.activeTab.set(tab);
  }

  setTheme(mode: ThemeMode): void {
    this.themeService.setMode(mode);
  }

  retryDepartments(): void {
    this.departmentsState.refresh();
  }

  retryLocations(): void {
    this.locationsState.refresh();
  }
}


<div class="settings">
  <nav class="tabs" role="tablist">
    @for (tab of tabs; track tab.id) {
      <button
        type="button"
        role="tab"
        [attr.aria-selected]="activeTab() === tab.id"
        class="tab"
        [class.tab--active]="activeTab() === tab.id"
        (click)="setTab(tab.id)">
        {{ tab.label }}
      </button>
    }
  </nav>

  <div class="panel">
    @if (activeTab() === 'departments') {
      @if (departmentsError(); as err) {
        <app-error-banner title="Unable to load departments" [message]="err" (retry)="retryDepartments()"></app-error-banner>
      } @else if (departmentsLoading() && departments().length === 0) {
        <app-loading-state inline label="Loading departments…"></app-loading-state>
      } @else {
        <ejs-grid
          [dataSource]="departments()"
          [allowPaging]="true"
          [pageSettings]="pageSettings"
          [allowSorting]="true"
          [enableAdaptiveUI]="true"
          adaptiveUIMode="Mobile">
          <e-columns>
            <e-column field="departmentCode" headerText="Code" width="100" isPrimaryKey="true"></e-column>
            <e-column field="departmentName" headerText="Name" width="200"></e-column>
            <e-column field="locationName" headerText="Location" width="200"></e-column>
            <e-column field="isActive" headerText="Active" width="90" displayAsCheckBox="true"></e-column>
          </e-columns>
        </ejs-grid>
      }
    }

    @if (activeTab() === 'locations') {
      @if (locationsError(); as err) {
        <app-error-banner title="Unable to load locations" [message]="err" (retry)="retryLocations()"></app-error-banner>
      } @else if (locationsLoading() && locations().length === 0) {
        <app-loading-state inline label="Loading locations…"></app-loading-state>
      } @else {
        <ejs-grid
          [dataSource]="locations()"
          [allowPaging]="true"
          [pageSettings]="pageSettings"
          [allowSorting]="true"
          [enableAdaptiveUI]="true"
          adaptiveUIMode="Mobile">
          <e-columns>
            <e-column field="locationName" headerText="Name" width="200" isPrimaryKey="true"></e-column>
            <e-column field="addressLine" headerText="Address" width="240"></e-column>
            <e-column field="city" headerText="City" width="120"></e-column>
            <e-column field="state" headerText="State" width="80"></e-column>
            <e-column field="postalCode" headerText="ZIP" width="100"></e-column>
            <e-column field="phoneNumber" headerText="Phone" width="140"></e-column>
            <e-column field="timeZone" headerText="Time Zone" width="160"></e-column>
            <e-column field="isActive" headerText="Active" width="90" displayAsCheckBox="true"></e-column>
          </e-columns>
        </ejs-grid>
      }
    }

    @if (activeTab() === 'theme') {
      <div class="appearance">
        <h3 class="appearance-title">Appearance</h3>

        <div class="appearance-row">
          <div class="appearance-meta">
            <div class="appearance-label">Theme</div>
            <div class="appearance-hint">Choose light, dark, or follow your system setting</div>
          </div>
          <div class="segmented" role="radiogroup" aria-label="Theme">
            @for (opt of themeOptions; track opt.mode) {
              <button
                type="button"
                role="radio"
                [attr.aria-checked]="themeService.getMode() === opt.mode"
                class="segmented-item"
                [class.segmented-item--active]="themeService.getMode() === opt.mode"
                (click)="setTheme(opt.mode)">
                {{ opt.label }}
              </button>
            }
          </div>
        </div>

      </div>
    }
  </div>
</div>

// React/src/pages/SettingsPage.tsx
import React, { useState } from 'react';
import {
  GridComponent,
  ColumnsDirective,
  ColumnDirective,
  Inject,
  Page,
  Sort,
  Toolbar,
  Edit,
} from '@syncfusion/ej2-react-grids';
import { useAsyncResult } from '@hooks/useAsyncResult';
import { listDepartments, listLocations } from '@services/healthcare.service';
import { ErrorBanner } from '@components/shared/ErrorBanner';
import { LoadingState } from '@components/shared/LoadingState';
import { useTheme, type ThemeMode } from '../theme/ThemeProvider';

const THEME_OPTIONS: { mode: ThemeMode; label: string }[] = [
  { mode: 'light', label: 'Light' },
  { mode: 'dark', label: 'Dark' },
  { mode: 'system', label: 'System' },
];

export const SettingsPage: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'departments' | 'locations' | 'theme'>('departments');
  const { mode, setMode } = useTheme();
  const departmentsQuery = useAsyncResult(() => listDepartments(), []);
  const locationsQuery = useAsyncResult(() => listLocations(), []);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>

      <div style={{ display: 'flex', gap: 4, borderBottom: '1px solid var(--color-sf-border-secondary)' }}>
        {(['departments', 'locations', 'theme'] as const).map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            style={{
              padding: '10px 16px',
              background: 'transparent',
              border: 'none',
              borderBottom: activeTab === tab ? '2px solid var(--color-sf-border-brand-solid)' : '2px solid transparent',
              color: activeTab === tab ? 'var(--color-sf-fg-brand-primary)' : 'var(--color-sf-fg-tertiary)',
              fontWeight: activeTab === tab ? 600 : 400,
              cursor: 'pointer',
              fontSize: 14,
            }}
          >
            {tab === 'departments' ? 'Departments' : tab === 'locations' ? 'Locations' : 'Appearance'}
          </button>
        ))}
      </div>

      <div style={{ background: 'var(--color-sf-bg-primary)', borderRadius: 8, padding: 20, boxShadow: 'var(--shadow-default)' }}>
        {activeTab === 'departments' && (
          <>
            {departmentsQuery.error && <ErrorBanner message={departmentsQuery.error} onRetry={departmentsQuery.refresh} />}
            {departmentsQuery.loading && !departmentsQuery.data ? (
              <LoadingState inline label="Loading departments…" />
            ) : (
              <GridComponent
                dataSource={departmentsQuery.data?.data ?? []}
                enableAdaptiveUI
                adaptiveUIMode="Mobile"
                allowPaging
                pageSettings={{ pageSize: 20 }}
                allowSorting
                >
                <ColumnsDirective>
                  <ColumnDirective field="departmentCode" headerText="Code" width="100" />
                  <ColumnDirective field="departmentName" headerText="Name" width="200" />
                  <ColumnDirective field="locationName" headerText="Location" width="200" />
                  <ColumnDirective field="isActive" headerText="Active" width="90" displayAsCheckBox />
                </ColumnsDirective>
                <Inject services={[Page, Sort, Toolbar, Edit]} />
              </GridComponent>
            )}
          </>
        )}

        {activeTab === 'locations' && (
          <>
            {locationsQuery.error && <ErrorBanner message={locationsQuery.error} onRetry={locationsQuery.refresh} />}
            {locationsQuery.loading && !locationsQuery.data ? (
              <LoadingState inline label="Loading locations…" />
            ) : (
              <GridComponent
                dataSource={locationsQuery.data?.data ?? []}
                enableAdaptiveUI
                adaptiveUIMode="Mobile"
                allowPaging
                pageSettings={{ pageSize: 20 }}
                allowSorting
                >
                <ColumnsDirective>
                  <ColumnDirective field="locationName" headerText="Name" width="200" />
                  <ColumnDirective field="addressLine" headerText="Address" width="240" />
                  <ColumnDirective field="city" headerText="City" width="120" />
                  <ColumnDirective field="state" headerText="State" width="80" />
                  <ColumnDirective field="postalCode" headerText="ZIP" width="100" />
                  <ColumnDirective field="phoneNumber" headerText="Phone" width="140" />
                  <ColumnDirective field="timeZone" headerText="Time Zone" width="160" />
                  <ColumnDirective field="isActive" headerText="Active" width="90" displayAsCheckBox />
                </ColumnsDirective>
                <Inject services={[Page, Sort, Toolbar, Edit]} />
              </GridComponent>
            )}
          </>
        )}

        {activeTab === 'theme' && (
          <div style={{ maxWidth: 400 }}>
            <div style={{ fontWeight: 600, fontSize: 16, marginBottom: 12, color: 'var(--color-sf-fg-primary)' }}>Appearance</div>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '12px 0', borderBottom: '1px solid var(--color-sf-border-secondary)' }}>
              <div>
                <div style={{ fontWeight: 500, color: 'var(--color-sf-fg-primary)' }}>Theme</div>
                <div style={{ fontSize: 12, color: 'var(--color-sf-fg-tertiary)' }}>Choose light, dark, or follow your system setting</div>
              </div>
              <div
                role="radiogroup"
                aria-label="Theme"
                style={{
                  display: 'flex',
                  gap: 2,
                  padding: 2,
                  background: 'var(--color-sf-bg-tertiary)',
                  borderRadius: 'var(--radius-8)',
                }}
              >
                {THEME_OPTIONS.map(({ mode: optMode, label }) => {
                  const active = mode === optMode;
                  return (
                    <button
                      key={optMode}
                      type="button"
                      role="radio"
                      aria-checked={active}
                      onClick={() => setMode(optMode)}
                      style={{
                        padding: '6px 12px',
                        border: 'none',
                        borderRadius: 'var(--radius-6)',
                        background: active ? 'var(--color-sf-bg-primary)' : 'transparent',
                        color: active ? 'var(--color-sf-fg-brand-primary)' : 'var(--color-sf-fg-tertiary)',
                        fontSize: 12,
                        fontWeight: active ? 600 : 500,
                        cursor: 'pointer',
                        boxShadow: active ? 'var(--shadow-sm)' : 'none',
                      }}
                    >
                      {label}
                    </button>
                  );
                })}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
