// React/src/components/waitlist/SlotMatchDialog.tsx
import React, { useEffect, useState } from 'react';
import { DialogComponent } from '@syncfusion/ej2-react-popups';
import { ButtonComponent } from '@syncfusion/ej2-react-buttons';
import { DropDownListComponent } from '@syncfusion/ej2-react-dropdowns';
import { DatePickerComponent } from '@syncfusion/ej2-react-calendars';
import {
  listProviders,
  getProviderAvailability,
  createAppointment,
  matchWaitlistEntry,
} from '@services/healthcare.service';
import type { WaitlistEntryDto, SlotDto, ProviderSummaryDto } from '@models/dtos';
import { ErrorBanner } from '@components/shared/ErrorBanner';
import { LoadingState } from '@components/shared/LoadingState';
import { fmtDate } from '../../utils/dateFormat';

export interface SlotMatchDialogProps {
  entry: WaitlistEntryDto;
  onClose: () => void;
  onMatched: () => void;
}

function toDateOnly(value: string): Date {
  const d = new Date(value);
  return isNaN(d.getTime()) ? new Date() : d;
}

function formatTime(value: string): string {
  return new Date(value).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
}

function toLocalDateOnly(value: Date): string {
  const year = value.getFullYear();
  const month = `${value.getMonth() + 1}`.padStart(2, '0');
  const day = `${value.getDate()}`.padStart(2, '0');
  return `${year}-${month}-${day}`;
}

type ProviderOption = ProviderSummaryDto & { displayName: string };

export const SlotMatchDialog: React.FC<SlotMatchDialogProps> = ({ entry, onClose, onMatched }) => {
  const [providers, setProviders] = useState<ProviderOption[]>([]);
  const [providerId, setProviderId] = useState<string>(entry.preferredProviderId ?? '');
  const [date, setDate] = useState<Date>(toDateOnly(entry.preferredDateRangeStart));
  const [slots, setSlots] = useState<SlotDto[]>([]);
  const [selectedSlot, setSelectedSlot] = useState<SlotDto | null>(null);
  const [finding, setFinding] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  
  useEffect(() => {
    let active = true;
    listProviders(entry.preferredDepartmentId)
      .then((res) => {
        if (!active || res.status !== 'ok') return;
        const list: ProviderOption[] = (res.data?.items ?? [])
          .map((p) => ({ ...p, displayName: `${p.title} ${p.firstName} ${p.lastName}`.trim() }))
          .sort((a, b) => a.lastName.localeCompare(b.lastName));
        setProviders(list);
        if (!entry.preferredProviderId && list.length > 0) {
          setProviderId((prev) => prev || list[0].providerId);
        }
      })
      .catch(() => undefined);
    return () => {
      active = false;
    };
  }, [entry.preferredDepartmentId, entry.preferredProviderId]);

  const findSlots = async () => {
    if (!providerId) {
      setError('Select a provider first.');
      return;
    }
    setFinding(true);
    setError(null);
    setSelectedSlot(null);
    try {
      const iso = toLocalDateOnly(date);
      const res = await getProviderAvailability(providerId, iso);
      if (res.status === 'ok') {
        setSlots((res.data ?? []).filter((s) => s.isAvailable));
      } else {
        setError(res.error?.title ?? 'Could not load availability.');
        setSlots([]);
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Could not load availability.');
      setSlots([]);
    } finally {
      setFinding(false);
    }
  };

  const confirmMatch = async () => {
    if (!selectedSlot) return;
    setSubmitting(true);
    setError(null);
    try {
      const durationMinutes = Math.max(
        15,
        Math.round((new Date(selectedSlot.slotEnd).getTime() - new Date(selectedSlot.slotStart).getTime()) / 60000)
      );
      const created = await createAppointment({
        patientId: entry.patientId,
        providerId: selectedSlot.providerId,
        departmentId: entry.preferredDepartmentId,
        locationId: selectedSlot.locationId,
        appointmentType: entry.requestedAppointmentType,
        scheduledDateTime: selectedSlot.slotStart,
        durationMinutes,
        reasonForVisit: `Waitlist match — ${entry.requestedAppointmentType}`,
      });
      if (created.status !== 'ok' || !created.data) {
        setError(created.error?.title ?? 'Failed to create the appointment.');
        return;
      }
      const matched = await matchWaitlistEntry(entry.waitlistId, created.data.appointmentId);
      if (matched.status !== 'ok') {
        setError(matched.error?.title ?? 'Appointment created but matching failed.');
        return;
      }
      onMatched();
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to match the waitlist entry.');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <DialogComponent
      header={`Match slot — ${entry.patientName}`}
      visible
      width="480px"
      isModal
      showCloseIcon
      close={onClose}
      target="#root"
    >
      <div style={{ padding: '4px 2px' }}>
        <div style={{ fontSize: 12, color: 'var(--color-sf-fg-tertiary)', marginBottom: 14 }}>
          {entry.requestedAppointmentType} • {entry.preferredDepartmentName} • preferred{' '}
          {fmtDate(entry.preferredDateRangeStart)} – {fmtDate(entry.preferredDateRangeEnd)}
        </div>

        <div style={{ display: 'flex', gap: 12, alignItems: 'flex-end', marginBottom: 14 }}>
          <div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: 4 }}>
            <label style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-sf-fg-secondary)' }}>Provider</label>
            <DropDownListComponent
              dataSource={providers as any}
              fields={{ text: 'displayName', value: 'providerId' }}
              value={providerId}
              placeholder="Select provider"
              sortOrder="Ascending"
              change={(e: any) => setProviderId((e.value as string) ?? '')}
              itemTemplate={(p: ProviderOption) => (
                <span>
                  {p.displayName} — {p.specialty}
                </span>
              )}
            />
          </div>
          <div style={{ width: 150, display: 'flex', flexDirection: 'column', gap: 4 }}>
            <label style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-sf-fg-secondary)' }}>Date</label>
            <DatePickerComponent
              value={date}
              format="MM/dd/yyyy"
              min={toDateOnly(entry.preferredDateRangeStart)}
              max={toDateOnly(entry.preferredDateRangeEnd)}
              change={(e: any) => e.value && setDate(e.value as Date)}
            />
          </div>
          <ButtonComponent cssClass="e-primary" onClick={findSlots} disabled={finding}>
            {finding ? 'Finding…' : 'Find slots'}
          </ButtonComponent>
        </div>

        {error && (
          <div style={{ marginBottom: 12 }}>
            <ErrorBanner message={error} />
          </div>
        )}

        <div style={{ maxHeight: 220, overflow: 'auto' }}>
          {finding ? (
            <LoadingState inline label="Loading available slots…" />
          ) : slots.length === 0 ? (
            <div style={{ textAlign: 'center', color: 'var(--color-sf-fg-quinary)', padding: 24, fontSize: 13 }}>
              No available slots for this provider and date. Try another date.
            </div>
          ) : (
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8 }}>
              {slots.map((s) => {
                const selected = selectedSlot?.slotStart === s.slotStart;
                return (
                  <button
                    key={s.slotStart}
                    onClick={() => setSelectedSlot(s)}
                    style={{
                      padding: '8px 6px',
                      borderRadius: 6,
                      border: selected ? '2px solid var(--color-sf-border-brand-solid)' : '1px solid var(--color-sf-border-secondary)',
                      background: selected ? 'var(--color-sf-bg-brand-primary)' : 'var(--color-sf-bg-primary)',
                      color: selected ? 'var(--color-sf-fg-brand-primary)' : 'var(--color-sf-fg-secondary)',
                      fontSize: 12,
                      fontWeight: 600,
                      cursor: 'pointer',
                    }}
                  >
                    {formatTime(s.slotStart)}
                  </button>
                );
              })}
            </div>
          )}
        </div>

        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8, marginTop: 18 }}>
          <ButtonComponent cssClass="e-outline" onClick={onClose} disabled={submitting}>
            Cancel
          </ButtonComponent>
          <ButtonComponent cssClass="e-success" onClick={confirmMatch} disabled={!selectedSlot || submitting}>
            {submitting ? 'Matching…' : selectedSlot ? `Confirm ${formatTime(selectedSlot.slotStart)}` : 'Confirm match'}
          </ButtonComponent>
        </div>
      </div>
    </DialogComponent>
  );
};

// Angular/src/app/pages/waitlist/slot-match-dialog.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy, signal, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { map } from 'rxjs';
import { DialogModule } from '@syncfusion/ej2-angular-popups';
import { DropDownListModule } from '@syncfusion/ej2-angular-dropdowns';
import { DatePickerModule } from '@syncfusion/ej2-angular-calendars';
import { ButtonModule } from '@syncfusion/ej2-angular-buttons';
import { HealthcareService } from '../../core/api/healthcare.service';
import { okOrThrow } from '../../core/api/api.service';
import { ErrorBannerComponent } from '../../shared/error-banner/error-banner.component';
import { EmptyStateComponent } from '../../shared/empty-state/empty-state.component';
import { fmtTime } from '../../core/utils/date-format';
import type { WaitlistEntryDto, SlotDto, ProviderSummaryDto } from '../../core/models/dtos';

function toDateOnly(value: string): Date {
  const d = new Date(value);
  return isNaN(d.getTime()) ? new Date() : d;
}

function formatTime(value: string): string {
  return fmtTime(value);
}

function toLocalDateOnly(value: Date): string {
  const year = value.getFullYear();
  const month = `${value.getMonth() + 1}`.padStart(2, '0');
  const day = `${value.getDate()}`.padStart(2, '0');
  return `${year}-${month}-${day}`;
}

@Component({
  selector: 'app-slot-match-dialog',
  standalone: true,
  imports: [CommonModule, DialogModule, DropDownListModule, DatePickerModule, ButtonModule, ErrorBannerComponent, EmptyStateComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './slot-match-dialog.component.html',
  styleUrl: './slot-match-dialog.component.scss',
})
export class SlotMatchDialogComponent implements OnInit {
  private healthcare: HealthcareService;
  @Input({ required: true }) entry!: WaitlistEntryDto;
  @Output() close = new EventEmitter<void>();
  @Output() matched = new EventEmitter<void>();

  readonly providers = signal<ProviderSummaryDto[]>([]);
  readonly providerId = signal<string>('');
  readonly date = signal<Date>(new Date());
  readonly slots = signal<SlotDto[]>([]);
  readonly selectedSlot = signal<SlotDto | null>(null);
  readonly finding = signal(false);
  readonly submitting = signal(false);
  readonly error = signal<string | null>(null);

  readonly providerFields = { text: 'lastName', value: 'providerId' };

  constructor(healthcare: HealthcareService) {
    this.healthcare = healthcare;
  }

  ngOnInit(): void {
    this.date.set(toDateOnly(this.entry.preferredDateRangeStart));
    this.healthcare
      .listProviders(this.entry.preferredDepartmentId)
      .pipe(map((res) => okOrThrow(res).items))
      .subscribe({
        next: (list) => {
          this.providers.set(list);
          if (!this.entry.preferredProviderId && list.length > 0) {
            this.providerId.set(list[0].providerId);
          } else if (this.entry.preferredProviderId) {
            this.providerId.set(this.entry.preferredProviderId);
          }
        },
        error: () => undefined,
      });
  }

  onProviderChange(value: string | null): void {
    this.providerId.set(value ?? '');
  }

  onDateChange(value: Date | string | null): void {
    if (value) this.date.set(new Date(value));
  }

  findSlots(): void {
    if (!this.providerId()) {
      this.error.set('Select a provider first.');
      return;
    }
    this.finding.set(true);
    this.error.set(null);
    this.selectedSlot.set(null);
    const iso = toLocalDateOnly(this.date());
    this.healthcare
      .getProviderAvailability(this.providerId(), iso)
      .pipe(map((res) => okOrThrow(res).filter((s) => s.isAvailable)))
      .subscribe({
        next: (available) => {
          this.slots.set(available);
          this.finding.set(false);
        },
        error: (err: unknown) => {
          this.error.set(err instanceof Error ? err.message : 'Could not load availability.');
          this.slots.set([]);
          this.finding.set(false);
        },
      });
  }

  selectSlot(s: SlotDto): void {
    this.selectedSlot.set(s);
  }

  confirmMatch(): void {
    const slot = this.selectedSlot();
    if (!slot) return;
    this.submitting.set(true);
    this.error.set(null);
    const durationMinutes = Math.max(
      15,
      Math.round((new Date(slot.slotEnd).getTime() - new Date(slot.slotStart).getTime()) / 60000)
    );
    this.healthcare
      .createAppointment({
        patientId: this.entry.patientId,
        providerId: slot.providerId,
        departmentId: this.entry.preferredDepartmentId,
        locationId: slot.locationId,
        appointmentType: this.entry.requestedAppointmentType,
        scheduledDateTime: slot.slotStart,
        durationMinutes,
        reasonForVisit: `Waitlist match — ${this.entry.requestedAppointmentType}`,
      })
      .pipe(map((res) => okOrThrow(res)))
      .subscribe({
        next: (created) => {
          this.healthcare
            .matchWaitlistEntry(this.entry.waitlistId, created.appointmentId)
            .pipe(map((res) => okOrThrow(res)))
            .subscribe({
              next: () => {
                this.submitting.set(false);
                this.matched.emit();
              },
              error: (err: unknown) => {
                this.error.set(err instanceof Error ? err.message : 'Appointment created but matching failed.');
                this.submitting.set(false);
              },
            });
        },
        error: (err: unknown) => {
          this.error.set(err instanceof Error ? err.message : 'Failed to create the appointment.');
          this.submitting.set(false);
        },
      });
  }

  get minDate(): Date {
    return toDateOnly(this.entry.preferredDateRangeStart);
  }

  get maxDate(): Date {
    return toDateOnly(this.entry.preferredDateRangeEnd);
  }

  formatTime = formatTime;
}

<ejs-dialog
  header="Match slot — {{ entry.patientName }}"
  [visible]="true"
  width="480px"
  [isModal]="true"
  [showCloseIcon]="true"
  (close)="close.emit()"
  target=".waitlist-root">
  <div class="dialog-body">
    <div class="dialog-summary">
      {{ entry.requestedAppointmentType }} • {{ entry.preferredDepartmentName }} • preferred
      {{ minDate | date: 'mediumDate' }} – {{ maxDate | date: 'mediumDate' }}
    </div>

    <div class="controls">
      <div class="control-field control-field--grow">
        <label class="control-label">Provider</label>
        <ejs-dropdownlist
          [dataSource]="providers()"
          [fields]="providerFields"
          [value]="providerId()"
          [sortOrder]="'Ascending'"
          placeholder="Select provider"
          (change)="onProviderChange($event.value)">
        </ejs-dropdownlist>
      </div>
      <div class="control-field control-field--date">
        <label class="control-label">Date</label>
        <ejs-datepicker
          [value]="date()"
          [min]="minDate"
          [max]="maxDate"
          (change)="onDateChange($event.value)">
        </ejs-datepicker>
      </div>
      <div class="control-action">
        <button ejs-button cssClass="e-primary" [disabled]="finding()" (click)="findSlots()">
          {{ finding() ? 'Finding…' : 'Find slots' }}
        </button>
      </div>
    </div>

    @if (error(); as err) {
      <div class="dialog-error">
        <app-error-banner [message]="err"></app-error-banner>
      </div>
    }

    <div class="slot-area">
      @if (finding()) {
        <app-empty-state title="Loading…" description="Loading available slots…"></app-empty-state>
      } @else if (slots().length === 0) {
        <div class="no-slots">No available slots for this provider and date. Try another date.</div>
      } @else {
        <div class="slot-grid">
          @for (s of slots(); track s.slotStart) {
            <button
              type="button"
              class="slot"
              [class.slot--selected]="selectedSlot()?.slotStart === s.slotStart"
              (click)="selectSlot(s)">
              {{ formatTime(s.slotStart) }}
            </button>
          }
        </div>
      }
    </div>

    <div class="dialog-footer">
      <button ejs-button cssClass="e-outline" [disabled]="submitting()" (click)="close.emit()">Cancel</button>
      <button ejs-button cssClass="e-success" [disabled]="!selectedSlot() || submitting()" (click)="confirmMatch()">
        {{ submitting() ? 'Matching…' : (selectedSlot() ? 'Confirm ' + formatTime(selectedSlot()!.slotStart) : 'Confirm match') }}
      </button>
    </div>
  </div>
</ejs-dialog>
