// React/src/pages/ReportsPage.tsx
import React, { useEffect, useMemo, useRef, useState } from 'react';
import {
  ChartComponent,
  SeriesCollectionDirective,
  SeriesDirective,
  Inject,
  LineSeries,
  Category,
  Legend,
  Tooltip,
  DataLabel,
  StepLineSeries,
  PieSeries,
  BulletChartComponent,
  BulletRangeCollectionDirective,
  BulletRangeDirective,
  BulletTooltip,
  AccumulationChartComponent,
  AccumulationSeriesCollectionDirective,
  AccumulationSeriesDirective,
  AccumulationLegend,
  AccumulationTooltip,
  AccumulationDataLabel,
} from '@syncfusion/ej2-react-charts';
import { DateRangePickerComponent, ChangeEventArgs as DateRangeChangeArgs } from '@syncfusion/ej2-react-calendars';
import { DropDownListComponent, ChangeEventArgs as DropDownChangeArgs } from '@syncfusion/ej2-react-dropdowns';
import { ButtonComponent } from '@syncfusion/ej2-react-buttons';
import { useAsyncResult } from '@hooks/useAsyncResult';
import { useDebounce } from '@hooks/useDebounce';
import { getAppointmentVolume, getNoShowTrends, getProviderUtilization, getCancellationReasons, listDepartments } from '@services/healthcare.service';
import { withDepartmentLabel } from '../utils/department';
import { ErrorBanner } from '@components/shared/ErrorBanner';
import { EmptyState } from '@components/shared/EmptyState';
import {
  APPOINTMENT_TYPE_SERIES,
  SERIES_ROSE,
  CATEGORY_RAMP,
  CHART_FONT_FAMILY,
  buildValueAxis,
  chartFillHeight,
  chartLegendSettings,
  accumulationLegendSettings,
  chartInteraction,
  chartThemeName,
  COLUMN_STYLE,
  Highlight,
  Selection,
} from '../utils/chartTheme';
import { useTheme } from '../theme/ThemeProvider';

const UTILIZATION_TARGET = 85;
const RANGE_LOW = 'var(--color-sf-error-100)';
const RANGE_MID = 'var(--color-sf-warning-100)';
const RANGE_HIGH = 'var(--color-sf-success-100)';

export const ReportsPage: React.FC = () => {
  const { resolved } = useTheme();
  const chartTheme = chartThemeName(resolved);
  const toYmd = (d: Date): string => d.toISOString().split('T')[0];
  const [lastQuarterStart, lastQuarterEnd] = useMemo(() => {
    const today = new Date();
    const startOfQuarter = new Date(today.getFullYear(), Math.floor(today.getMonth() / 3) * 3, 1);
    const startOfPrevQuarter = new Date(today.getFullYear(), Math.floor(today.getMonth() / 3) * 3 - 3, 1);
    const endOfPrevQuarter = new Date(startOfQuarter.getTime() - 86400000);
    return [startOfPrevQuarter, endOfPrevQuarter];
  }, []);
  const [startDate, setStartDate] = useState<string>(toYmd(lastQuarterStart));
  const [endDate, setEndDate] = useState<string>(toYmd(lastQuarterEnd));
  const [departmentFilter, setDepartmentFilter] = useState<string>('');
  const deptDdlRef = useRef<DropDownListComponent>(null);

  const filtersReady = Boolean(startDate && endDate && departmentFilter);

  const utilChartRef = useRef<HTMLDivElement>(null);
  const [utilHeightRaw, setUtilHeightRaw] = useState(0);
  const utilHeight = useDebounce(utilHeightRaw, 150);
  useEffect(() => {
    const el = utilChartRef.current;
    if (!el) return;
    const update = () => setUtilHeightRaw(el.clientHeight);
    update();
    const ro = new ResizeObserver(update);
    ro.observe(el);
    return () => ro.disconnect();
  }, [filtersReady]);

  const rangePresets = useMemo(() => {
    const today = new Date();
    const startOfDay = new Date(today.getFullYear(), today.getMonth(), today.getDate());
    const startOfMonth = new Date(today.getFullYear(), today.getMonth(), 1);
    const startOfPrevMonth = new Date(today.getFullYear(), today.getMonth() - 1, 1);
    const endOfPrevMonth = new Date(today.getFullYear(), today.getMonth(), 0);
    const startOfQuarter = new Date(today.getFullYear(), Math.floor(today.getMonth() / 3) * 3, 1);
    const startOfPrevQuarter = new Date(today.getFullYear(), Math.floor(today.getMonth() / 3) * 3 - 3, 1);
    const endOfPrevQuarter = new Date(startOfQuarter.getTime() - 86400000);
    return [
      { label: 'Last 7 days', start: new Date(startOfDay.getTime() - 6 * 86400000), end: startOfDay },
      { label: 'Last 30 days', start: new Date(startOfDay.getTime() - 29 * 86400000), end: startOfDay },
      { label: 'MTD', start: startOfMonth, end: startOfDay },
      { label: 'QTD', start: startOfQuarter, end: startOfDay },
      { label: 'This Month', start: startOfMonth, end: startOfDay },
      { label: 'Last Month', start: startOfPrevMonth, end: endOfPrevMonth },
      { label: 'Last Quarter', start: startOfPrevQuarter, end: endOfPrevQuarter },
    ];
  }, []);

  const departmentsQuery = useAsyncResult(() => listDepartments(), []);
  const departmentList = departmentsQuery.data?.data ?? [];
  const firstDepartmentId = departmentList[0]?.departmentId ?? '';
  const didAutoSelect = useRef(false);
  useEffect(() => {
    if (!didAutoSelect.current && firstDepartmentId && !departmentFilter) {
      didAutoSelect.current = true;
      setDepartmentFilter(firstDepartmentId);
      const ddl = deptDdlRef.current;
      if (ddl) {
        ddl.value = firstDepartmentId;
        ddl.dataBind();
      }
    }
  }, [firstDepartmentId, departmentFilter]);
  const volumeQuery = useAsyncResult(() => getAppointmentVolume(startDate, endDate), [startDate, endDate, departmentFilter], { immediate: filtersReady });
  const noShowQuery = useAsyncResult(() => getNoShowTrends(startDate, endDate, departmentFilter || undefined), [startDate, endDate, departmentFilter], { immediate: filtersReady });
  const utilizationQuery = useAsyncResult(() => getProviderUtilization(startDate, endDate, undefined, departmentFilter || undefined), [startDate, endDate, departmentFilter], { immediate: filtersReady });
  const cancellationQuery = useAsyncResult(() => getCancellationReasons(startDate, endDate, departmentFilter || undefined), [startDate, endDate, departmentFilter], { immediate: filtersReady });

  const volumeData = useMemo(() => {
    const data = volumeQuery.data?.data ?? [];
    type VolumeRow = { period: string } & Record<string, number | string>;
    const grouped: Record<string, VolumeRow> = {};
    data
      .filter((d) => !departmentFilter || d.departmentId === departmentFilter)
      .forEach((d) => {
        let row = grouped[d.period];
        if (!row) {
          row = { period: d.period };
          APPOINTMENT_TYPE_SERIES.forEach((s) => (row[s.type] = 0));
          grouped[d.period] = row;
        }
        if (d.appointmentType in row) row[d.appointmentType] = (row[d.appointmentType] as number) + d.count;
      });

    return Object.values(grouped).sort((a, b) => a.period.localeCompare(b.period));
  }, [volumeQuery.data, departmentFilter]);

  const noShowData = useMemo(() => {
    const data = noShowQuery.data?.data ?? [];
    const grouped: Record<string, { period: string; rate: number }> = {};
    data.forEach((d) => {
      grouped[d.period] = { period: d.period, rate: d.noShowRate * 100 };
    });
    
    return Object.values(grouped).sort((a, b) => a.period.localeCompare(b.period));
  }, [noShowQuery.data]);

  const utilizationData = useMemo(() => {
    const rows = utilizationQuery.data?.data ?? [];
    const byProvider: Record<string, { providerName: string; appts: number; slots: number }> = {};
    rows.forEach((d) => {
      if (!byProvider[d.providerId]) byProvider[d.providerId] = { providerName: d.providerName, appts: 0, slots: 0 };
      byProvider[d.providerId].appts += d.appointmentCount;
      byProvider[d.providerId].slots += d.totalSlots;
    });
    return Object.values(byProvider)
      .map((p) => ({
        category: p.providerName.split(',')[0].trim(),
        value: p.slots ? Math.round((p.appts / p.slots) * 100) : 0,
      }))
      .sort((a, b) => b.value - a.value)
      .map((row, i) => ({
        ...row,
        target: UTILIZATION_TARGET,
        color: CATEGORY_RAMP[i % CATEGORY_RAMP.length],
      }));
  }, [utilizationQuery.data]);

  const cancellationData = useMemo(
    () => (cancellationQuery.data?.data ?? []).map((d, i) => ({ ...d, color: CATEGORY_RAMP[i % CATEGORY_RAMP.length] })),
    [cancellationQuery.data]
  );

  const totalCancellations = useMemo(
    () => cancellationData.reduce((sum, d) => sum + (d.count ?? 0), 0),
    [cancellationData]
  );

  const cardSurface: React.CSSProperties = {
    background: 'var(--color-sf-bg-primary)',
    borderRadius: 'var(--radius-12)',
    border: '1px solid var(--color-sf-border-secondary)',
    boxShadow: 'var(--shadow-sm)',
    padding: 20,
  };
  const sectionTitle: React.CSSProperties = {
    fontWeight: 600,
    fontSize: 14,
    color: 'var(--color-sf-fg-primary)',
    marginBottom: 16,
  };

  return (
    <div>
      {(volumeQuery.error || noShowQuery.error || utilizationQuery.error || cancellationQuery.error) && (
        <ErrorBanner message="Failed to load analytics data" onRetry={() => { volumeQuery.refresh(); noShowQuery.refresh(); utilizationQuery.refresh(); cancellationQuery.refresh(); }} />
      )}

      <div className="responsive-page-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 16 }}>
        <div id="filters" style={{ gridColumn: 'span 4', display: 'flex', gap: 16, alignItems: 'flex-end', flexWrap: 'wrap', ...cardSurface }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 4, width: 280 }}>
            <label style={{ fontSize: 12, fontWeight: 600, color: 'var(--color-sf-fg-secondary)' }}>Date Range</label>
            <DateRangePickerComponent
              placeholder="Select a date range"
              startDate={startDate ? new Date(startDate) : undefined}
              endDate={endDate ? new Date(endDate) : undefined}
              format="MM/dd/yyyy"
              width="280px"
              showClearButton
              presets={rangePresets}
              change={(e: DateRangeChangeArgs) => {
                const [s, en] = (e.value as unknown as (Date | null)[]) ?? [];
                setStartDate(s ? toYmd(new Date(s)) : '');
                setEndDate(en ? toYmd(new Date(en)) : '');
              }}
            />
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 4, width: 220 }}>
            <label style={{ fontSize: 12, fontWeight: 600, color: 'var(--color-sf-fg-secondary)' }}>Department</label>
            <DropDownListComponent
              ref={deptDdlRef}
              cssClass="dept-group-ddl"
              dataSource={withDepartmentLabel(departmentsQuery.data?.data ?? []) as any}
              fields={{ text: 'departmentName', value: 'departmentId', groupBy: 'locationName' }}
              placeholder="All Departments"
              change={(e: DropDownChangeArgs) => setDepartmentFilter((e.value as string) ?? '')}
              value={departmentFilter}
              allowFiltering
              showClearButton
              width="220px"
              sortOrder='Ascending'
            />
          </div>
          <ButtonComponent cssClass="e-outline" onClick={() => { setStartDate(''); setEndDate(''); setDepartmentFilter(''); }}>
            Reset
          </ButtonComponent>
        </div>

        {!filtersReady ? (
          <div style={{ gridColumn: 'span 4', ...cardSurface }}>
            <EmptyState title="Select filters" description="Choose a start date, end date, and department to view the analytics reports. Use Reset to clear your selection." />
          </div>
        ) : (
        <>
        <div id="volume" style={{ gridColumn: 'span 2', minWidth: 0, ...cardSurface }}>
          <div style={sectionTitle}>Appointment Volume Trend</div>
          <div style={{ height: chartFillHeight({ rows: 2, reserve: 300 }) }}>
          <ChartComponent theme={chartTheme} primaryXAxis={{ valueType: 'Category', title: 'Period' }} primaryYAxis={{ title: 'Count' }} legendSettings={chartLegendSettings} height="100%" tooltip={{ enable: true }}>
            <Inject services={[LineSeries, Category, Legend, Tooltip, DataLabel]} />
            <SeriesCollectionDirective>
              {APPOINTMENT_TYPE_SERIES.map((s) => (
                <SeriesDirective
                  key={s.type}
                  dataSource={volumeData}
                  xName="period"
                  yName={s.type}
                  name={s.type}
                  type="Line"
                  fill={s.color}
                  width={2}
                  marker={{ visible: true, width: 7, height: 7, fill: s.color }}
                />
              ))}
            </SeriesCollectionDirective>
          </ChartComponent>
          </div>
        </div>

        <div id="noshow" style={{ gridColumn: 'span 2', minWidth: 0, ...cardSurface }}>
          <div style={sectionTitle}>No-Show Rate Trend</div>
          <div style={{ height: chartFillHeight({ rows: 2, reserve: 300 }) }}>
          <ChartComponent
            theme={chartTheme}
            primaryXAxis={{ valueType: 'Category', title: 'Period' }}
            primaryYAxis={buildValueAxis(noShowData.map((d) => d.rate), { title: 'No-Show %', labelFormat: '{value}%' })}
            legendSettings={{ visible: false }}
            height="100%"
            tooltip={{ enable: true }}
            {...chartInteraction}
          >
            <Inject services={[StepLineSeries, Category, Legend, Tooltip, DataLabel, Highlight, Selection]} />
            <SeriesCollectionDirective>
              <SeriesDirective
                dataSource={noShowData}
                xName="period"
                yName="rate"
                name="No-Show %"
                type="StepLine"
                fill={SERIES_ROSE}
                width={2.5}
                marker={{ visible: true, width: 7, height: 7, fill: SERIES_ROSE, shape: 'Circle' }}
              />
            </SeriesCollectionDirective>
          </ChartComponent>
          </div>
        </div>

        <div id="utilization" style={{ gridColumn: 'span 2', minWidth: 0, ...cardSurface }}>
          <div style={sectionTitle}>{`Provider Utilization (% vs ${UTILIZATION_TARGET}% goal)`}</div>
          <div ref={utilChartRef} style={{ height: chartFillHeight({ rows: 2, reserve: 300 }) }}>
          <BulletChartComponent
            key={`util-${departmentFilter}-${utilizationData.map((d) => d.category).join('|')}-${Math.round(utilHeight)}`}
            id="provider-utilization"
            theme={chartTheme}
            dataSource={utilizationData}
            valueField="value"
            targetField="target"
            categoryField="category"
            valueFill="color"
            valueHeight={18}
            type="Rect"
            targetTypes={['Rect']}
            targetWidth={5}
            targetColor="var(--color-sf-fg-primary)"
            minimum={0}
            maximum={100}
            interval={20}
            height={utilHeight ? `${Math.round(utilHeight)}px` : '100%'}
            animation={{ enable: true, duration: 800 }}
            tooltip={{ enable: true }}
            dataLabel={{
              enable: true,
              labelStyle: { size: '11px', fontFamily: CHART_FONT_FAMILY, fontWeight: '600', color: 'var(--color-sf-fg-secondary)' },
            }}
            labelFormat="{value}%"
            margin={{ left: 110, right: 40, top: 16, bottom: 16 }}
            categoryLabelStyle={{ size: '12px', fontFamily: CHART_FONT_FAMILY, fontWeight: '600', color: 'var(--color-sf-fg-primary)' }}
            labelStyle={{ size: '10px', fontFamily: CHART_FONT_FAMILY, color: 'var(--color-sf-fg-secondary)' }}
            legendSettings={{ visible: false }}
          >
            <Inject services={[BulletTooltip]} />
            <BulletRangeCollectionDirective>
              <BulletRangeDirective end={70} color={RANGE_LOW} opacity={0.6} />
              <BulletRangeDirective end={85} color={RANGE_MID} opacity={0.6} />
              <BulletRangeDirective end={100} color={RANGE_HIGH} opacity={0.6} />
            </BulletRangeCollectionDirective>
          </BulletChartComponent>
          </div>
        </div>

        <div id="cancellation" style={{ gridColumn: 'span 2', minWidth: 0, ...cardSurface }}>
          <div style={sectionTitle}>Cancellation Reasons</div>
          <div style={{ height: chartFillHeight({ rows: 2, reserve: 300 }) }}>
          <AccumulationChartComponent
            theme={chartTheme}
            height="100%"
            tooltip={{ enable: true }}
            legendSettings={{ ...accumulationLegendSettings, position: 'Bottom' }}
            margin={{ top: 16, bottom: 16, left: 16, right: 16 }}
            centerLabel={{
              text: `${totalCancellations}`,
              textStyle: {
                fontFamily: CHART_FONT_FAMILY,
                size: '18px',
                fontWeight: '700',
                color: 'var(--color-sf-fg-primary)',
              },
            }}
          >
            <Inject services={[PieSeries, AccumulationLegend, AccumulationTooltip, AccumulationDataLabel]} />
            <AccumulationSeriesCollectionDirective>
              <AccumulationSeriesDirective
                dataSource={cancellationData}
                xName="reason"
                yName="count"
                name="Cancellations"
                type="Pie"
                innerRadius="60%"
                startAngle={0}
                endAngle={360}
                explode
                explodeOffset="8px"
                pointColorMapping="color"
                dataLabel={{ visible: true, name: 'reason', position: 'Outside', font: { fontFamily: CHART_FONT_FAMILY, size: '12px' } }}
              />
            </AccumulationSeriesCollectionDirective>
          </AccumulationChartComponent>
          </div>
        </div>
        </>
        )}
      </div>
    </div>
  );
};

// Angular/src/app/pages/reports/reports-page.component.ts
import { Component, inject, computed, signal, effect, ChangeDetectionStrategy, ViewChild, AfterViewInit, OnDestroy, NgZone, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { map, of } from 'rxjs';
import {
  ChartModule,
  AccumulationChartModule,
  CategoryService,
  LineSeriesService,
  ColumnSeriesService,
  StepLineSeriesService,
  PieSeriesService,
  StackingColumnSeriesService,
  BulletChartModule,
  BulletTooltipService,
  LegendService,
  TooltipService,
  DataLabelService,
  HighlightService,
  SelectionService,
  AccumulationLegendService,
  AccumulationTooltipService,
  AccumulationDataLabelService,
} from '@syncfusion/ej2-angular-charts';
import { DateRangePickerModule } from '@syncfusion/ej2-angular-calendars';
import { DropDownListModule, DropDownListComponent } from '@syncfusion/ej2-angular-dropdowns';
import { ButtonModule } from '@syncfusion/ej2-angular-buttons';
import { HealthcareService } from '../../core/api/healthcare.service';
import { okOrThrow } from '../../core/api/api.service';
import { createAsyncResult } from '../../core/async/async-result';
import { ErrorBannerComponent } from '../../shared/error-banner/error-banner.component';
import { EmptyStateComponent } from '../../shared/empty-state/empty-state.component';
import {
  APPOINTMENT_TYPE_SERIES,
  SERIES_ROSE,
  CATEGORY_RAMP,
  CHART_FONT_FAMILY,
  buildValueAxis,
  chartFillHeight,
  CHART_LEGEND_SETTINGS,
  ACCUMULATION_LEGEND_SETTINGS,
  HIDDEN_LEGEND_SETTINGS,
  COLUMN_WIDTH,
  COLUMN_CORNER_RADIUS,
  CHART_SELECTION_MODE,
  CHART_HIGHLIGHT_MODE,
  chartThemeName,
} from '../../core/utils/chart-theme';
import { ThemeService } from '../../core/theme/theme.service';
import type {
  VolumeDataPointDto,
  NoShowTrendDto,
  UtilizationDataPointDto,
  CancellationReasonDto,
  DepartmentDto,
} from '../../core/models/dtos';

interface VolumeRow {
  period: string;
  [type: string]: number | string;
}

interface NoShowRow {
  period: string;
  rate: number;
}

interface UtilizationRow {
  category: string;
  value: number;
  target: number;
  color: string;
}

interface CancellationRow extends CancellationReasonDto {
  color: string;
}

const UTILIZATION_TARGET = 85;
const RANGE_LOW = 'var(--color-sf-error-100)';
const RANGE_MID = 'var(--color-sf-warning-100)';
const RANGE_HIGH = 'var(--color-sf-success-100)';

function toYmd(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

@Component({
  selector: 'app-reports-page',
  standalone: true,
  imports: [
    CommonModule,
    ChartModule,
    AccumulationChartModule,
    BulletChartModule,
    DateRangePickerModule,
    DropDownListModule,
    ButtonModule,
    ErrorBannerComponent,
    EmptyStateComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './reports-page.component.html',
  styleUrl: './reports-page.component.scss',
  providers: [
    CategoryService,
    LineSeriesService,
    ColumnSeriesService,
    StepLineSeriesService,
    PieSeriesService,
    StackingColumnSeriesService,
    BulletTooltipService,
    LegendService,
    TooltipService,
    DataLabelService,
    HighlightService,
    SelectionService,
    AccumulationLegendService,
    AccumulationTooltipService,
    AccumulationDataLabelService,
  ],
})
export class ReportsPageComponent implements AfterViewInit, OnDestroy {
  private healthcare = inject(HealthcareService);
  private theme = inject(ThemeService);
  private zone = inject(NgZone);

  readonly chartTheme = computed(() => chartThemeName(this.theme.resolved()));
  readonly chartFillHeight = chartFillHeight;

  readonly bulletChartFillHeight = (
    opts: { rows?: number; reserve?: number; floor?: number; cap?: number } = {},
  ): string => chartFillHeight({ rows: opts.rows ?? 2, reserve: opts.reserve ?? 300, floor: opts.floor ?? 320, cap: opts.cap ?? 980 });

  readonly bulletChartContainerHeight = signal(0);

  readonly bulletChartHeight = computed(() => {
    const h = this.bulletChartContainerHeight();
    return h ? `${Math.round(h)}px` : '100%';
  });

 
  readonly bulletChartRenderKey = computed<string[]>(() => {
    if (this.bulletChartLayoutVersion() === 0) return [];
    const categories = this.utilizationData().map((d) => d.category).join('|');
    return [`util-${this.departmentFilter()}-${categories}-${this.bulletChartContainerHeight()}`];
  });

  readonly bulletChartLayoutVersion = signal(0);

  @ViewChild('bulletChartWrap', { read: ElementRef }) bulletChartWrap?: ElementRef<HTMLElement>;

  @ViewChild('deptDropDown') deptDropDown?: DropDownListComponent;

  readonly startDate = signal<string>('');
  readonly endDate = signal<string>('');
  readonly departmentFilter = signal<string>('');

  readonly filtersReady = computed(() => Boolean(this.startDate() && this.endDate() && this.departmentFilter()));

  private readonly departmentsState = createAsyncResult<DepartmentDto[]>(() =>
    this.healthcare.listDepartments().pipe(map((res) => okOrThrow(res)))
  );
  readonly departmentFields = { text: 'departmentName', value: 'departmentId', groupBy: 'locationName' };

  private readonly lastQuarterRange = (() => {
    const today = new Date();
    const startOfQuarter = new Date(today.getFullYear(), Math.floor(today.getMonth() / 3) * 3, 1);
    const startOfPrevQuarter = new Date(today.getFullYear(), Math.floor(today.getMonth() / 3) * 3 - 3, 1);
    const endOfPrevQuarter = new Date(startOfQuarter.getTime() - 86400000);
    return { start: startOfPrevQuarter, end: endOfPrevQuarter };
  })();

  readonly rangePresets = (() => {
    const today = new Date();
    const startOfDay = new Date(today.getFullYear(), today.getMonth(), today.getDate());
    const startOfMonth = new Date(today.getFullYear(), today.getMonth(), 1);
    const startOfPrevMonth = new Date(today.getFullYear(), today.getMonth() - 1, 1);
    const endOfPrevMonth = new Date(today.getFullYear(), today.getMonth(), 0);
    const startOfQuarter = new Date(today.getFullYear(), Math.floor(today.getMonth() / 3) * 3, 1);
    const startOfPrevQuarter = new Date(today.getFullYear(), Math.floor(today.getMonth() / 3) * 3 - 3, 1);
    const endOfPrevQuarter = new Date(startOfQuarter.getTime() - 86400000);
    return [
      { label: 'Last 7 days', start: new Date(startOfDay.getTime() - 6 * 86400000), end: startOfDay },
      { label: 'Last 30 days', start: new Date(startOfDay.getTime() - 29 * 86400000), end: startOfDay },
      { label: 'This Month', start: startOfMonth, end: startOfDay },
      { label: 'Last Month', start: startOfPrevMonth, end: endOfPrevMonth },
      { label: 'QTD', start: startOfQuarter, end: startOfDay },
      { label: 'Last Quarter', start: startOfPrevQuarter, end: endOfPrevQuarter },
    ];
  })();

  readonly departmentOptions = computed(() => this.departmentsState.data ?? []);

  private readonly autoSelectDone = signal(false);

  constructor() {
    this.startDate.set(toYmd(this.lastQuarterRange.start));
    this.endDate.set(toYmd(this.lastQuarterRange.end));

    effect(() => {
      const depts = this.departmentsState.data ?? [];
      if (this.autoSelectDone()) return;
      if (!depts.length) return;
      if (this.departmentFilter()) {
        this.autoSelectDone.set(true);
        this.syncDropDownValue(this.departmentFilter());
        return;
      }
      const first = depts[0].departmentId;
      this.departmentFilter.set(first);
      this.autoSelectDone.set(true);
      this.syncDropDownValue(first);
      this.applyFilters();
    });

    effect(() => {
      const value = this.departmentFilter();
      this.syncDropDownValue(value, this.autoSelectDone());
    });
  }

  private bulletResizeObserver?: ResizeObserver;

  private computeBulletHeightPx(): number {
    const vh = typeof window !== 'undefined' ? window.innerHeight : 900;
    const raw = (vh - 300) / 2; // rows: 2, reserve: 300 — matches bulletChartFillHeight
    return Math.round(Math.max(320, Math.min(980, raw))); // floor: 320, cap: 980
  }

  ngAfterViewInit(): void {
    const wrap = this.bulletChartWrap?.nativeElement;
    const measured = wrap?.clientHeight ?? 0;
    this.bulletChartContainerHeight.set(measured > 0 ? Math.round(measured) : this.computeBulletHeightPx());
    this.bulletChartLayoutVersion.set(1);
    if (typeof ResizeObserver !== 'undefined' && wrap) {
      this.bulletResizeObserver = new ResizeObserver((entries) => {
        const h = entries[0]?.contentRect?.height ?? 0;
        if (h && Math.abs(h - this.bulletChartContainerHeight()) > 2) {
          this.zone.run(() => {
            this.bulletChartContainerHeight.set(Math.round(h));
            this.bulletChartLayoutVersion.update((v) => v + 1);
          });
        }
      });
      this.bulletResizeObserver.observe(wrap);
    }
  }

  ngOnDestroy(): void {
    this.bulletResizeObserver?.disconnect();
  }

  private readonly volumeState = createAsyncResult<VolumeDataPointDto[] | undefined>(
    () =>
      this.filtersReady()
        ? this.healthcare
            .getAppointmentVolume(this.startDate(), this.endDate())
            .pipe(map((res) => okOrThrow(res)))
        : of(undefined),
    { immediate: false }
  );
  private readonly noShowState = createAsyncResult<NoShowTrendDto[] | undefined>(
    () =>
      this.filtersReady()
        ? this.healthcare
            .getNoShowTrends(this.startDate(), this.endDate(), this.departmentFilter() || undefined)
            .pipe(map((res) => okOrThrow(res)))
        : of(undefined),
    { immediate: false }
  );
  private readonly utilizationState = createAsyncResult<UtilizationDataPointDto[] | undefined>(
    () =>
      this.filtersReady()
        ? this.healthcare
            .getProviderUtilization(this.startDate(), this.endDate(), undefined, this.departmentFilter() || undefined)
            .pipe(map((res) => okOrThrow(res)))
        : of(undefined),
    { immediate: false }
  );
  private readonly cancellationState = createAsyncResult<CancellationReasonDto[] | undefined>(
    () =>
      this.filtersReady()
        ? this.healthcare
            .getCancellationReasons(this.startDate(), this.endDate(), this.departmentFilter() || undefined)
            .pipe(map((res) => okOrThrow(res)))
        : of(undefined),
    { immediate: false }
  );

  readonly volumeData = computed<VolumeRow[]>(() => {
    const data = this.volumeState.data ?? [];
    const grouped: Record<string, VolumeRow> = {};
    data
      .filter((d) => !this.departmentFilter() || d.departmentId === this.departmentFilter())
      .forEach((d) => {
        let row = grouped[d.period];
        if (!row) {
          row = { period: d.period };
          APPOINTMENT_TYPE_SERIES.forEach((s) => (row[s.type] = 0));
          grouped[d.period] = row;
        }
        if (d.appointmentType in row) {
          row[d.appointmentType] = (row[d.appointmentType] as number) + d.count;
        }
      });
    return Object.values(grouped).sort((a, b) => a.period.localeCompare(b.period));
  });

  readonly noShowData = computed<NoShowRow[]>(() =>
    (this.noShowState.data ?? [])
      .map((d) => ({ period: d.period, rate: d.noShowRate * 100 }))
      .sort((a, b) => a.period.localeCompare(b.period))
  );

  readonly utilizationData = computed<UtilizationRow[]>(() => {
    const rows = this.utilizationState.data ?? [];
    const byProvider: Record<string, { providerName: string; appts: number; slots: number }> = {};
    rows.forEach((d) => {
      if (!byProvider[d.providerId]) byProvider[d.providerId] = { providerName: d.providerName, appts: 0, slots: 0 };
      byProvider[d.providerId].appts += d.appointmentCount;
      byProvider[d.providerId].slots += d.totalSlots;
    });
    return Object.values(byProvider)
      .map((p) => ({
        category: p.providerName.split(',')[0].trim(),
        value: p.slots ? Math.round((p.appts / p.slots) * 100) : 0,
      }))
      .sort((a, b) => b.value - a.value)
      .map((row, i) => ({
        ...row,
        target: UTILIZATION_TARGET,
        color: CATEGORY_RAMP[i % CATEGORY_RAMP.length],
      }));
  });

  readonly totalCancellations = computed(() =>
    this.cancellationData().reduce((sum, d) => sum + (d.count ?? 0), 0)
  );

  readonly cancellationData = computed<CancellationRow[]>(() =>
    (this.cancellationState.data ?? []).map((d, i) => ({
      ...d,
      color: CATEGORY_RAMP[i % CATEGORY_RAMP.length],
    }))
  );

  readonly bannerError = computed(
    () =>
      this.volumeState.error ??
      this.noShowState.error ??
      this.utilizationState.error ??
      this.cancellationState.error ??
      null
  );

  readonly volumeLoading = computed(() => this.volumeState.loading);
  readonly noShowLoading = computed(() => this.noShowState.loading);
  readonly utilizationLoading = computed(() => this.utilizationState.loading);
  readonly cancellationLoading = computed(() => this.cancellationState.loading);

  readonly categoryXAxis = { valueType: 'Category', title: 'Period' };
  readonly volumeYAxis = { title: 'Count' };
  readonly noShowYAxis = computed(() =>
    buildValueAxis(this.noShowData().map((d) => d.rate), { title: 'No-Show %', labelFormat: '{value}%' })
  );

  readonly tooltip = { enable: true };
  readonly accumulationTooltip = { enable: true };
  readonly legendSettings = CHART_LEGEND_SETTINGS;
  readonly hiddenLegend = HIDDEN_LEGEND_SETTINGS;
  readonly accumulationLegendBottom = { ...ACCUMULATION_LEGEND_SETTINGS, position: 'Bottom' as const };
  readonly cancellationDataLabel = {
    visible: true,
    name: 'reason',
    position: 'Outside' as const,
    font: { fontFamily: CHART_FONT_FAMILY, size: '12px' },
  };
  readonly cancellationCenterLabel = computed(() => ({
    text: `${this.totalCancellations()}`,
    textStyle: {
      fontFamily: CHART_FONT_FAMILY,
      size: '18px',
      fontWeight: '700',
      color: 'var(--color-sf-fg-primary)',
    },
  }));
  readonly cancellationMargin = { top: 16, bottom: 16, left: 16, right: 16 };
  readonly selectionMode = CHART_SELECTION_MODE;
  readonly highlightMode = CHART_HIGHLIGHT_MODE;

  readonly seriesRose = SERIES_ROSE;

  readonly volumeSeries = APPOINTMENT_TYPE_SERIES.map((s) => ({
    type: s.type,
    color: s.color,
    marker: { visible: true, width: 7, height: 7, fill: s.color },
  }));
  readonly columnWidth = COLUMN_WIDTH;
  readonly columnCornerRadius = COLUMN_CORNER_RADIUS;

  readonly utilizationTarget = UTILIZATION_TARGET;
  readonly utilizationBulletRanges = [
    { end: 70, color: RANGE_LOW, opacity: 0.6 },
    { end: 85, color: RANGE_MID, opacity: 0.6 },
    { end: 100, color: RANGE_HIGH, opacity: 0.6 },
  ];
  readonly utilizationBulletDataLabel = {
    enable: true,
    labelStyle: { size: '11px', fontFamily: CHART_FONT_FAMILY, fontWeight: '600', color: 'var(--color-sf-fg-secondary)' },
  };
  readonly utilizationBulletCategoryLabelStyle = {
    size: '12px',
    fontFamily: CHART_FONT_FAMILY,
    fontWeight: '600',
    color: 'var(--color-sf-fg-primary)',
  };
  readonly utilizationBulletLabelStyle = {
    size: '10px',
    fontFamily: CHART_FONT_FAMILY,
    color: 'var(--color-sf-fg-secondary)',
  };
  readonly utilizationBulletMargin = { left: 110, right: 40, top: 16, bottom: 16 };

  toDate(value: string): Date {
    return new Date(value);
  }

  private syncDropDownValue(value: string, run = true): void {
    if (!run) return;
    const ddl = this.deptDropDown;
    if (!ddl) return;
    // Defer to next change detection so the view child is bound after the
    // initial render and after dataSource updates.
    Promise.resolve().then(() => {
      const inst = this.deptDropDown;
      if (!inst) return;
      inst.value = value ?? null;
      inst.dataBind();
    });
  }

  applyFilters(): void {
    if (this.filtersReady()) {
      this.volumeState.refresh();
      this.noShowState.refresh();
      this.utilizationState.refresh();
      this.cancellationState.refresh();
    }
  }

  onRangeChange(value: { startDate?: Date | string | null; endDate?: Date | string | null } | null): void {
    this.startDate.set(value?.startDate ? toYmd(new Date(value.startDate)) : '');
    this.endDate.set(value?.endDate ? toYmd(new Date(value.endDate)) : '');
    this.applyFilters();
  }

  onDepartmentChange(value: string | null): void {
    this.departmentFilter.set(value ?? '');
    this.applyFilters();
  }

  resetFilters(): void {
    this.startDate.set('');
    this.endDate.set('');
    this.departmentFilter.set('');
    this.autoSelectDone.set(false);
    // Clear the ej2 input text immediately; the auto-select effect will run
    // again once autoSelectDone is reset and re-fire dataBind().
    const ddl = this.deptDropDown;
    if (ddl) {
      ddl.value = null;
      ddl.dataBind();
    }
  }

  retryAll(): void {
    this.volumeState.refresh();
    this.noShowState.refresh();
    this.utilizationState.refresh();
    this.cancellationState.refresh();
  }
}

<div class="reports">
  @if (bannerError(); as err) {
    <app-error-banner title="Unable to load analytics data" [message]="err" (retry)="retryAll()"></app-error-banner>
  }

  <div class="grid">
    <section class="card filters">
      <div class="field field--range">
        <label class="field-label">Date Range</label>
        <ejs-daterangepicker
          placeholder="Select a date range"
          [locale]="'en-US'"
          [format]="'MMM d, yyyy'"
          width="280px"
          [showClearButton]="true"
          [presets]="rangePresets"
          [startDate]="startDate() ? toDate(startDate()) : null"
          [endDate]="endDate() ? toDate(endDate()) : null"
          (change)="onRangeChange($event)">
        </ejs-daterangepicker>
      </div>
      <div class="field field--wide">
        <label class="field-label">Department</label>
        <ejs-dropdownlist
          #deptDropDown
          cssClass="dept-group-ddl"
          [dataSource]="departmentOptions()"
          [fields]="departmentFields"
          placeholder="All Departments"
          [allowFiltering]="true"
          [showClearButton]="true"
          [sortOrder]="'Ascending'"
          [value]="departmentFilter()"
          width="220px"
          (change)="onDepartmentChange($event.value)">
        </ejs-dropdownlist>
      </div>
      <div class="field-actions">
        <button ejs-button cssClass="e-outline" (click)="resetFilters()">Reset</button>
      </div>
    </section>

    @if (!filtersReady()) {
      <section class="card card--full empty">
        <app-empty-state
          title="Select filters"
          description="Choose a start date, end date, and department to view the analytics reports. Use Reset to clear your selection.">
        </app-empty-state>
      </section>
    } @else {
      <section class="card chart-card">
        <h3 class="card-title">Appointment Volume Trend</h3>
        <div [style.height]="chartFillHeight({ rows: 2, reserve: 300 })">
          <ejs-chart
            [theme]="chartTheme()"
            [primaryXAxis]="categoryXAxis"
            [primaryYAxis]="volumeYAxis"
            [legendSettings]="legendSettings"
            [tooltip]="tooltip"
            height="100%">
            <e-series-collection>
              @for (s of volumeSeries; track s.type) {
                <e-series
                  type="Line"
                  [dataSource]="volumeData()"
                  xName="period"
                  [yName]="s.type"
                  [name]="s.type"
                  [fill]="s.color"
                  [width]="2"
                  [marker]="s.marker">
                </e-series>
              }
            </e-series-collection>
          </ejs-chart>
        </div>
      </section>

      <section class="card chart-card">
        <h3 class="card-title">No-Show Rate Trend</h3>
        <div [style.height]="chartFillHeight({ rows: 2, reserve: 300 })">
          <ejs-chart
            [theme]="chartTheme()"
            [primaryXAxis]="categoryXAxis"
            [primaryYAxis]="noShowYAxis()"
            [legendSettings]="hiddenLegend"
            [tooltip]="tooltip"
            [selectionMode]="selectionMode"
            [highlightMode]="highlightMode"
            height="100%">
            <e-series-collection>
              <e-series
                type="StepLine"
                [dataSource]="noShowData()"
                xName="period"
                yName="rate"
                name="No-Show %"
                [fill]="seriesRose"
                [width]="2.5"
                [marker]="{ visible: true, width: 7, height: 7, fill: seriesRose, shape: 'Circle' }">
              </e-series>
            </e-series-collection>
          </ejs-chart>
        </div>
      </section>

      <section class="card chart-card">
        <h3 class="card-title">{{ 'Provider Utilization (% vs ' + utilizationTarget + '% goal)' }}</h3>
        <div #bulletChartWrap class="bullet-chart-wrap" [style.height]="bulletChartFillHeight({ rows: 2, reserve: 300 })">
          @for (bulletKey of bulletChartRenderKey(); track bulletKey) {
            <ejs-bulletchart
              id="provider-utilization"
              [theme]="chartTheme()"
              [dataSource]="utilizationData()"
              valueField="value"
              targetField="target"
              categoryField="category"
              valueFill="color"
              [valueHeight]="18"
              type="Rect"
              [targetTypes]="['Rect']"
              [targetWidth]="5"
              targetColor="var(--color-sf-fg-primary)"
              [minimum]="0"
              [maximum]="100"
              [interval]="20"
              [tooltip]="tooltip"
              [dataLabel]="utilizationBulletDataLabel"
              labelFormat="{value}%"
              [margin]="utilizationBulletMargin"
              [categoryLabelStyle]="utilizationBulletCategoryLabelStyle"
              [labelStyle]="utilizationBulletLabelStyle"
              [legendSettings]="hiddenLegend"
              [animation]="{ enable: true, duration: 800 }"
              [height]="bulletChartHeight()">
              <e-bullet-range-collection>
                @for (range of utilizationBulletRanges; track range.end) {
                  <e-bullet-range [end]="range.end" [color]="range.color" [opacity]="range.opacity"></e-bullet-range>
                }
              </e-bullet-range-collection>
            </ejs-bulletchart>
          }
        </div>
      </section>

      <section class="card chart-card">
        <h3 class="card-title">Cancellation Reasons</h3>
        <div [style.height]="chartFillHeight({ rows: 2, reserve: 300 })">
          <ejs-accumulationchart
            [theme]="chartTheme()"
            height="100%"
            [tooltip]="accumulationTooltip"
            [legendSettings]="accumulationLegendBottom"
            [centerLabel]="cancellationCenterLabel()"
            [margin]="cancellationMargin">
            <e-accumulation-series-collection>
              <e-accumulation-series
                type="Pie"
                [dataSource]="cancellationData()"
                xName="reason"
                yName="count"
                name="Cancellations"
                innerRadius="60%"
                [startAngle]="0"
                [endAngle]="360"
                [explode]="true"
                explodeOffset="8px"
                [pointColorMapping]="'color'"
                [dataLabel]="cancellationDataLabel">
              </e-accumulation-series>
            </e-accumulation-series-collection>
          </ejs-accumulationchart>
        </div>
      </section>
    }
  </div>
</div>
