// React/src/components/shared/ErrorBanner.tsx
import React from 'react';
import { ButtonComponent } from '@syncfusion/ej2-react-buttons';

export interface ErrorBannerProps {
  title?: string;
  message: string;
  onRetry?: () => void;
}

export const ErrorBanner: React.FC<ErrorBannerProps> = ({ title = 'Something went wrong', message, onRetry }) => {
  return (
    <div
      style={{
        background: 'var(--color-sf-bg-error-primary)',
        border: '1px solid var(--color-sf-border-error)',
        borderRadius: 8,
        padding: 16,
        color: 'var(--color-sf-fg-error-primary)',
      }}
    >
      <div style={{ fontWeight: 700, marginBottom: 4 }}>{title}</div>
      <div style={{ fontSize: 14 }}>{message}</div>
      {onRetry && (
        <div style={{ marginTop: 12 }}>
          <ButtonComponent cssClass="e-danger e-outline" onClick={onRetry}>
            Retry
          </ButtonComponent>
        </div>
      )}
    </div>
  );
};

// Angular/src/app/shared/error-banner/error-banner.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { ButtonModule } from '@syncfusion/ej2-angular-buttons';

@Component({
  selector: 'app-error-banner',
  standalone: true,
  imports: [ButtonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="error-banner">
      <div class="error-title">{{ title }}</div>
      <div class="error-message">{{ message }}</div>
      @if (retry.observed) {
        <div class="error-actions">
          <button ejs-button cssClass="e-danger e-outline" (click)="retry.emit()">Retry</button>
        </div>
      }
    </div>
  `,
  styles: [`
    .error-banner {
      background: var(--color-sf-bg-error-primary);
      border: 1px solid var(--color-sf-border-error);
      border-radius: var(--radius-8);
      padding: 16px;
      color: var(--color-sf-fg-error-primary);
    }
    .error-title {
      font-weight: 700;
      margin-bottom: 4px;
    }
    .error-message {
      font-size: 14px;
    }
    .error-actions {
      margin-top: 12px;
    }
  `],
})
export class ErrorBannerComponent {
  @Input() title = 'Something went wrong';
  @Input({ required: true }) message!: string;
  @Output() retry = new EventEmitter<void>();
}
