// React/src/components/appointments/NewAppointmentDialog.tsx
import React, { useEffect, useMemo, useState } from 'react';
import {
  DialogComponent,
  ButtonPropsModel,
} from '@syncfusion/ej2-react-popups';
import {
  AutoCompleteComponent,
  DropDownListComponent,
  ChangeEventArgs as DropDownChangeArgs,
} from '@syncfusion/ej2-react-dropdowns';
import {
  DateTimePickerComponent,
  ChangeEventArgs as DateChangeArgs,
} from '@syncfusion/ej2-react-calendars';
import { TextBoxComponent } from '@syncfusion/ej2-react-inputs';
import type {
  PatientSummaryDto,
  ProviderSummaryDto,
  DepartmentDto,
  LocationDto,
  CreateAppointmentRequest,
} from '@models/dtos';
import { listPatients, listLocations, getAppointmentConflicts } from '@services/healthcare.service';
import { withDepartmentLabel } from '../../utils/department';
import { FormFieldError } from '@components/shared/FormFieldError';

export interface NewAppointmentDialogProps {
  visible: boolean;
  initialDateTime?: Date;
  initialProviderId?: string;
  providers: ProviderSummaryDto[];
  departments: DepartmentDto[];
  onClose: () => void;
  onSubmit: (req: CreateAppointmentRequest) => void;
  loading?: boolean;
}

type FieldName =
  | 'patient'
  | 'provider'
  | 'department'
  | 'location'
  | 'scheduledDateTime'
  | 'appointmentType'
  | 'reasonForVisit';

export const NewAppointmentDialog: React.FC<NewAppointmentDialogProps> = ({
  visible,
  initialDateTime,
  initialProviderId,
  providers,
  departments,
  onClose,
  onSubmit,
  loading,
}) => {
  const [patientId, setPatientId] = useState<string>('');
  const [patientData, setPatientData] = useState<(PatientSummaryDto & { display: string })[]>([]);
  const [patientLoading, setPatientLoading] = useState(false);
  const [providerId, setProviderId] = useState<string>(initialProviderId ?? '');
  const [departmentId, setDepartmentId] = useState<string>('');
  const [locationId, setLocationId] = useState<string>('');
  const [locations, setLocations] = useState<LocationDto[]>([]);
  const [appointmentType, setAppointmentType] = useState<string>('');
  const [scheduledDateTime, setScheduledDateTime] = useState<Date | null>(initialDateTime ?? null);
  const [durationMinutes, setDurationMinutes] = useState<number>(15);
  const [reasonForVisit, setReasonForVisit] = useState<string>('');
  const [notes, setNotes] = useState<string>('');
  const [errors, setErrors] = useState<Partial<Record<FieldName, string>>>({});
  const [conflictError, setConflictError] = useState<string>('');
  const [submitting, setSubmitting] = useState(false);

  const filteredProviders = useMemo(() => {
    if (!departmentId) return providers;
    return providers.filter((p) => p.departmentId === departmentId);
  }, [providers, departmentId]);

  const selectedDepartment = useMemo(
    () => departments.find((d) => d.departmentId === departmentId),
    [departments, departmentId]
  );

  useEffect(() => {
    listLocations().then((res) => setLocations(res.data ?? []));
  }, []);

  useEffect(() => {
    if (selectedDepartment) setLocationId(selectedDepartment.locationId);
  }, [selectedDepartment]);

  useEffect(() => {
    if (visible) {
      setPatientId('');
      setPatientData([]);
      setProviderId(initialProviderId ?? '');
      setDepartmentId('');
      setLocationId('');
      setAppointmentType('');
      setScheduledDateTime(initialDateTime ?? null);
      setDurationMinutes(15);
      setReasonForVisit('');
      setNotes('');
      setErrors({});
      setConflictError('');
    }
  }, [visible, initialDateTime, initialProviderId]);

  const patientItemTemplate = (data: PatientSummaryDto) =>
    `${data.lastName}, ${data.firstName} — MRN ${data.medicalRecordNumber}`;

  const validateField = (name: FieldName, value: unknown): string => {
    if (!value || (Array.isArray(value) && value.length === 0)) {
      const label = name === 'scheduledDateTime' ? 'Date & time' : name[0].toUpperCase() + name.slice(1);
      return `${label} is required`;
    }
    return '';
  };

  const handleBlur = (name: FieldName, value: unknown) => {
    setErrors((prev) => ({ ...prev, [name]: validateField(name, value) }));
  };

  const runValidation = (): boolean => {
    const next: Partial<Record<FieldName, string>> = {
      patient: validateField('patient', patientId),
      provider: validateField('provider', providerId),
      department: validateField('department', departmentId),
      location: validateField('location', locationId),
      scheduledDateTime: validateField('scheduledDateTime', scheduledDateTime),
      appointmentType: validateField('appointmentType', appointmentType),
      reasonForVisit: validateField('reasonForVisit', reasonForVisit),
    };
    setErrors(next);
    return !Object.values(next).some(Boolean);
  };

  const canSubmit =
    patientId && providerId && departmentId && locationId && appointmentType && scheduledDateTime && reasonForVisit;

  const handleSubmit = async () => {
    if (submitting) return;
    if (!runValidation() || !canSubmit || !scheduledDateTime) return;
    setConflictError('');
    setSubmitting(true);
    try {
      const conflicts = await getAppointmentConflicts(
        providerId,
        scheduledDateTime.toISOString(),
        durationMinutes
      );
      if (conflicts.data && conflicts.data.length > 0) {
        setConflictError('Provider has an overlapping appointment at this time.');
        setSubmitting(false);
        return;
      }
      onSubmit({
        patientId,
        providerId,
        departmentId,
        locationId,
        appointmentType,
        scheduledDateTime: scheduledDateTime.toISOString(),
        durationMinutes,
        reasonForVisit,
        notes,
      });
    } catch {
      setConflictError('Could not verify conflicts. Try again.');
    } finally {
      setSubmitting(false);
    }
  };

  const dialogButtons: ButtonPropsModel[] = [
    {
      click: handleSubmit,
      buttonModel: {
        content: 'Book Appointment',
        cssClass: 'e-primary',
        isPrimary: true,
        disabled: !canSubmit || loading || submitting,
      },
    },
    { click: onClose, buttonModel: { content: 'Cancel', cssClass: 'e-outline' } },
  ];

  const patientFields = { value: 'patientId', text: 'display' };

  const providerData = useMemo(
    () =>
      filteredProviders.map((p) => ({
        ...p,
        displayName: `Dr. ${p.lastName} — ${p.specialty}`,
      })),
    [filteredProviders]
  );

  const durationOptions = [
    { text: '15 min', value: 15 },
    { text: '30 min', value: 30 },
    { text: '45 min', value: 45 },
    { text: '60 min', value: 60 },
  ];

  const appointmentTypeOptions = [
    'New Patient',
    'Follow-Up',
    'Annual Physical',
    'Urgent Visit',
    'Consultation',
    'Procedure',
  ];

  return (
    <DialogComponent
      visible={visible}
      header="New Appointment"
      showCloseIcon
      close={onClose}
      width="640px"
      isModal
      buttons={dialogButtons}
    >
      <div
        style={{ display: 'flex', flexDirection: 'column', gap: 14, padding: '8px 0' }}
      >
        <div>
          <label style={{ fontWeight: 600, fontSize: 13 }}>Patient *</label>
          <AutoCompleteComponent
            cssClass={errors.patient ? 'e-error' : ''}
            dataSource={patientData as any}
            fields={patientFields}
            itemTemplate={patientItemTemplate as any}
            placeholder="Search by name or MRN"
            minLength={2}
            suggestionCount={10}
            noRecordsTemplate={patientLoading ? 'Searching…' : 'No patients found'}
            filterType="Contains"
            ignoreCase={true}
            sortOrder="Ascending"
            filtering={(args: any) => {
              if (!args.text || args.text.length < 2) {
                args.updateData([] as any);
                return;
              }
              setPatientLoading(true);
              listPatients(args.text)
                .then((res) => {
                  const items = (res.data?.items ?? []).map((p: PatientSummaryDto) => ({
                    ...p,
                    display: `${p.lastName}, ${p.firstName} — MRN ${p.medicalRecordNumber}`,
                  }));
                  setPatientData(items);
                  args.updateData(items);
                })
                .catch(() => {
                  args.updateData([] as any);
                })
                .finally(() => setPatientLoading(false));
            }}
            change={(e: { value?: string; itemData?: any }) => {
              const fromItem = e.itemData?.patientId as string | undefined;
              const fromValue = typeof e.value === 'string' ? e.value : '';
              const id = fromItem || fromValue || '';
              setPatientId(id);
              handleBlur('patient', id);
            }}
            value={patientId || undefined}
          />
          {errors.patient && <FormFieldError message={errors.patient} />}
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
          <div>
            <label style={{ fontWeight: 600, fontSize: 13 }}>Department *</label>
            <DropDownListComponent
              cssClass={errors.department ? 'e-error' : ''}
              dataSource={withDepartmentLabel(departments) as any}
              fields={{ text: 'displayLabel', value: 'departmentId' }}
              placeholder="Select department"
              sortOrder="Ascending"
              change={(e: DropDownChangeArgs) => {
                setDepartmentId((e.value as string) ?? '');
                handleBlur('department', e.value ?? '');
              }}
              value={departmentId}
            />
            {errors.department && <FormFieldError message={errors.department} />}
          </div>
          <div>
            <label style={{ fontWeight: 600, fontSize: 13 }}>Location *</label>
            <DropDownListComponent
              cssClass={errors.location ? 'e-error' : ''}
              dataSource={locations as any}
              fields={{ text: 'locationName', value: 'locationId' }}
              placeholder="Select location"
              sortOrder="Ascending"
              change={(e: DropDownChangeArgs) => {
                setLocationId((e.value as string) ?? '');
                handleBlur('location', e.value ?? '');
              }}
              value={locationId}
              enabled={!!departmentId}
            />
            {errors.location && <FormFieldError message={errors.location} />}
          </div>
        </div>

        <div>
          <label style={{ fontWeight: 600, fontSize: 13 }}>Provider *</label>
          <AutoCompleteComponent
            cssClass={errors.provider ? 'e-error' : ''}
            dataSource={providerData}
            fields={{ value: 'providerId', text: 'displayName' }}
            placeholder={departmentId ? 'Select provider' : 'Select a department first'}
            sortOrder="Ascending"
            change={(e: DropDownChangeArgs) => {
              setProviderId((e.value as string) ?? '');
              handleBlur('provider', e.value ?? '');
            }}
            value={providerId}
            enabled={!!departmentId}
          />
          {errors.provider && <FormFieldError message={errors.provider} />}
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 12 }}>
          <div>
            <label style={{ fontWeight: 600, fontSize: 13 }}>Date & Time *</label>
            <DateTimePickerComponent
              cssClass={errors.scheduledDateTime || conflictError ? 'e-error' : ''}
              value={scheduledDateTime ?? undefined}
              change={(e: DateChangeArgs) => {
                setScheduledDateTime((e.value as Date) ?? null);
                handleBlur('scheduledDateTime', e.value ?? null);
                setConflictError('');
              }}
              style={{ width: '100%' }}
            />
            {errors.scheduledDateTime && <FormFieldError message={errors.scheduledDateTime} />}
            {conflictError && <FormFieldError message={conflictError} />}
          </div>
          <div>
            <label style={{ fontWeight: 600, fontSize: 13 }}>Duration (min) *</label>
            <DropDownListComponent
              dataSource={durationOptions as any}
              fields={{ text: 'text', value: 'value' }}
              placeholder="Duration"
              sortOrder="Ascending"
              change={(e: DropDownChangeArgs) => setDurationMinutes(Number(e.value) || 15)}
              value={durationMinutes}
            />
          </div>
          <div>
            <label style={{ fontWeight: 600, fontSize: 13 }}>Type *</label>
            <DropDownListComponent
              cssClass={errors.appointmentType ? 'e-error' : ''}
              dataSource={appointmentTypeOptions}
              placeholder="Appointment type"
              sortOrder="Ascending"
              change={(e: DropDownChangeArgs) => {
                setAppointmentType((e.value as string) ?? '');
                handleBlur('appointmentType', e.value ?? '');
              }}
              value={appointmentType}
            />
            {errors.appointmentType && <FormFieldError message={errors.appointmentType} />}
          </div>
        </div>

        <div>
          <label style={{ fontWeight: 600, fontSize: 13 }}>Reason for Visit *</label>
          <TextBoxComponent
            cssClass={errors.reasonForVisit ? 'e-error' : ''}
            placeholder="Enter reason for visit"
            value={reasonForVisit}
            change={(e: { value?: string }) => setReasonForVisit(e.value ?? '')}
            blur={() => handleBlur('reasonForVisit', reasonForVisit)}
            multiline
            style={{ width: '100%' }}
          />
          {errors.reasonForVisit && <FormFieldError message={errors.reasonForVisit} />}
        </div>

        <div>
          <label style={{ fontWeight: 600, fontSize: 13 }}>Notes</label>
          <TextBoxComponent
            placeholder="Additional notes"
            value={notes}
            change={(e: { value?: string }) => setNotes(e.value ?? '')}
            multiline
            style={{ width: '100%' }}
          />
        </div>
      </div>
    </DialogComponent>
  );
};

// Angular/src/app/pages/schedule/new-appointment-dialog.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ChangeDetectionStrategy,
  signal,
  computed,
  inject,
  OnInit,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { of } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import {
  DialogModule,
  ButtonPropsModel,
} from '@syncfusion/ej2-angular-popups';
import {
  AutoCompleteModule,
  DropDownListModule,
  FilteringEventArgs,
  ChangeEventArgs as DropDownChangeArgs,
  SelectEventArgs,
} from '@syncfusion/ej2-angular-dropdowns';
import {
  DateTimePickerModule,
  ChangeEventArgs as DateChangeArgs,
} from '@syncfusion/ej2-angular-calendars';
import { TextBoxModule } from '@syncfusion/ej2-angular-inputs';
import { ButtonModule } from '@syncfusion/ej2-angular-buttons';
import { HealthcareService } from '../../core/api/healthcare.service';
import { FormFieldErrorComponent } from '../../shared/form-field-error/form-field-error.component';
import type {
  PatientSummaryDto,
  ProviderSummaryDto,
  DepartmentDto,
  LocationDto,
  CreateAppointmentRequest,
} from '../../core/models/dtos';

type FieldName =
  | 'patient'
  | 'provider'
  | 'department'
  | 'location'
  | 'scheduledDateTime'
  | 'appointmentType'
  | 'reasonForVisit';

interface PatientOption extends PatientSummaryDto {
  display: string;
}

interface ProviderOption extends ProviderSummaryDto {
  displayName: string;
}

@Component({
  selector: 'app-new-appointment-dialog',
  standalone: true,
  imports: [
    CommonModule,
    DialogModule,
    AutoCompleteModule,
    DropDownListModule,
    DateTimePickerModule,
    TextBoxModule,
    ButtonModule,
    FormFieldErrorComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './new-appointment-dialog.component.html',
  styleUrl: './new-appointment-dialog.component.scss',
})
export class NewAppointmentDialogComponent implements OnInit {
  private healthcare = inject(HealthcareService);

  @Input() visible = false;
  @Input() initialDateTime?: Date | null;
  @Input() initialProviderId?: string | null;
  @Input({ required: true }) providers: ProviderSummaryDto[] = [];
  @Input({ required: true }) departments: DepartmentDto[] = [];
  @Output() onClose = new EventEmitter<void>();
  @Output() onSubmit = new EventEmitter<CreateAppointmentRequest>();

  readonly patientId = signal('');
  readonly patients = signal<PatientOption[]>([]);
  readonly providerId = signal('');
  readonly departmentId = signal('');
  readonly locationId = signal('');
  readonly locations = signal<LocationDto[]>([]);
  readonly appointmentType = signal('');
  readonly scheduledDateTime = signal<Date | null>(null);
  readonly durationMinutes = signal(15);
  readonly reasonForVisit = signal('');
  readonly notes = signal('');
  readonly errors = signal<Partial<Record<FieldName, string>>>({});
  readonly conflictError = signal('');
  readonly submitting = signal(false);

  readonly patientFields = { value: 'patientId', text: 'display' };
  readonly providerFields = { value: 'providerId', text: 'displayName' };
  readonly locationFields = { text: 'locationName', value: 'locationId' };
  readonly departmentFields = { text: 'displayLabel', value: 'departmentId' };
  readonly durationFields = { text: 'text', value: 'value' };
  readonly durationOptions = [
    { text: '15 min', value: 15 },
    { text: '30 min', value: 30 },
    { text: '45 min', value: 45 },
    { text: '60 min', value: 60 },
  ];
  readonly appointmentTypeOptions = [
    'New Patient',
    'Follow-Up',
    'Annual Physical',
    'Urgent Visit',
    'Consultation',
    'Procedure',
  ];

  readonly departmentOptions = computed(() =>
    this.departments.map((d) => ({ ...d, displayLabel: `${d.departmentName} — ${d.locationName}` }))
  );

  readonly filteredProviders = computed<ProviderOption[]>(() => {
    const dept = this.departmentId();
    const list = dept ? this.providers.filter((p) => p.departmentId === dept) : this.providers;
    return list.map((p) => ({ ...p, displayName: `Dr. ${p.lastName} — ${p.specialty}` }));
  });

  readonly selectedDepartment = computed(() =>
    this.departments.find((d) => d.departmentId === this.departmentId())
  );

  readonly canSubmit = computed(() =>
    !!(
      this.patientId() &&
      this.providerId() &&
      this.departmentId() &&
      this.locationId() &&
      this.appointmentType() &&
      this.scheduledDateTime() &&
      this.reasonForVisit()
    )
  );

  readonly dialogButtons = computed<ButtonPropsModel[]>(() => [
    {
      click: () => this.handleSubmit(),
      buttonModel: {
        content: 'Book Appointment',
        cssClass: 'e-primary',
        isPrimary: true,
        disabled: !this.canSubmit() || this.submitting(),
      },
    },
    {
      click: () => this.onClose.emit(),
      buttonModel: { content: 'Cancel', cssClass: 'e-outline' },
    },
  ]);

  ngOnInit(): void {
    this.healthcare
      .listLocations()
      .pipe(map((res) => (res.status === 'ok' ? res.data ?? [] : [])))
      .subscribe((locs) => this.locations.set(locs));

    if (this.initialProviderId) this.providerId.set(this.initialProviderId);
    if (this.initialDateTime) this.scheduledDateTime.set(this.initialDateTime);
  }

  onPatientFiltering(e: FilteringEventArgs): void {
    if (!e.text || e.text.length < 2) {
      e.updateData([]);
      return;
    }
    e.preventDefaultAction = true;
    this.healthcare
      .listPatients(e.text, 0, 20)
      .pipe(
        map((res) => (res.status === 'ok' ? res.data?.items ?? [] : [])),
        catchError(() => of([]))
      )
      .subscribe((items) => {
        const options = items.map((p) => ({ ...p, display: `${p.lastName}, ${p.firstName} — MRN ${p.medicalRecordNumber}` }));
        e.updateData(options as unknown as { [key: string]: Object }[]);
      });
  }

  onPatientSelect(e: SelectEventArgs): void {
    const item = e.itemData as unknown as PatientOption | null;
    const id = item?.patientId ?? '';
    this.patientId.set(id);
    this.validateField('patient', id);
  }

  onProviderFiltering(e: FilteringEventArgs): void {
    e.preventDefaultAction = true;
    const text = (e.text || '').toLowerCase();
    const options = this.filteredProviders().filter((p) => p.displayName.toLowerCase().includes(text));
    e.updateData(options as unknown as { [key: string]: Object }[]);
  }

  onDepartmentChange(args: DropDownChangeArgs): void {
    const value = (args.value as string) ?? '';
    this.departmentId.set(value);
    const dept = this.departments.find((d) => d.departmentId === value);
    this.locationId.set(dept?.locationId ?? '');
    this.providerId.set('');
    this.validateField('department', value);
  }

  onLocationChange(args: DropDownChangeArgs): void {
    const value = (args.value as string) ?? '';
    this.locationId.set(value);
    this.validateField('location', value);
  }

  onProviderSelect(args: DropDownChangeArgs): void {
    const item = args.itemData as unknown as ProviderOption | null;
    const value = item?.providerId ?? '';
    this.providerId.set(value);
    this.validateField('provider', value);
  }

  onDateTimeChange(args: DateChangeArgs): void {
    this.scheduledDateTime.set((args.value as Date) ?? null);
    this.validateField('scheduledDateTime', args.value);
    this.conflictError.set('');
  }

  onDurationChange(args: DropDownChangeArgs): void {
    this.durationMinutes.set(Number(args.value) || 15);
  }

  onTypeChange(args: DropDownChangeArgs): void {
    const value = (args.value as string) ?? '';
    this.appointmentType.set(value);
    this.validateField('appointmentType', value);
  }

  onReasonChange(value: string | undefined): void {
    this.reasonForVisit.set(value ?? '');
  }

  onReasonBlur(): void {
    this.validateField('reasonForVisit', this.reasonForVisit());
  }

  onNotesChange(value: string | undefined): void {
    this.notes.set(value ?? '');
  }

  private validateField(name: FieldName, value: unknown): void {
    const err = this.validateValue(name, value);
    this.errors.update((prev) => ({ ...prev, [name]: err }));
  }

  private validateValue(name: FieldName, value: unknown): string {
    if (!value || (Array.isArray(value) && value.length === 0)) {
      const label = name === 'scheduledDateTime' ? 'Date & time' : name[0].toUpperCase() + name.slice(1);
      return `${label} is required`;
    }
    return '';
  }

  private runValidation(): boolean {
    const next: Partial<Record<FieldName, string>> = {
      patient: this.validateValue('patient', this.patientId()),
      provider: this.validateValue('provider', this.providerId()),
      department: this.validateValue('department', this.departmentId()),
      location: this.validateValue('location', this.locationId()),
      scheduledDateTime: this.validateValue('scheduledDateTime', this.scheduledDateTime()),
      appointmentType: this.validateValue('appointmentType', this.appointmentType()),
      reasonForVisit: this.validateValue('reasonForVisit', this.reasonForVisit()),
    };
    this.errors.set(next);
    return !Object.values(next).some(Boolean);
  }

  handleSubmit(): void {
    if (this.submitting()) return;
    if (!this.runValidation() || !this.canSubmit() || !this.scheduledDateTime()) return;
    this.conflictError.set('');
    this.submitting.set(true);
    this.healthcare
      .getAppointmentConflicts(this.providerId(), this.scheduledDateTime()!.toISOString(), this.durationMinutes())
      .pipe(
        map((res) => (res.status === 'ok' ? res.data ?? [] : [])),
        catchError(() => of([]))
      )
      .subscribe((conflicts) => {
        if (conflicts && conflicts.length > 0) {
          this.conflictError.set('Provider has an overlapping appointment at this time.');
          this.submitting.set(false);
          return;
        }
        this.submitting.set(false);
        this.onSubmit.emit({
          patientId: this.patientId(),
          providerId: this.providerId(),
          departmentId: this.departmentId(),
          locationId: this.locationId(),
          appointmentType: this.appointmentType(),
          scheduledDateTime: this.scheduledDateTime()!.toISOString(),
          durationMinutes: this.durationMinutes(),
          reasonForVisit: this.reasonForVisit(),
          notes: this.notes(),
        });
      });
  }
}

<ejs-dialog
  [visible]="visible"
  header="New Appointment"
  [showCloseIcon]="true"
  (close)="onClose.emit()"
  width="600px"
  [isModal]="true"
  [buttons]="dialogButtons()">
  <div class="dialog-body">
    <div>
      <label class="field-label">Patient *</label>
    </div>
    <ejs-autocomplete
      [dataSource]="patients()"
      [fields]="patientFields"
      placeholder="Search by name or MRN"
      [minLength]="2"
      [suggestionCount]="10"
      [allowFiltering]="true"
      noRecordsTemplate="No patients found"
      filterType="Contains"
      [ignoreCase]="true"
      [sortOrder]="'Ascending'"
      (filtering)="onPatientFiltering($event)"
      (select)="onPatientSelect($event)">
    </ejs-autocomplete>
    @if (errors().patient) {
      <app-form-field-error [message]="errors().patient!"></app-form-field-error>
    }

    <div class="grid-2">
      <div>
        <label class="field-label">Department *</label>
        <ejs-dropdownlist
          [dataSource]="departmentOptions()"
          [fields]="departmentFields"
          placeholder="Select department"
          [sortOrder]="'Ascending'"
          (change)="onDepartmentChange($event)">
        </ejs-dropdownlist>
        @if (errors().department) {
          <app-form-field-error [message]="errors().department!"></app-form-field-error>
        }
      </div>
      <div>
        <label class="field-label">Location *</label>
        <ejs-dropdownlist
          [dataSource]="locations()"
          [fields]="locationFields"
          placeholder="Select location"
          [value]="locationId()"
          [enabled]="!!departmentId()"
          [sortOrder]="'Ascending'"
          (change)="onLocationChange($event)">
        </ejs-dropdownlist>
        @if (errors().location) {
          <app-form-field-error [message]="errors().location!"></app-form-field-error>
        }
      </div>
    </div>

    <div>
      <label class="field-label">Provider *</label>
      <ejs-autocomplete
        [dataSource]="filteredProviders()"
        [fields]="providerFields"
        [placeholder]="departmentId() ? 'Select provider' : 'Select a department first'"
        [value]="providerId()"
        [enabled]="!!departmentId()"
        [allowCustom]="false"
        [sortOrder]="'Ascending'"
        (filtering)="onProviderFiltering($event)"
        (change)="onProviderSelect($event)">
      </ejs-autocomplete>
      @if (errors().provider) {
        <app-form-field-error [message]="errors().provider!"></app-form-field-error>
      }
    </div>

    <div class="grid-3">
      <div>
        <label class="field-label">Date & Time *</label>
        <ejs-datetimepicker
          [value]="scheduledDateTime() ?? undefined"
          (change)="onDateTimeChange($event)"
          width="100%">
        </ejs-datetimepicker>
        @if (errors().scheduledDateTime) {
          <app-form-field-error [message]="errors().scheduledDateTime!"></app-form-field-error>
        }
        @if (conflictError()) {
          <app-form-field-error [message]="conflictError()!"></app-form-field-error>
        }
      </div>
      <div>
        <label class="field-label">Duration (min) *</label>
        <ejs-dropdownlist
          [dataSource]="durationOptions"
          [fields]="durationFields"
          placeholder="Duration"
          [value]="durationMinutes()"
          [sortOrder]="'Ascending'"
          (change)="onDurationChange($event)">
        </ejs-dropdownlist>
      </div>
      <div>
        <label class="field-label">Type *</label>
        <ejs-dropdownlist
          [dataSource]="appointmentTypeOptions"
          placeholder="Appointment type"
          [value]="appointmentType()"
          [sortOrder]="'Ascending'"
          (change)="onTypeChange($event)">
        </ejs-dropdownlist>
        @if (errors().appointmentType) {
          <app-form-field-error [message]="errors().appointmentType!"></app-form-field-error>
        }
      </div>
    </div>

    <div>
      <label class="field-label">Reason for Visit *</label>
      <ejs-textbox
        placeholder="Enter reason for visit"
        [value]="reasonForVisit()"
        [multiline]="true"
        width="100%"
        (input)="onReasonChange($any($event).value)"
        (blur)="onReasonBlur()">
      </ejs-textbox>
      @if (errors().reasonForVisit) {
        <app-form-field-error [message]="errors().reasonForVisit!"></app-form-field-error>
      }
    </div>

    <div>
      <label class="field-label">Notes</label>
      <ejs-textbox
        placeholder="Additional notes"
        [value]="notes()"
        [multiline]="true"
        width="100%"
        (input)="onNotesChange($any($event).value)">
      </ejs-textbox>
    </div>
  </div>
</ejs-dialog>
