// Angular/src/app/pages/providers/provider-analytics-tab.component.ts
import { Component, Input, ChangeDetectionStrategy, inject, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  ChartModule,
  CategoryService,
  ColumnSeriesService,
  SplineSeriesService,
  LegendService,
  TooltipService,
  HighlightService,
  SelectionService,
} from '@syncfusion/ej2-angular-charts';
import { LoadingStateComponent } from '../../shared/loading-state/loading-state.component';
import { EmptyStateComponent } from '../../shared/empty-state/empty-state.component';
import { ErrorBannerComponent } from '../../shared/error-banner/error-banner.component';
import {
  SERIES_TEAL,
  SERIES_ROSE,
  buildValueAxis,
  chartFillHeight,
  HIDDEN_LEGEND_SETTINGS,
  COLUMN_WIDTH,
  COLUMN_CORNER_RADIUS,
  CHART_SELECTION_MODE,
  CHART_HIGHLIGHT_MODE,
  chartThemeName,
} from '../../core/utils/chart-theme';
import { ThemeService } from '../../core/theme/theme.service';

interface TrendPoint {
  month: string;
  rate: number;
}

@Component({
  selector: 'app-provider-analytics-tab',
  standalone: true,
  imports: [
    CommonModule,
    ChartModule,
    LoadingStateComponent,
    EmptyStateComponent,
    ErrorBannerComponent,
  ],
  providers: [
    CategoryService,
    ColumnSeriesService,
    SplineSeriesService,
    LegendService,
    TooltipService,
    HighlightService,
    SelectionService,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './provider-analytics-tab.component.html',
  styleUrl: './provider-analytics-tab.component.scss',
})
export class ProviderAnalyticsTabComponent {
  private theme = inject(ThemeService);

  readonly chartTheme = computed(() => chartThemeName(this.theme.resolved()));
  readonly chartFillHeight = chartFillHeight;

  @Input({ required: true }) utilizationData: TrendPoint[] = [];
  @Input() utilizationLoading = false;
  @Input() utilizationError: string | null = null;
  @Input() onUtilizationRetry: () => void = () => {};

  @Input({ required: true }) noShowData: TrendPoint[] = [];
  @Input() noShowLoading = false;
  @Input() noShowError: string | null = null;
  @Input() onNoShowRetry: () => void = () => {};

  @Input() departmentName = '';

  readonly categoryXAxis = { valueType: 'Category' as const };
  get utilizationYAxis() {
    return buildValueAxis(this.utilizationData.map((d) => d.rate), {
      title: 'Utilization %',
      labelFormat: '{value}%',
    });
  }
  get noShowYAxis() {
    return buildValueAxis(this.noShowData.map((d) => d.rate), {
      title: 'No-Show %',
      labelFormat: '{value}%',
    });
  }
  readonly tooltip = { enable: true };
  readonly hiddenLegend = HIDDEN_LEGEND_SETTINGS;
  readonly columnWidth = COLUMN_WIDTH;
  readonly cornerRadius = COLUMN_CORNER_RADIUS;
  readonly selectionMode = CHART_SELECTION_MODE;
  readonly highlightMode = CHART_HIGHLIGHT_MODE;
  readonly seriesTeal = SERIES_TEAL;
  readonly seriesRose = SERIES_ROSE;

  retryUtilization(): void {
    this.onUtilizationRetry();
  }

  retryNoShow(): void {
    this.onNoShowRetry();
  }
}

<div class="analytics-grid">
  <div class="card">
    <div class="card-title">Utilization Trend</div>
    @if (utilizationLoading) {
      <app-loading-state inline label="Loading utilization…"></app-loading-state>
    } @else if (utilizationError) {
      <app-error-banner title="Unable to load utilization" [message]="utilizationError" (retry)="retryUtilization()"></app-error-banner>
    } @else if (utilizationData.length === 0) {
      <app-empty-state title="No utilization data" description="No appointments in the last 6 months."></app-empty-state>
    } @else {
      <div [style.height]="chartFillHeight({ rows: 1, reserve: 420, floor: 240 })">
      <ejs-chart
        [theme]="chartTheme()"
        [primaryXAxis]="categoryXAxis"
        [primaryYAxis]="utilizationYAxis"
        [legendSettings]="hiddenLegend"
        [tooltip]="tooltip"
        [selectionMode]="selectionMode"
        [highlightMode]="highlightMode"
        height="100%">
        <e-series-collection>
          <e-series
            type="Spline"
            [dataSource]="utilizationData"
            xName="month"
            yName="rate"
            name="Utilization %"
            [fill]="seriesTeal"
            [width]="2"
            [marker]="{ visible: true, width: 7, height: 7 }">
          </e-series>
        </e-series-collection>
      </ejs-chart>
      </div>
    }
  </div>

  <div class="card">
    <div class="card-title">No-Show Rate Trend</div>
    <div class="card-subtitle">Department-level trend ({{ departmentName }})</div>
    @if (noShowLoading) {
      <app-loading-state inline label="Loading no-show trend…"></app-loading-state>
    } @else if (noShowError) {
      <app-error-banner title="Unable to load no-show trend" [message]="noShowError" (retry)="retryNoShow()"></app-error-banner>
    } @else if (noShowData.length === 0) {
      <app-empty-state title="No no-show data" description="No appointments in the last 6 months."></app-empty-state>
    } @else {
      <div [style.height]="chartFillHeight({ rows: 1, reserve: 420, floor: 240 })">
      <ejs-chart
        [theme]="chartTheme()"
        [primaryXAxis]="categoryXAxis"
        [primaryYAxis]="noShowYAxis"
        [legendSettings]="hiddenLegend"
        [tooltip]="tooltip"
        [selectionMode]="selectionMode"
        [highlightMode]="highlightMode"
        height="100%">
        <e-series-collection>
          <e-series
            type="Column"
            [dataSource]="noShowData"
            xName="month"
            yName="rate"
            name="No-Show %"
            [fill]="seriesRose"
            [columnWidth]="columnWidth"
            [cornerRadius]="cornerRadius">
          </e-series>
        </e-series-collection>
      </ejs-chart>
      </div>
    }
  </div>
</div>

// React/src/components/providers/ProviderAnalyticsTab.tsx
import React from 'react';
import {
  ChartComponent,
  SeriesCollectionDirective,
  SeriesDirective,
  Inject as ChartInject,
  ColumnSeries,
  SplineSeries,
  Category,
  Legend,
  Tooltip,
} from '@syncfusion/ej2-react-charts';
import { LoadingState } from '@components/shared/LoadingState';
import { EmptyState } from '@components/shared/EmptyState';
import { ErrorBanner } from '@components/shared/ErrorBanner';
import {
  SERIES_TEAL,
  SERIES_ROSE,
  buildValueAxis,
  chartFillHeight,
  chartInteraction,
  chartThemeName,
  COLUMN_STYLE,
  Highlight,
  Selection,
} from '../../utils/chartTheme';
import { useTheme } from '../../theme/ThemeProvider';

interface TrendPoint {
  month: string;
  rate: number;
}

export interface ProviderAnalyticsTabProps {
  utilizationData: TrendPoint[];
  utilizationLoading: boolean;
  utilizationError: string | null;
  onUtilizationRetry: () => void;
  noShowData: TrendPoint[];
  noShowLoading: boolean;
  noShowError: string | null;
  onNoShowRetry: () => void;
  departmentName: string;
}

const card: React.CSSProperties = {
  background: 'var(--color-sf-bg-primary)',
  borderRadius: 8,
  padding: 20,
  boxShadow: 'var(--shadow-default)',
};

export const ProviderAnalyticsTab: React.FC<ProviderAnalyticsTabProps> = ({
  utilizationData,
  utilizationLoading,
  utilizationError,
  onUtilizationRetry,
  noShowData,
  noShowLoading,
  noShowError,
  onNoShowRetry,
  departmentName,
}) => {
  const { resolved } = useTheme();
  const chartTheme = chartThemeName(resolved);
  return (
  <div className="responsive-collapse-grid" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20 }}>
    <div style={card}>
      <div style={{ fontWeight: 600, fontSize: 16, marginBottom: 12 }}>Utilization Trend</div>
      {utilizationLoading ? (
        <LoadingState inline label="Loading utilization…" />
      ) : utilizationError ? (
        <ErrorBanner message={utilizationError} onRetry={onUtilizationRetry} />
      ) : utilizationData.length === 0 ? (
        <EmptyState title="No utilization data" description="No appointments in the last 6 months." />
      ) : (
        <div style={{ height: chartFillHeight({ rows: 1, reserve: 420, floor: 240 }) }}>
        <ChartComponent
          theme={chartTheme}
          primaryXAxis={{ valueType: 'Category' }}
          primaryYAxis={buildValueAxis(utilizationData.map((d) => d.rate), { title: 'Utilization %', labelFormat: '{value}%' })}
          legendSettings={{ visible: false }}
          height="100%"
          tooltip={{ enable: true }}
          {...chartInteraction}
        >
          <ChartInject services={[SplineSeries, Category, Legend, Tooltip, Highlight, Selection]} />
          <SeriesCollectionDirective>
            <SeriesDirective
              dataSource={utilizationData}
              xName="month"
              yName="rate"
              name="Utilization %"
              type="Spline"
              fill={SERIES_TEAL}
              width={2}
              marker={{ visible: true, width: 7, height: 7 }}
            />
          </SeriesCollectionDirective>
        </ChartComponent>
        </div>
      )}
    </div>
    <div style={card}>
      <div style={{ fontWeight: 600, fontSize: 16, marginBottom: 4 }}>No-Show Rate Trend</div>
      <div style={{ fontSize: 11, color: 'var(--color-sf-fg-quinary)', marginBottom: 12 }}>Department-level trend ({departmentName})</div>
      {noShowLoading ? (
        <LoadingState inline label="Loading no-show trend…" />
      ) : noShowError ? (
        <ErrorBanner message={noShowError} onRetry={onNoShowRetry} />
      ) : noShowData.length === 0 ? (
        <EmptyState title="No no-show data" description="No appointments in the last 6 months." />
      ) : (
        <div style={{ height: chartFillHeight({ rows: 1, reserve: 420, floor: 240 }) }}>
        <ChartComponent
          theme={chartTheme}
          primaryXAxis={{ valueType: 'Category' }}
          primaryYAxis={buildValueAxis(noShowData.map((d) => d.rate), { title: 'No-Show %', labelFormat: '{value}%' })}
          legendSettings={{ visible: false }}
          height="100%"
          tooltip={{ enable: true }}
          {...chartInteraction}
        >
          <ChartInject services={[ColumnSeries, Category, Legend, Tooltip, Highlight, Selection]} />
          <SeriesCollectionDirective>
            <SeriesDirective dataSource={noShowData} xName="month" yName="rate" name="No-Show %" type="Column" fill={SERIES_ROSE} {...COLUMN_STYLE} />
          </SeriesCollectionDirective>
        </ChartComponent>
        </div>
      )}
    </div>
  </div>
  );
};
