// React/src/components/shared/ThemeSwitcher.tsx
import React, { useEffect, useRef, useState } from 'react';
import { Sun, Moon, Monitor, Check } from 'lucide-react';
import { useTheme, type ThemeMode } from '../../theme/ThemeProvider';

const OPTIONS: { mode: ThemeMode; label: string; icon: React.ElementType }[] = [
  { mode: 'light', label: 'Light', icon: Sun },
  { mode: 'dark', label: 'Dark', icon: Moon },
  { mode: 'system', label: 'System', icon: Monitor },
];


export const ThemeSwitcher: React.FC = () => {
  const { mode, resolved, setMode } = useTheme();
  const [open, setOpen] = useState(false);
  const rootRef = useRef<HTMLDivElement>(null);

  
  useEffect(() => {
    if (!open) return;
    const onPointer = (e: MouseEvent) => {
      if (rootRef.current && !rootRef.current.contains(e.target as Node)) setOpen(false);
    };
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setOpen(false);
    };
    document.addEventListener('mousedown', onPointer);
    document.addEventListener('keydown', onKey);
    return () => {
      document.removeEventListener('mousedown', onPointer);
      document.removeEventListener('keydown', onKey);
    };
  }, [open]);

  const TriggerIcon = resolved === 'dark' ? Moon : Sun;

  return (
    <div ref={rootRef} style={{ position: 'relative', display: 'flex', alignItems: 'center' }}>
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        aria-haspopup="menu"
        aria-expanded={open}
        aria-label="Change theme"
        title="Change theme"
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          width: 34,
          height: 34,
          borderRadius: 'var(--radius-8)',
          border: '1px solid var(--color-sf-border-secondary)',
          background: 'var(--color-sf-bg-primary)',
          color: 'var(--color-sf-fg-tertiary)',
          cursor: 'pointer',
          padding: 0,
        }}
      >
        <TriggerIcon size={18} strokeWidth={1.75} />
      </button>

      {open && (
        <div
          role="menu"
          style={{
            position: 'absolute',
            top: 'calc(100% + 6px)',
            right: 0,
            minWidth: 160,
            background: 'var(--color-sf-bg-primary)',
            border: '1px solid var(--color-sf-border-secondary)',
            borderRadius: 'var(--radius-8)',
            boxShadow: 'var(--shadow-lg)',
            padding: 4,
            zIndex: 1000,
          }}
        >
          {OPTIONS.map(({ mode: optMode, label, icon: Icon }) => {
            const active = mode === optMode;
            return (
              <button
                key={optMode}
                type="button"
                role="menuitemradio"
                aria-checked={active}
                onClick={() => {
                  setMode(optMode);
                  setOpen(false);
                }}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: 10,
                  width: '100%',
                  padding: '8px 10px',
                  border: 'none',
                  borderRadius: 'var(--radius-6)',
                  background: active ? 'var(--color-sf-bg-brand-primary)' : 'transparent',
                  color: active ? 'var(--color-sf-fg-brand-primary)' : 'var(--color-sf-fg-secondary)',
                  fontSize: 13,
                  fontWeight: active ? 600 : 500,
                  cursor: 'pointer',
                  textAlign: 'left',
                }}
              >
                <Icon size={16} strokeWidth={1.75} />
                <span style={{ flex: 1 }}>{label}</span>
                {active && <Check size={15} strokeWidth={2.25} />}
              </button>
            );
          })}
        </div>
      )}
    </div>
  );
};

// Angular/src/app/shared/theme-switcher/theme-switcher.component.ts
import { Component, inject, signal, HostListener, ElementRef, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideSun, LucideMoon, LucideMonitor, LucideCheck } from '@lucide/angular';
import { ThemeMode, ThemeService } from '../../core/theme/theme.service';

@Component({
  selector: 'app-theme-switcher',
  standalone: true,
  imports: [CommonModule, LucideSun, LucideMoon, LucideMonitor, LucideCheck],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="theme-switcher">
      <button
        type="button"
        class="theme-trigger"
        aria-haspopup="menu"
        [attr.aria-expanded]="open()"
        aria-label="Change theme"
        title="Change theme"
        (click)="open.set(!open())">
        @if (themeService.resolved() === 'dark') {
          <svg lucideMoon [size]="18" [strokeWidth]="1.75"></svg>
        } @else {
          <svg lucideSun [size]="18" [strokeWidth]="1.75"></svg>
        }
      </button>

      @if (open()) {
        <div class="theme-menu" role="menu">
          <button
            type="button"
            role="menuitemradio"
            [attr.aria-checked]="themeService.getMode() === 'light'"
            class="theme-menu-item"
            [class.active]="themeService.getMode() === 'light'"
            (click)="onSelect('light')">
            <svg lucideSun [size]="16" [strokeWidth]="1.75"></svg>
            <span class="theme-menu-label">Light</span>
            @if (themeService.getMode() === 'light') { <svg lucideCheck [size]="15" [strokeWidth]="2.25"></svg> }
          </button>
          <button
            type="button"
            role="menuitemradio"
            [attr.aria-checked]="themeService.getMode() === 'dark'"
            class="theme-menu-item"
            [class.active]="themeService.getMode() === 'dark'"
            (click)="onSelect('dark')">
            <svg lucideMoon [size]="16" [strokeWidth]="1.75"></svg>
            <span class="theme-menu-label">Dark</span>
            @if (themeService.getMode() === 'dark') { <svg lucideCheck [size]="15" [strokeWidth]="2.25"></svg> }
          </button>
          <button
            type="button"
            role="menuitemradio"
            [attr.aria-checked]="themeService.getMode() === 'system'"
            class="theme-menu-item"
            [class.active]="themeService.getMode() === 'system'"
            (click)="onSelect('system')">
            <svg lucideMonitor [size]="16" [strokeWidth]="1.75"></svg>
            <span class="theme-menu-label">System</span>
            @if (themeService.getMode() === 'system') { <svg lucideCheck [size]="15" [strokeWidth]="2.25"></svg> }
          </button>
        </div>
      }
    </div>
  `,
  styles: [`
    .theme-switcher {
      position: relative;
      display: flex;
      align-items: center;
    }
    .theme-trigger {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 34px;
      height: 34px;
      border-radius: var(--radius-8);
      border: 1px solid var(--color-sf-border-secondary);
      background: var(--color-sf-bg-primary);
      color: var(--color-sf-fg-tertiary);
      cursor: pointer;
      padding: 0;
    }
    .theme-menu {
      position: absolute;
      top: calc(100% + 6px);
      right: 0;
      min-width: 160px;
      background: var(--color-sf-bg-primary);
      border: 1px solid var(--color-sf-border-secondary);
      border-radius: var(--radius-8);
      box-shadow: var(--shadow-lg);
      padding: 4px;
      z-index: 1000;
    }
    .theme-menu-item {
      display: flex;
      align-items: center;
      gap: 10px;
      width: 100%;
      padding: 8px 10px;
      border: none;
      border-radius: var(--radius-6);
      background: transparent;
      color: var(--color-sf-fg-secondary);
      font-size: 13px;
      font-weight: 500;
      cursor: pointer;
      text-align: left;
    }
    .theme-menu-label {
      flex: 1;
    }
    .theme-menu-item.active {
      background: var(--color-sf-bg-brand-primary);
      color: var(--color-sf-fg-brand-primary);
      font-weight: 600;
    }
    .theme-menu-item:hover {
      background: var(--color-sf-bg-brand-secondary);
    }
  `],
})
export class ThemeSwitcherComponent {
  protected themeService = inject(ThemeService);
  private host = inject<ElementRef<HTMLElement>>(ElementRef);

  readonly open = signal(false);

  onSelect(id: ThemeMode): void {
    this.themeService.setMode(id);
    this.open.set(false);
  }

  @HostListener('document:click', ['$event'])
  onDocumentClick(event: MouseEvent): void {
    if (this.open() && !this.host.nativeElement.contains(event.target as Node)) {
      this.open.set(false);
    }
  }

  @HostListener('document:keydown.escape')
  onEscape(): void {
    this.open.set(false);
  }
}
